### ISSUE TITLE
NotifyIcon vanished from 3.0.0 / 3.0.1

### ISSUE THREAD

**Issue by MR-444** [lepoco/wpfui#1007]
### Describe the bug

Reading the Documentation (https://wpfui.lepo.co/api/Wpf.Ui.Tray.Controls.NotifyIcon.html) NotifyIcon should be here: Wpf.Ui.Tray.Controls 
But it is removed.  In the Wpf.Ui.xml it can't be found any more. 
( In the Release Candidate it was here:
        <member name="T:Wpf.Ui.Controls.NotifyIcon">
            <summary>
            Represents the implementation of icon in the tray menu as <see cref="T:System.Windows.FrameworkElement"/>.
            </summary>
        </member>
)
So what did I wrong or is it really absent?

### To Reproduce

Just try to find the NotifyIcon.

### Expected behavior

https://wpfui.lepo.co/api/Wpf.Ui.Tray.Controls.NotifyIcon should be found where it is described.

### OS version

Windows 11

### .NET version

.NET 8.0

### WPF-UI NuGet version

3.0.0 or 3.0.1

**Comment by pomianowski** [comment]
NotifyIcon is present in the separate package https://www.nuget.org/packages/WPF-UI.Tray since version 3.0.0

**Comment by MR-444** [comment]
Omg... thank you very much. I would not have found it…
Is this change somewhere documented?
