### ISSUE TITLE
TitleBarButton foreground  color is incorrect

### ISSUE THREAD

**Issue by sherlockforrest** [lepoco/wpfui#1020]
### Describe the bug

Before I put the mouse on it, the titlebar buttons are unclear

### To Reproduce

Before I put the mouse on it, the titlebar buttons are unclear

### Expected behavior

The color of foreground buttons does not need to change with mouseover

### Screenshots

![动画](https://github.com/lepoco/wpfui/assets/40654941/0267847d-f249-4d7c-bbf3-cbea8ad08f60)

### OS version

Windows 11 23H2

### .NET version

.net framework 4.7.2

### WPF-UI NuGet version

3.0.3

**Comment by koal44** [comment]
looks like it's already fixed (#1017).
