### ISSUE TITLE
NavigationView  Only supports two-level menus

### ISSUE THREAD

**Issue by wch66** [lepoco/wpfui#1024]
### Describe the bug

NavigationView  Only supports two-level menus？

### To Reproduce

`
NavigationItems = new ObservableCollection<object>
{
    new NavigationViewItem()
    {
        Content = "Home",
        Icon = new SymbolIcon { Symbol = SymbolRegular.Home24 },
        TargetPageType = typeof(Views.Pages.DashboardPage),
        MenuItemsSource = new ObservableCollection<object>
        {
           new NavigationViewItem()
            {
                Content = "Home1",
                Icon = new SymbolIcon { Symbol = SymbolRegular.DataHistogram24 },
                TargetPageType = typeof(Views.Pages.DataPage),
                MenuItemsSource = new ObservableCollection<object>
                    {
                       new NavigationViewItem()
                        {
                            Content = "Home2",
                            Icon = new SymbolIcon { Symbol = SymbolRegular.DataHistogram24 },
                            TargetPageType = typeof(Views.Pages.DataPage)
                        }
                    }
            }
        }
    },
`
![image](https://github.com/lepoco/wpfui/assets/36251958/12bf88c3-bd54-4f69-b0ea-ece1096b9f59)

### Expected behavior

Support multi-level menu

### OS version

win10

### .NET version

net7.0

### WPF-UI NuGet version

3.0.3.0

**Comment by pomianowski** [comment]
Hey @wch66, yes, and support for deeper menus is not planned for now.
