### ISSUE TITLE
the domain schemas.lepo.co is down

### ISSUE THREAD

**Issue by joseborges** [lepoco/wpfui#1031]
### Describe the bug

the domain schemas.lepo.co is down

### To Reproduce

the domain schemas.lepo.co is down

### Expected behavior

the domain schemas.lepo.co is down

### Screenshots

the domain schemas.lepo.co is down

### OS version

the domain schemas.lepo.co is down

### .NET version

the domain schemas.lepo.co is down

### WPF-UI NuGet version

the domain schemas.lepo.co is down

### Additional context

the domain schemas.lepo.co is down

**Comment by m0lDaViA** [comment]
Bro ... this is NOT a domain. Please close this "issue", thanks.

**Comment by m0lDaViA** [comment]
@joseborges Bro ... this is NOT a domain. Please close this "issue", thanks.

**Comment by joseborges** [comment]
Bro, it's not a domain, but isn't it needed for using WPF-UI xaml files?

**Comment by m0lDaViA** [comment]
@joseborges it is but not as domain, so close this. That's not an issue.

**Comment by joseborges** [comment]
Is there a way I can get the missing "content" expected from those endpoints? I can't find them on the repository.
