### ISSUE TITLE
SnackbarPresenter

### ISSUE THREAD

**Issue by Hykox** [lepoco/wpfui#1042]
### Describe the bug

Hello everyone,

I don't understand how to display the SnackBar on the last version. Can someone show me the code needed to make this snackbar appear?

Thanks a lot

### To Reproduce

nothing

### Expected behavior

nothing

### OS version

Windows 11

### .NET version

.NET 8

### WPF-UI NuGet version

3.0.3

**Comment by pomianowski** [comment]
Hey, the sample is in the Gallery app

https://github.com/lepoco/wpfui/blob/303f0aefcd59a142bc681415dc4360a34a15f33d/src/Wpf.Ui.Gallery/App.xaml.cs#L38
https://github.com/lepoco/wpfui/blob/303f0aefcd59a142bc681415dc4360a34a15f33d/src/Wpf.Ui.Gallery/Views/Windows/MainWindow.xaml#L70
https://github.com/lepoco/wpfui/blob/303f0aefcd59a142bc681415dc4360a34a15f33d/src/Wpf.Ui.Gallery/Views/Windows/MainWindow.xaml.cs#L30
https://github.com/lepoco/wpfui/blob/303f0aefcd59a142bc681415dc4360a34a15f33d/src/Wpf.Ui.Gallery/ViewModels/Pages/DialogsAndFlyouts/SnackbarViewModel.cs#L32-L38
