### ISSUE TITLE
PasswordBox Placeholder Not Working Properly

### ISSUE THREAD

**Issue by Taiizor** [lepoco/wpfui#1043]
### Describe the bug

PasswordBox Placeholder not working properly.

### To Reproduce

`<ui:PasswordBox
      Password="Sucrose Wallpaper Engine"
      PlaceholderEnabled="True"
      PlaceholderText="Enter a password" />`

### Expected behavior

When PlaceholderEnabled is true, Placeholder should not appear if there is data in the Password.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/41683699/db94da18-d1bb-402e-a969-d5257a744b77)

### OS version

Windows 11 24H2

### .NET version

.NET 9

### WPF-UI NuGet version

3.0.3

**Comment by textGamex** [comment]
You can set `PlaceholderEnabled` to `false` to avoid this bug; this will not affect the normal display of `PlaceholderText`. I am looking for a solution to fix it.

**Comment by Taiizor** [comment]
> You can set `PlaceholderEnabled` to `false` or remove `PlaceholderEnabled="True"` to avoid this bug; this will not affect the normal display of `PlaceholderText`. I am looking for a solution to fix it.

I'm already using this solution temporarily, but a permanent solution would be better (:
