### ISSUE TITLE
Windows Flickering on dark mode - win10

### ISSUE THREAD

**Issue by lhodhy** [lepoco/wpfui#1060]
### Describe the bug

The window will flicker on resize and maximize/restore on dark mode. There's a work around on version 2.1.0 which is AllowsTransparency="True" but this won't work on 3.0.4 because you can't set the window style to none. Is there any work around for this before migrating to v3?

### To Reproduce

Run the Demo/Gallery App and try to resize, maximize/restore.

### Expected behavior

no flickering

### OS version

Windows 10

### .NET version

.net8

### WPF-UI NuGet version

3.0.4

**Comment by pomianowski** [comment]
Window style none is not supported for FluentWindow
