### ISSUE TITLE
 ResizeMode="CanMinimize" is not working

### ISSUE THREAD

**Issue by xianyunleo** [lepoco/wpfui#1070]
### Describe the bug

 ResizeMode="CanMinimize" invalid

### To Reproduce

 ResizeMode="CanMinimize" 

### Expected behavior

![image](https://github.com/lepoco/wpfui/assets/104482255/0529b6e7-54a5-47d0-ad66-c969290a8609)
The maximize button is invalid. Unable to resize the window

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/104482255/a61889eb-09c2-4b83-b5dc-28317904f77a)

### OS version

windows 11

### .NET version

.NET 8

### WPF-UI NuGet version

3.0.0

**Comment by textGamex** [comment]
使用`TitleBar`上的`CanMaximize`属性

**Comment by xianyunleo** [comment]
@textGamex 感谢提示

 @经测试，设置TitleBar的CanMaximize=False，还是可以通过双击TitleBar，或者TitleBar右键菜单实现最大化。建议官方优化一下@pomianowski 。 
最终我是通过设置Window的ResizeMode=CanMinimize 和 TitleBar的ShowMaximize=False 完美实现。

**Comment by pomianowski** [comment]
Please describe problems thoroughly and keep isuues in English
