### ISSUE TITLE
Suggestion: Rename Icon to FontIcon

### ISSUE THREAD

**Issue by MajorXAML** [lepoco/wpfui#112]
FontIcon is a more appropriate name (in my opinion) and used in [winui](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon?view=winrt-22000) 

Though it's more like a [SymbolIcon](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbolicon?view=winrt-22000) in terms of functionality, maybe it makes sense to make two controls for the font and the built-in enum?

Something like this:
Use FontIcon to specify an icon using a Glyph value from a FontFamily
Use SymbolIcon specify an icon using a Glyph value from a Symbol enumeration

🙂

**Comment by pomianowski** [comment]
Quite a nice name, but renaming this control can be a bit of a mess at this stage.

**Comment by MajorXAML** [comment]
Yes, this is a change for the next/dev version. Resharper can help with the renaming. 

Also, in order to avoid confusion we can call the enums e.g. 

```
Symbol
SymbolFilled
```
or
```
SymbolRegular
SymbolFilled
```

**Comment by pomianowski** [comment]
> Yes, this is a change for the next/dev version. Resharper can help with the renaming. I think this will greatly simplify the documentation, since it is already created by microsoft 😁
>
More I meant that it could be a problem for people who already use this control. May think about keeping `Icon` as Obsolete, or wait for a bigger update in which much will be changed anyway.
