### ISSUE TITLE
404 Return at schemas.lepo.co

### ISSUE THREAD

**Issue by Hamzaless** [lepoco/wpfui#1158]
### Describe the bug

I've been using WPFUI for a long time, but all my projects went down the drain when this url became inaccessible
URL: https://schemas.lepo.co/wpfui/2022/xaml

### To Reproduce

- Create a new WPF project in Visual Studio.
- Add the WPFUI NuGet package version 3.0.4 to the project.
- Ensure the project is using .NET Framework 4.8.
- Attempt to access the URL https://schemas.lepo.co/wpfui/2022/xaml in the project settings or code.
- Observe the error indicating that the URL is inaccessible.
- Change the NuGet package version to another version (e.g., 3.0.3) and try accessing the URL again.
- Enable a VPN and attempt to access the URL again.
- Observe that the URL remains inaccessible despite these changes.

### Expected behavior

I expected the URL https://schemas.lepo.co/wpfui/2022/xaml to remain accessible so that my WPFUI projects could continue to function correctly. The inaccessibility of this URL should not disrupt the functionality or compilation of the WPFUI projects.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/89343438/aa2d3776-a786-43cf-be9b-8cfb41ebdddd)

### OS version

Microsoft Windows 11 Pro
10.0.22631 N/A Build 22631

### .NET version

.NET Framework 4.8

### WPF-UI NuGet version

3.0.4

**Comment by pomianowski** [comment]
This is XAML namespace, not real web address.
