### ISSUE TITLE
RichTextBox theme

### ISSUE THREAD

**Issue by ThinkFutures** [lepoco/wpfui#118]
When switching dark / light theme, the font color of RichTextBox control does not follow

**Comment by pomianowski** [comment]
`RichTextBox` does not change color dynamically because it allows individual color for each letter. The only simple solution I see in this situation is listening to the OnThemeChanged event and replacing all the letters that are in the default colors. This can be problematic to achieve.

**Comment by jimm98y** [comment]
What worked for me was to add the RichTextBox control to the UI from the code-behind, then listen for OnThemeChanged and in the event handler simply remove the control from the UI, throw it away and then create a new instance of the RichTextBox control and add it to the UI. This reloaded the default font color and resulted in the text properly changing from black to white and back again whenever the theme is changed.
