### ISSUE TITLE
Sign the assembly for strong naming for the nuget package

### ISSUE THREAD

**Issue by fsol11** [lepoco/wpfui#1185]
### Is your feature request related to a problem? Please describe

When using the library in a project you get this warning:

warning CS8002: Referenced assembly 'Wpf.Ui, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

### Describe the solution you'd like

Sign the assembly for strong naming when compiling for nuget

**Comment by HarryPitsillides** [comment]
Yes please i am hoping to use this to migrate VSTO add-ins for our company and strongly signed is a requirement to run a VSTO

**Comment by pomianowski** [comment]
Done in https://github.com/lepoco/wpfui/commit/c3a50f74ee76f53cabea9f0d19e1287e56fb15dd
