### ISSUE TITLE
WPF-UI causes Closing event cancelling to be ignored

### ISSUE THREAD

**Issue by quajak** [lepoco/wpfui#122]
**Describe the bug**  
After adding the WPF-UI the following event handler for the `Window.Closing` event fails to prevent the window from closing.

```
private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
{
    e.Cancel = true;
}
```

**To Reproduce**  
1. Create a new project using the code from the README.md
2. Add the above mentioned closing event handler to the Closing event on the window.
3. Run the project and click on the X to close the window.

**Expected behavior**  
The event handler should prevent the window from closing.

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
 - OS Windows 10
 - .NET: net 4.7.2
 - Version: 1.2.2

**Comment by quajak** [comment]
I saw that there was a commit referencing this. Does this mean its fixed in the newest version already or is still work in progress?

**Comment by pomianowski** [comment]
Hey @quajak, please check if your problem still exists in version 1.2.6.

**Comment by quajak** [comment]
It seems to be fixed! Thanks a lot!
