### ISSUE TITLE
How do I set the size of NavigationItem's Icon size and font size?

### ISSUE THREAD

**Issue by SeungHuLee** [lepoco/wpfui#123]
**Describe the bug**  
I'm using NavigationStore and I want to set Icon size and font size for child NavigationItems.
Currently, setting FontWeight works, but font size doesn't.

Additionally, I want to change the FillColor to green when clicked.
It seems I need to override ControlFillColorDefault or TextFillColorSecondary. What would be the best practice to do this?

- Screenshot without changing FontWeight and FontSize in xaml
![image](https://user-images.githubusercontent.com/39406255/161678321-69cea4b3-9f32-47d3-aef6-918228b1c267.png)
![image](https://user-images.githubusercontent.com/39406255/161678564-dc6b1765-fcca-47a8-b22c-00b1b87f5048.png)

- Screenshot with changing FontWeight and FontSize in xaml (Setting FontWeight to ExtraBold worked)
![image](https://user-images.githubusercontent.com/39406255/161678509-78ef92e7-b848-404a-8136-db91caafe68f.png)
![image](https://user-images.githubusercontent.com/39406255/161678541-77fd9106-1d50-4c45-adfa-95f9ba79933a.png)

I think I need to override ResourceDictionary's default Styles. I want to know your solutions with these.
https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Controls/NavigationStore.xaml

**Comment by michaelsd28** [comment]
To change the size you can change the content for a text block 


`             new NavigationItem()
                {

                    Content =new TextBlock() { Text = "My Text", FontSize= 13 },
                    PageTag = "settings",
                    Icon = SymbolRegular.Settings24,
                    PageType = typeof(Views.Pages.SettingsPage)
                }`
