### ISSUE TITLE
Excessive Processes of Demo Software

### ISSUE THREAD

**Issue by aaayd** [lepoco/wpfui#125]
**Describe the bug**  
From what I see, if you leave the demo software open for a long time, lots of processes will appear overtime.
Im unsure if this is visible from the task manager, but it is visible from the processes in the task manager section

**To Reproduce**  
1. Open Demo Software
2. Leave open for a long time
3. Click the tasks button and view all tasks in the task manager

**Expected behavior**  
For there to be no processes in this section

**Screenshots**  
![image](https://user-images.githubusercontent.com/53049056/161944336-1b02c991-479f-4054-8176-df198746e429.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - .NET: [e.g. net6.0-windows]
 - Version: 1.2.2

**Additional context**  
Im not sure if this occurs for all projects using WPF-UI, but this happens on the demo project for definite

**Comment by azenyx** [comment]
- Update, yes it shows up with WPF-UI developed applications

**Comment by pomianowski** [comment]
Hey @azenyx, are you sure the extra Tray icons show up after a period of time and not after Visual Studio exits the application repeatedly?

**Comment by chucker** [comment]
> From what I see, if you leave the demo software open for a long time, lots of processes will appear overtime.

This is typically the behavior when you run an app from VS's debugger. Stopping debug will clean the notification area in an unsafe way, so icons remain (until hovered over).

**Comment by blakepell** [comment]
This fix works perfect, I just updated and the notify icon correctly removes itself both when the app closes and from forced closes like from VS.

Also, just wanted to say thank you @pomianowski.  This library is awesome and the fluent style is implemented beautifully.
