### ISSUE TITLE
The light mode of the backend code of the bug

### ISSUE THREAD

**Issue by AmirMohammadPX** [lepoco/wpfui#1258]
### Describe the bug

The backend codes are problematic for light mode but work well for dark mode

            Loaded += (sender, args) =>
            {
                Wpf.Ui.Appearance.ApplicationThemeManager.Apply(
                 Wpf.Ui.Appearance.ApplicationTheme.Light, // Theme type
                 Wpf.Ui.Controls.WindowBackdropType.Mica,  // Background type
                 true                                      // Whether to change accents automatically
               );
            };            

### To Reproduce

-

### Expected behavior

-

### Screenshots

![image](https://github.com/user-attachments/assets/c9b7d882-139a-4d29-acf0-f26f20cc58fe)

### OS version

Windows 11

### .NET version

dotnet 8

### WPF-UI NuGet version

3.0.5

**Comment by Ledgerbiggg** [comment]
Because using WindowStyle="None" with native window forms may cause issues

I suggest you use
````xml
<ui:FluentWindow>
</ui:FluentWindow>
````
to replace
```xml
<Window>
</Window>
```

**Comment by AmirMohammadPX** [comment]
@Ledgerbiggg  Thank you
