### ISSUE TITLE
How do I create a three-level menu using "NavigationView"?

### ISSUE THREAD

**Issue by Justin1107-good** [lepoco/wpfui#1285]
### Describe the bug

How do I create a three-level menu using "NavigationView"?

### To Reproduce

 <ui:NavigationViewItem Content="Data"   Style="{StaticResource CustomNavigationViewItemStyle}">
                        <ui:NavigationViewItem.Icon>
                            <ui:SymbolIcon Symbol="DataHistogram24" />
                        </ui:NavigationViewItem.Icon>
                        <ui:NavigationViewItem.MenuItems>
                          
                        <ui:NavigationViewItem Content="CHA"   NavigationCacheMode="Enabled" Style="{StaticResource CustomNavigationViewItemStyle}">

                            <ui:NavigationViewItem.MenuItems>
                               
                                <ui:NavigationViewItem Content="PAGE1" Tag="SqlDatabaseTag" Style="{StaticResource CustomNavigationViewItemStyle}"/>
                                <ui:NavigationViewItem Content="PAGE1" Tag="NoSqlDatabaseTag" Style="{StaticResource CustomNavigationViewItemStyle}"/>
                                </ui:NavigationViewItem.MenuItems>
                            </ui:NavigationViewItem>

                         
                        </ui:NavigationViewItem.MenuItems>
                    </ui:NavigationViewItem>

### Expected behavior

hope show?
  <ui:NavigationViewItem Content="PAGE1" Tag="SqlDatabaseTag" Style="{StaticResource CustomNavigationViewItemStyle}"/>
                                <ui:NavigationViewItem Content="PAGE1" Tag="NoSqlDatabaseTag" Style="{StaticResource CustomNavigationViewItemStyle}"/>
                                </ui:NavigationViewItem.MenuItems>

### Screenshots

![image](https://github.com/user-attachments/assets/581bb0d4-7acb-4dcf-bce5-5495692b4b3a)

### OS version

win10

### .NET version

.NET framework 4.7.2

### WPF-UI NuGet version

3.0.5

**Comment by pomianowski** [comment]
Hey @Justin1107-good,thank you for trying the WPF UI. The 3+ level navigation is currently not supported.

**Comment by Justin1107-good** [comment]
thanks,The use of the WPF UI is not bad, and the demo reference is detailed.
