### ISSUE TITLE
Responsive CardAction style for Dark or Light theme.

### ISSUE THREAD

**Issue by arthuridea** [lepoco/wpfui#131]
**Is your feature request related to a problem? Please describe.**
I noticed that in windows 11 UI (e.g  Settings>System ), the cardAction only reduces its opacity on mouse-over in light theme,while plays an opposite animation effect in dark mode.
But wpfui plays the same animation in both light and dark theme. 
![image](https://user-images.githubusercontent.com/2337583/163524447-bd354d91-edc1-483a-af86-2fec053219ce.png)
![image](https://user-images.githubusercontent.com/2337583/163524569-663de449-6799-4df0-a52f-2a9f2c3625f5.png)

**Comment by MajorXAML** [comment]
In fact, there is no such control in winui yet, so we can't determine exactly what colors they use. Visually they look like an expander, but the expander (body) has no hover effect.
![expander](https://user-images.githubusercontent.com/93913816/163551415-5cfaa88f-95d2-4fc8-9688-78f3f142456f.png)
