### ISSUE TITLE
Mica on context menu

### ISSUE THREAD

**Issue by Symbai** [lepoco/wpfui#132]
**Is your feature request related to a problem? Please describe.**
Mica can only be applied to a window currently

**Describe the solution you'd like**
Add Mica also to context menu

**Describe alternatives you've considered**

**Additional context**
It's somehow possible. For example the Edge in Windows 11 has mica applied to all context menus. Also the context menus in Windows settings have Mica.

**Comment by MajorXAML** [comment]
duplicate https://github.com/lepoco/wpfui/issues/93
