### ISSUE TITLE
NavigationStore Items bad sizing

### ISSUE THREAD

**Issue by randomdotdll** [lepoco/wpfui#137]
**Describe the bug**  

**To Reproduce**  
1. Use the latest revision
2. Open the project
3. Launch WPF.Demo project
4. Go to Windows
5. Open Windows Store Navigation

**Expected behavior**  
Sizing must be higher.

**Screenshots**  
![image](https://user-images.githubusercontent.com/90194305/163680551-ab17ea0e-c448-465a-8b1a-7ff4c66f0aac.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - .NET: .NET 6.0
 - Version: Unknown

**Comment by pomianowski** [comment]
Haha, i see. It took me a while to get it. What you did was enter text for the icon, while `MenuItem` takes the value from a struct `SymbolRegular`.

```xaml
<Window
xmlns:wpfuicommon="clr-namespace:WPFUI.Common;assembly=WPFUI">
</Window>

```xaml
<MenuItem Header="Hello" Icon="{x:Static wpfuicommon:SymbolRegular.WindowAdOff20}"/>
```

**Comment by pomianowski** [comment]
In the 'development' branch this bug should already be corrected.

Scale 100%
![image](https://user-images.githubusercontent.com/13592821/163684841-3df5a9f4-d08d-4841-8d23-de5ada7d1d9e.png)

Scale 150%
<img width="598" alt="image" src="https://user-images.githubusercontent.com/13592821/163684887-3bde4984-7a77-42f1-8d4b-05b665f3980f.png">
