### ISSUE TITLE
Port to avalonia

### ISSUE THREAD

**Issue by sabuto** [lepoco/wpfui#14]
I really like the look of this theme but I use avalonia for most of my projects would you be happy for me to port this to avalonia? I would adhere to the rules of the license and credit you and this repo

**Comment by Pomianowski** [comment]
Hi @Sabuto, Thank you for your appreciation and interest in the project. If building a dll for [Avalonia ](https://github.com/AvaloniaUI/Avalonia)only requires Nuget packages, you can add a new project like WPFUI.Avalonia in the main repository. Just send PR

**Comment by Sabuto** [comment]
It would require a complete rewrite as avalonia styling system is different and they have different controls for example in wpf the togglebutton is the equivalent of toggleswitch in avalonia and their togglebutton is something different. Also creating custom controls is completely different too. I'm happy to create it and then maybe add a pr so the project can be included in this repo?

**Comment by Pomianowski** [comment]
All projects can be in one solution and published as a separate NuGet packages and DLL's for selected framework.

**Comment by Sabuto** [comment]
for anyone interested in helping out before i commit to this repo please feel free https://github.com/Sabuto/WpfUi.Avalonia/

**Comment by nlogozzo** [comment]
This already exists: https://github.com/amwx/FluentAvalonia

**Comment by sabuto** [comment]
> This already exists: https://github.com/amwx/FluentAvalonia

Yeah I figured that after I started doing it
