### ISSUE TITLE
Color problems with WindowsFormsHost

### ISSUE THREAD

**Issue by chucker** [lepoco/wpfui#141]
(This is more of a support request than a bug report.)

**Describe the bug**  
If a window is set to the `UiWindow` style, `WindowsFormsHost` controls inside have strange background color behavior. This is probably mostly on Microsoft's end, but I'm trying to figure out how to work around it, if possible at all.

**To Reproduce**  
Make an empty app with `App.xaml`:

```xml
<Application x:Class="WpfApp1.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:WpfApp1"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

`MainWindow.xaml`:

```xml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" xmlns:wpfui="clr-namespace:WPFUI.Controls;assembly=WPFUI"
        Style="{StaticResource UiWindow}">
    <Grid>
        <WindowsFormsHost x:Name="WinFormsHost" Margin="10" Visibility="Visible" />
    </Grid>
</Window>
```

`MainWindow.xaml.cs`:

```csharp
using System.Windows;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            WinFormsHost.Child = new System.Windows.Forms.Label
            {
                BackColor = System.Drawing.Color.Red,
                ForeColor = System.Drawing.Color.Black,
                Text = "Hello"
            };
        }
    }
}
```

**Expected behavior**  
There should be a light grey margin (from WPFUI), a large red rectangle (from the Label's `BackColor`), and the black text "Hello".

**Actual behavior**
The light grey margin appears, but the red rectangle is mostly white instead, and the text itself is a mix of black and red.

**Screenshots**  
Without `Style="{StaticResource UiWindow}"` (correct behavior):

![image](https://user-images.githubusercontent.com/20194/164194978-c1368a77-51c2-43eb-b09d-d36a9489d126.png)

With it:

![image](https://user-images.githubusercontent.com/20194/164194844-f1911676-7e04-4542-a27d-533b94a7aff5.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 21H1 19043.1645
 - .NET: occurs in both `net6.0-windows` and `net472`
 - Version: 1.2.3

**Additional context**  
Some cursory research suggests this may be related to "the airspace problem", which is the conflict between WPF's and Windows Forms's rendering. However, I've tried two libraries (AirspaceDecorator and AirspaceFixel) to work around this, with no success so far.

Any pointers would be appreciated.

**Comment by pomianowski** [comment]
![image](https://user-images.githubusercontent.com/13592821/164303471-f1a84fed-b2d2-4d5f-9269-d0d8e4d22a1a.png)

Hey @chucker, thanks for reporting a bug. For now, all I can say is that the bug is easily reproducible 😂 Honestly, I never used `WindowsFormsHost` and didn't think about supporting it. By default, **WPFUI** does not have `UseWindowsForms` enabled. I'll try to mess around with it, but it doesn't guarantee that support will be added if it requires WinForms to be enabled for the library.

**Comment by chucker** [comment]
No worries, and thanks for getting back to me.

Like I said, I did find a workaround; while it does significantly reduce the benefits of using WPFUI in the first place, it at least unblocks me, so this is no longer urgent or something that would make me give up on the library altogether.

I'm still hoping someone else has some experience with this issue, though.

>By default, WPFUI does not have UseWindowsForms enabled. I'll try to mess around with it, but doesn't guarantee that support will be added if it requires WinForms to be enabled for the library.

Right — I don't think you should enable that dependency by default.

**Comment by pomianowski** [comment]
Well, it went fast. Adding the immersive dark mode effect fixed the bug on at least Windows 11.

![image](https://user-images.githubusercontent.com/13592821/164306282-af1158e5-e050-412a-8074-2faa0ed230e9.png)

```c#
public partial class Container : Window
{
    internal class ExWindowsFormsHost : WindowsFormsHost
    {
        [DllImport("dwmapi.dll")]
        public static extern int DwmSetWindowAttribute(IntPtr hWnd, int dwAttribute, ref int pvAttribute, int cbAttribute);

        protected override HandleRef BuildWindowCore(HandleRef hwndParent)
        {
            var hRef = base.BuildWindowCore(hwndParent);

            var _hostedHwnd = (IntPtr)hwndParent;

            System.Diagnostics.Debug.WriteLine(_hostedHwnd);

            var pvAttribute = 0x01;

            DwmSetWindowAttribute(_hostedHwnd, 20, ref pvAttribute, Marshal.SizeOf(typeof(int)));

            return hRef;
        }
    }

    public Container()
    {
        InitializeComponent();

        WindowsFormsHostsContainer.Children.Add(new ExWindowsFormsHost
        {
            Child = new System.Windows.Forms.Label
            {
                BackColor = System.Drawing.Color.Red,
                ForeColor = System.Drawing.Color.Black,
                Text = "Hello"
            }
        });
    }
}
```

**Comment by chucker** [comment]
Hey, that does indeed help a lot!

**Comment by CejSmets** [comment]
For anyone running into a similar problem (We had this problem with ReportViewer where all text would turn white), the issue seems to be setting ExtendsContentIntoTitleBar to True in the containing UiWindow. @pomianowski might be fixable?

**Comment by chucker** [comment]
> the issue seems to be setting ExtendsContentIntoTitleBar to True in the containing UiWindow

I suspect you then lose a lot of abilities such as the Mica background.

**Comment by chucker** [comment]
I'm now running into the same issue on a different machine. I _think_ this is because that machine is reached via RDP. Trying an extension method for now until I've found a nicer approach…

```csharp
    public static class RdpSafety
    {
        public static void ApplyStyleIfCompatible(this Window window)
        {
            if (System.Windows.SystemParameters.IsRemoteSession)
                return;

            window.Style = (Style)window.FindResource("UiWindow");
        }
    }
```
