### ISSUE TITLE
SearchBar

### ISSUE THREAD

**Issue by AZProductions** [lepoco/wpfui#15]
**Is your feature request related to a problem? Please describe.**
I'm wondering if a search-bar is a good addition to the WPFUI suit of controls?

**Describe the solution you'd like**
It should behave just like the search-bar in the Microsoft Store or in the Xbox app.

**Describe alternatives you've considered**
I've thought on editing a list box using styles and more, but I haven't succeed yet.

**Additional context**
![image](https://user-images.githubusercontent.com/66299945/146680321-31615c71-3658-40a3-9db7-2fc3820e0a16.png)

**Comment by pomianowski** [comment]
Initial search box added in https://github.com/lepoco/wpfui/commit/d55847dd165163c8c6c305138cc7313ffc3b16e4
![image](https://user-images.githubusercontent.com/13592821/154100216-b78d4287-e4b0-45fa-8115-4858110eaa1c.png)
