### ISSUE TITLE
What is the radiograph sample? 

### ISSUE THREAD

**Issue by YBAZAN** [lepoco/wpfui#16]
**Describe the bug**  
It's not a bug report, just a question. In the screenshots, there is a radiograph sample. But I don't see any trace of it in the code. 

Is it a mistake or a sample to come? 

I take the opportunity to thank you about your work. There is work to do to refine some styles, but I do like the simplicity of the code compared to other repos with lot of stuff (too much in my opinion).

**Comment by Pomianowski** [comment]
Hey @YBAZAN. Radiograph is an implementation example. This app is actually the reason I made WPF UI. Before that, it was just a Radiograph module.

The app will be updated soon in the Store:
https://www.microsoft.com/en-us/p/radiograph/9nh1p86h06cg

Data reading is based on:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
