### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by realityisgay** [lepoco/wpfui#162]
Not sure where to send this. Please fix the website's documentation.

**Comment by chucker** [comment]
I think you'd need to be more specific.

(It does seem to work. There's a lot missing, of course, but it's a volunteer project.)

**Comment by Xinnony** [comment]
![image](https://user-images.githubusercontent.com/6058403/167042402-981814b5-a0a1-46e5-a078-015efad28281.png)
Not need more specific..

**Comment by pomianowski** [comment]
@Xinnony Clear site data, or use CTRL + SHIFT + R.  
The website is based on WorkBox and PWA, so sometimes the cache remains. Often it's enough to clear the cache and it should work.
![image](https://user-images.githubusercontent.com/13592821/167083145-09401d2d-82e7-42ba-9cba-1fcf808076f6.png)
