### ISSUE TITLE
Scroll control conflicts with VirtualizingWrapPanel

### ISSUE THREAD

**Issue by LasmGratel** [lepoco/wpfui#164]
**Describe the bug**  
While using https://github.com/sbaeumlisberger/VirtualizingWrapPanel together with WPFUI, all items in the ListView are loaded immediately.

Also WPFUI has taken control of ListView's scrolling behavior. `ScrollViewer.VerticalScrollBarVisibility="Disabled"` does nothing on ListView.

Copying WPFUI.xaml and have `<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Controls/Scroll.xaml" />` removed would have the problem fixed.

**To Reproduce**  
```xml
<ListView>
  <ListView.ItemContainerStyle>
      <Style TargetType="{x:Type ListViewItem}">
          <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
          <Setter Property="VerticalContentAlignment" Value="Stretch"/>
      </Style>
  </ListView.ItemContainerStyle>
  <ListView.ItemsPanel>
      <ItemsPanelTemplate>
          <wpftk:VirtualizingWrapPanel />
      </ItemsPanelTemplate>
  </ListView.ItemsPanel>
      <ListView.ItemTemplate>
          <DataTemplate>
              <StackPanel HorizontalAlignment="Stretch"
                          VerticalAlignment="Stretch">
                  <TextBlock Text="{Binding}"  Loaded="Element_OnLoaded" Unloaded="Element_OnUnloaded"></TextBlock>
              </StackPanel>
          </DataTemplate>
      </ListView.ItemTemplate>
  </ListView>
```

Add 1000 items to ListView, `Element_OnLoaded` are called 1000 times and not unloaded while scrolling.

**Expected behavior**  
Have VirtualizingWrapPanel

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0
 - Version: 1.2.6

**Additional context**

**Comment by pomianowski** [comment]
I confirm that the reason for bugs was a badly implemented `ScrollBar` and `ScrollViewer`. A great library by the way, I think it is worth implementing it's features in WPF UI.

![image](https://user-images.githubusercontent.com/13592821/167230363-48d30512-793b-4cba-b070-efd5baf5416a.png)

**Comment by LasmGratel** [comment]
Can we see more Windows Community Toolkit features implemented in WPFUI beside this? They are quite useful and create simple developing patterns.

**Comment by pomianowski** [comment]
Feel free to send PR with any functionality you like :)
