### ISSUE TITLE
MenuItem - Custom Icon

### ISSUE THREAD

**Issue by mortuusars** [lepoco/wpfui#168]
**MenuItem.Icon** is an object, and WPF default template for **MenuItem** displays Icon content through a **ContentPresenter**. That way we can set Icon to anything we want. 
But WPFUI template basically hardcodes the Icon to be a **TextBlock** with predefined **FontFamily** and **FontSize**, this limits the possibilities in exchange for ease of setting for limited number of icons.

Maybe I'm mistaken, but I haven't found a way to set a custom icon without redefining the template. Which is not ideal.

**Comment by pomianowski** [comment]
Hi @mortuusars , I think that's a fair point. My initial suggestion is to add an extended MenuItem. They both have an Icon parameter in `ContentPresenter`, but `wpfui:MenuItem` also has a `SymbolIcon` parameter.

Classic WPF `MenuItem`
```xaml
<MenuItem Header="With icon">
  <MenuItem.Icon>
    <wpfui:SymbolIcon Filled="True" Symbol="StoreMicrosoft24" />
  </MenuItem.Icon>
</MenuItem>
```

Extended WPF UI `MenuItem`
```xaml
<wpfui:MenuItem
  Header="Checkable custom"
  IsCheckable="True"
  SymbolIcon="AlignTop24" />
```

**Comment by mortuusars** [comment]
Yes, I think that's a nice solution. Thanks.
