### ISSUE TITLE
ComboBox foreground color won't change when set to "IsEditable"

### ISSUE THREAD

**Issue by sinantutan** [lepoco/wpfui#174]
**Description**  
When the property IsEditable is set to True in a ComboBox (for dark mode) the foreground color is set to Black, rather than the original primary text color for the theme.

**To Reproduce**  
1. Create ComboBox
2. Set property of IsEditable to True
3. Create ComboBoxItem
4. Pick item when app is running

**Expected behavior**  
Foreground color of ComboBox should follow theme colors.

**Screenshots**  
![Screenshot ComboBox](https://user-images.githubusercontent.com/73258913/167361357-f57ef1db-ea0b-4979-9c5c-ba9a389316bd.png)

**Desktop:**  
 - OS: Windows 10, Windows 11
 - .NET: 6
 - Version: n/a

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/pull/170
