### ISSUE TITLE
The ClearType of any text element is unexpectedly disabled so that it blurs.

### ISSUE THREAD

**Issue by walterlv** [lepoco/wpfui#177]
**Describe the bug**  
The ClearType of any text element is unexpectedly disabled so that it blurs. 

**To Reproduce**  
1. Run any application using the WPFUI

**Expected behavior**  
I think it should be set to default (keep it unset) and let the application developers set them by their decision.

**Screenshots**  
![image](https://user-images.githubusercontent.com/9959623/167525308-2af783d8-bb8b-4e3c-9319-092afef101a8.png)  
▲ The ClearType text above is created using the snoop

![image](https://user-images.githubusercontent.com/9959623/167525705-be116efa-d0da-4d9a-a276-1abd6f9b04c1.png)  
▲ 400% View

**Desktop (please complete the following information):**  
 - OS: Windows 11 22H2 (22616.1)
 - .NET: net6.0-windows
 - Version: 1.2.7

**Additional context**  
It has a comment to describe the reason why it is turned off here:

https://github.com/lepoco/wpfui/blob/bece9fb2815ca8fe4bb66fb70454d0f10d8f40b7/src/WPFUI/Styles/Controls/Window.xaml#L44-L45

The comment came from this commit: https://github.com/lepoco/wpfui/commit/71fe5c675f6fd4996a2a1e0c7992c23f1f6e8e79

**Comment by MajorXAML** [comment]
ClearType has a problem, it doesn't work on some elements if WindowChrome is used. https://github.com/lepoco/wpfui/issues/38 

In the end I just switched to GrayScale.

**Comment by walterlv** [comment]
@MajorXAML It seems that the WindowChrome is not the root cause. I'll try to reproduce the issue you mentioned, find out the reason, and fix it.

**Comment by chucker** [comment]
I don't think there's anything non-trivial you can do here.

ClearType is only implemented in the CPU. Subpixel text rendering like ClearType is dependent on the ultimate subpixels of the display. That's not hard if you can predict the backdrop, i.e. if you don't have any transparency effects. But as soon as your window *does* have transparency effects (like in Acrylic), anything underneath the text could affect how the ClearType text should be rendered, in a way that's hard to predict. For that to work, it needs to be at the end of the rendering pipeline: the final subpixels of each glyph need to be characters after everything else; after every other window of every other process has been drawn. But for performance reasons, effects like Acrylic should really be run in the GPU instead.

Thus, WPF has two options:

1. it can render the entire window _in software_, in the CPU, or
2. it can use (**G**PU) hardware acceleration, as it would prefer to, but disable ClearType. That's also why UWP no longer supports ClearType out of the box and apps like Settings do not use it.

The alternative would've been to implement ClearType (or subpixel text rendering in general) in the GPU, which most OS vendors have decided isn't worth the trouble.

And that is why, as soon as you set `AllowsTransparency="True"`, ClearType is disabled.

**Comment by walterlv** [comment]
@chucker Thank you for your description.

It seems that the UWP apps (e.g. Windows Settings) behave like what you have described. So this issue can be safely closed.

Maybe we need to find more solutions to solve the blurring of the texts.

![image](https://user-images.githubusercontent.com/9959623/170678179-47e842ac-a133-4fac-a017-439e6d94afa4.png)
