### ISSUE TITLE
Navigation parameter in NavigationStore.Navigate

### ISSUE THREAD

**Issue by amellini** [lepoco/wpfui#182]
Maybe I'm missing something but seem is not possible to pass arguments to NavigationStore.Navigate method
You can pass only a pageTag and a DataContext (but I cant figure how to use it) but no parameters (like Xamarin do)

Should be nice to add a parameter to Navigate method like "Query" (String) or "Parameters" (params[]) and add this to the OnNavigated(INavigation sender, RoutedNavigationEventArgs e) event

**Comment by pomianowski** [comment]
Since 2.0.0 you can use `IPageService` and enjoy the benefits of Dependency Injection and MVVM.
https://github.com/lepoco/wpfui/blob/b6e846262573336b265fdf033b682339beb43570/src/Wpf.Ui/Mvvm/Contracts/IPageService.cs#L17

Navigation also allows you to set the DataContext manually
```c#
Navigation.Navigate(Type pageType, object dataContext);
Navigation.Navigate(string pageTag, object dataContext);
Navigation.Navigate(int pageId, object dataContext);
```
