### ISSUE TITLE
[Bug Report] NumberBox can not handle negative numbers

### ISSUE THREAD

**Issue by miu-na** [lepoco/wpfui#187]
It seems like the number box can not handle negative numbers. Perhaps it will be better to allow the input of '-'.

**Comment by Dealman** [comment]
While I definitely agree, you can make a rather simple temporary workaround like this;

```cs
private void NumberBox_PreviewKeyUp(object sender, KeyEventArgs e)
{
    var numBox = ((NumberBox)sender);
    if (numBox is null)
        return;

    if (e.Key == Key.Subtract)
    {

        numBox.Value = -numBox.Value;
        numBox.Text = numBox.Value.ToString();
    }
}
```

Basically it just toggles the current value between negative/positive.
