### ISSUE TITLE
Version 1.2.7 on Nuget but version 1.2.6 here on github.

### ISSUE THREAD

**Issue by darcome** [lepoco/wpfui#188]
Just a small thing:

Version 1.2.7 on Nuget but version 1.2.6 here on github.

**Comment by chucker** [comment]
The code is 1.2.7: https://github.com/lepoco/wpfui/commit/3e86e314a3e3726855884670261c907418f63f2b

However, there's no changelog. You'd have to look at the commits starting at `aaa9c85` here: https://github.com/lepoco/wpfui/commits/3e86e31

**Comment by darcome** [comment]
Sorry, probably I didn't explain it well. 

What I mean is that at this page is still at 1.2.6.

https://github.com/lepoco/wpfui/releases

and therefore, I didn't receive any notification.
