### ISSUE TITLE
Allow different TitleBar foreground

### ISSUE THREAD

**Issue by chucker** [lepoco/wpfui#189]
**Is your feature request related to a problem? Please describe.**
I have a custom title bar with inverted colors:

```xml
<wpfui:TitleBar Grid.ColumnSpan="2" Grid.Row="0" Background="DodgerBlue" Foreground="LightCyan">
    <wpfui:TitleBar.Header>
        <StackPanel Margin="16,12" Orientation="Horizontal">
            <!-- NOTE: keep in sync with TitleBar.xaml -->
            <TextBlock>
                <TextBlock.Inlines>
                    <Run FontWeight="DemiBold">An inverted title</Run>
                    <LineBreak />
                    <Run FontWeight="Light">Some subtitle</Run>
                </TextBlock.Inlines>
            </TextBlock>
        </StackPanel>
    </wpfui:TitleBar.Header>
</wpfui:TitleBar>
```

However, while the `Foreground` property is inherited by `Header`, it _isn't_ by the buttons to the right:

![image](https://user-images.githubusercontent.com/20194/168308241-6529fb80-61a4-48c7-8215-896584566770.png)

**Describe the solution you'd like**
* if `Foreground` is set on `TitleBar`, it should apply to the buttons as well
* on top of that, perhaps the area of the buttons should be exposed somehow so it can be configured separately

**Additional context**
This is with 1.2.7.

**Comment by MajorXAML** [comment]
@pomianowski 
![sss](https://user-images.githubusercontent.com/93913816/168333448-bd9188e8-20d7-423b-aa51-a68af20b0f6a.jpg)
Close button MouseOver Foreground must be #FFFFFF 😉
