### ISSUE TITLE
Documentation & Tutorial missing

### ISSUE THREAD

**Issue by chociii** [lepoco/wpfui#196]
**Describe the bug**  
Neither documentation nor tutorial on https://wpfui.lepo.co/

I'm sorry for bringing this up via GitHub issue. 
Unfortunately the documentation & tutorial is missing since quite some time now.

**Comment by chucker** [comment]
They’re incomplete, but not missing for me. Try clearing your browser cache, maybe…

**Comment by chociii** [comment]
Interesting, so it only works on Chrome on my side. I can live with that.

**Comment by pomianowski** [comment]
`CTRL` + `SHIFT` + `R` or: **Clear site data**

![image](https://user-images.githubusercontent.com/13592821/169652694-a361b18d-4f2d-4861-8b28-1dcde6982893.png)
