### ISSUE TITLE
Be able to exit the rootnavigation

### ISSUE THREAD

**Issue by SamuelCHICHA** [lepoco/wpfui#199]
I am accessing a page outside of the set of pages handled by the rootnavigation. I want to be able to leave the rootnavigation to get back to it later. For instance if I am on the page and accessing the so called other page, I'm still considered as being on the homepage and therefore I cannot click on the home page button to get back at it.

I would like to be able to set a null value to the RootNavigation.Navigate() to exit the rootnavigation.

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/blob/6dbdf624d2d6b736c6fab2aefa2c10fdf7940368/src/WPFUI/Controls/Navigation/NavigationBase.cs#L311

**Comment by SamuelCHICHA** [comment]
Thank you sir ! I will look into it.

**Comment by MajorXAML** [comment]
@pomianowski may I ask what the difference between PageSource and PageType is? and what should be used?

**Comment by pomianowski** [comment]
@MajorXAML 

`PageSource` is the address of the view
```xaml
<wpfui:NavigationItem
  PageSource="pack://application:,,,/Views/Pages/Dashboard.xaml" />
```

`PageType` directly points to the class
```xaml
<wpfui:NavigationItem
  PageType="{x:Type pages:Dashboard}" />
```

**Comment by MajorXAML** [comment]
@pomianowski Thank you. Using PageSource I encountered an error in the designer... But, I can't replicate it in Demo. Very strange. I'll keep digging. 

![image_2022-05-29_145337364](https://user-images.githubusercontent.com/93913816/170866649-9ff12681-14a3-41fc-9ab5-5010caf13483.png)

**Comment by pomianowski** [comment]
Hey @MajorXAML, probably something breaks while solving an absolute uri
https://github.com/lepoco/wpfui/blob/66741cea058cc1e15317a4fb16c4f561f42dcc02/src/WPFUI/Controls/NavigationItem.cs#L333

**Comment by pomianowski** [comment]
Especially this
```c#
// TODO: Force extracting BaseUri for Designer
        if (baseUri == null)
            return pageUri;
```

**Comment by MajorXAML** [comment]
Probably the demo does not have this error, because it does not display current nav page in the designer. 

I just created a new project and here is literally all of its code. 🙄
![image_2022-05-29_153243103](https://user-images.githubusercontent.com/93913816/170868515-0df6e72b-eff7-40fc-99af-e3bef24d3fba.png)

The only solution I have found is to use  `SelectedPageIndex="-1"`
