### ISSUE TITLE
Smooth animations while navigating

### ISSUE THREAD

**Issue by PierreLeGit** [lepoco/wpfui#200]
This improvement would really be a must:
Changing pages without blocking navigation animations.
I have browsed the material design extension project here
https://github.com/spiegelp/MaterialDesignExtensions
The navigation is smooth. The graphic style is a mess compared to WPFUI. I tried to adapt it for this project but without success, I don't have the knowledge level for that.
Especially I try to keep the functionality where you see the navigation in the VS graphical editor and the store navigation control is really good.
Do you think it would be possible?

Translated with www.DeepL.com/Translator (free version)

**Comment by pomianowski** [comment]
I don't know if I understand your request well, but navigation animations have been added to `development` branch. They are not very smooth, but certainly make navigation more pleasant.

**Comment by PierreLeGit** [comment]
I Pomianowsky,  thanks for your reply!
The title you renamed to "Smooth animations while navigating" fits well the subject. The animations of the "storeNavigation" control are vert nice but freeze when opening a page that contains a number of controls. I saw in the attached project that the navigable pages are user controls and that they are loaded asynchronously on another thread. This makes the animations of the navigation banner remain fluid no matter what the content of the page is loading. This gives a nice fluid impression.
Currently I'm using this code and I'm adapting the xaml customization but it's not very nice yet. Moreover the pages are created in a list in code behind and you can't see anything in the graphic designer. I find this uncomfortable and I prefer your method.
I hope that's clearer.
