### ISSUE TITLE
Setting ResizeMode to NoResize still allows Resizing

### ISSUE THREAD

**Issue by M1XT3NZ** [lepoco/wpfui#202]
**Describe the bug**  
Setting ResizeMode to NoResize still allows resizing

**To Reproduce**  
1. Open the WPFUI Demo
2. Go to Container.xml and add ResizeMode="NoResize"
3. Start the Application and try to resize

**Expected behavior**  
That the application does not allow resizing

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/issues/109
```xaml
<Window Style="{DynamicResource UiWindowNoResize}" />
```

This is currently a limitation resulting from extensive `Window` alternations. If you want a custom effect, you have to create your own `Window` style.

**Comment by M1XT3NZ** [comment]
So basically either we have a window that we can resize or a window that we cant resize and not a window that we can programmatically allow resizing or not resizing. hmm
