### ISSUE TITLE
How to change ResizeMode

### ISSUE THREAD

**Issue by Reksely** [lepoco/wpfui#207]
I was looking through all documentations but I cant find method to change resize mode so I can make user not open my appin full screen

**Comment by Reksely** [comment]
I got it not change size by doing

 MaxWidth="1200"
    MaxHeight="654"
     MinWidth="1200"
    MinHeight="654"

but how can i make resize button show as disabled

**Comment by realcnk** [comment]
`<wpfui:TitleBar
            x:Name="RootTitleBar"
            ShowMaximize="False" />`

**Comment by Reksely** [comment]
Thanks❤️
