### ISSUE TITLE
Can I make only one grid be scrollable

### ISSUE THREAD

**Issue by Reksely** [lepoco/wpfui#208]
I want to make system like in microsoft store where left side is not moving while scrolling
![image](https://user-images.githubusercontent.com/69013710/171879509-cda69738-37d6-4344-bfec-b873f4f89ff8.png)
![image](https://user-images.githubusercontent.com/69013710/171879567-7f8b1907-fedc-4c47-b7ef-1c02d0680f32.png)

I know about Style="{StaticResource UiPageScrollable}" but its making everything be scrollable

**Comment by pomianowski** [comment]
I think you want to achieve something more like that
```xaml
<Page Style="{DynamicResource UiPage}">
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="Auto"/>
      <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>

    <Grid Grid.Column="0"/> <!-- Static column -->
    <wpfui:DynamicScrollViewer Grid.Column="1"/> <!-- Scrollable right content -->

  </Grid>
</Page>

**Comment by Reksely** [comment]
So only things in this grid would be scrollable and everything else wont?
