### ISSUE TITLE
How do I make items with microsoft store design? (example in description)

### ISSUE THREAD

**Issue by Reksely** [lepoco/wpfui#210]
![image](https://user-images.githubusercontent.com/69013710/171963100-6e024a3e-8903-40cf-852f-b49dc4789823.png)

I want to make same thing. I tried using expander because it looked like it but it has non needed expand button that i couldnt remove so I wanted to ask if there is smth like this in wpfui or is there a way to remove expand button in expander

**Comment by MajorXAML** [comment]
Just user border and grid...

**Comment by Reksely** [comment]
I mean text and this spacer

**Comment by kevfrench** [comment]
Hi, you can use the CardExpander control, just set ```IsExpanded="true" and hide the expander chevron with a local style:
```
<ui:CardExpander.Resources>
    <Style TargetType="ToggleButton">
        <Setter Property="Visibility" Value="Collapsed" />
    </Style>
</ui:CardExpander.Resources>
```
Although that's probably overkill, as suggested you can replicate this pretty easily with just a border and a stackpanel or grid:
```
        <Border Background="{DynamicResource ControlFillColorDefaultBrush}" CornerRadius="4">
            <StackPanel>
                <TextBlock Margin="12" FontSize="14" FontWeight="SemiBold" Text="Title" />
                <Separator />
                <TextBlock Margin="12" FontSize="13" TextWrapping="Wrap">
                    This app demonstrates all of the Xaml and Windows UI library controls available to make a Fluent Windows 10 app.
                </TextBlock>
            </StackPanel>
        </Border>
``
![expander-lite](https://user-images.githubusercontent.com/2056054/173506750-9326bd60-72de-434f-a55d-bdc246d619d6.png)
`
