### ISSUE TITLE
Can't tell the third state from unchecked on CheckBox

### ISSUE THREAD

**Issue by ekdahl** [lepoco/wpfui#213]
**Describe the bug**  
There is no difference between the third state and unchecked on checkboxes, for both themes.

**To Reproduce**  
1. Add CheckBox
2. Set IsThreeState="True"
3. Test the three states
4. Unchecked and third state looks the same

**Expected behavior**  
Visual indication of the third state.

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 1.2.7

**Comment by Inzaniity** [comment]
Would it be possible to expose the `ControlIcon` as a property so we could change it with StyleTriggers? This wouldn't be a clean solution but we could have all 3 states look different.

For example 
CheckMark48 when IsChecked = True 
Dismiss46 when IsChecked = False

This would leave us with at least some sort of distinction between all 3 states.

Apart from that, setting the `ControlIcon` would generally be a neat feature. (Tried to extract the template and modify it for my needs but I didn't manage to get it working)

**Comment by Inzaniity** [comment]
@ekdahl I managed to get it working in a fashion that is not ideal but gets the job done in the meantime. 

I created my own CheckBox with an OnToggle() override to change the order of the

**Comment by pomianowski** [comment]
Oh..., I didn't know IsChecked is `null` when in ThreeState. This solves problems with VisualState and themes.

![image](https://user-images.githubusercontent.com/13592821/182895556-f3f9f3d1-b4d6-4606-a4c1-4f408ad6ff87.png)

**Comment by niels9001** [comment]
This has been resolved in the latest previews
