### ISSUE TITLE
Getting a list of navigation Items

### ISSUE THREAD

**Issue by slava-aes** [lepoco/wpfui#221]
I have set a function for the event PreviewMouseDown for my NavigationStore. Now inside this function I want to get which of the navigation items was clicked, but it appears that I CAN'T. Appearantly I can only get the count and the list of all navigation itens via **WPFUI.Controls.NavigationStore.Items** and **WPFUI.Controls.NavigationStore.Items.Count** but NOT which of the items was clicked. I can't use the Click event for the navigationItem because I need to set all the others to inactive (I mean there can only be one item active at a time). 

How do I go about this? All I want is to set the current selected navigationItem to active.

**Comment by pomianowski** [comment]
`[get] _navigation.Current` will return `INavigationItem`.

You can also use Linq or enumarate items and check which one is currenlty active
```c#
var current = _navigation.Items.Where(item => item is INavigationItem && ((INavigationItem)item).IsActive).First()
```
