### ISSUE TITLE
'#29000000' is not a valid value for property 'BorderBrush'.

### ISSUE THREAD

**Issue by aiqinxuancai** [lepoco/wpfui#226]
I am trying to convert an application that previously used the metro interface library to a WPFUI, I removed a lot of styles that relied on metro and prioritized making the application work.
After confirming the removal of metro and making it work, I inserted the code " <ui:Resources Theme="Light" />" into the App.xaml to run it with the error "'#29000000' is not a valid value for property 'BorderBrush'." .

Then I checked the source code of WPFUI, deleted line 27 of ComboBox.xaml, and the program worked fine.

Then I reverted all the code and added " <ui:Resources Theme="Light" />" directly without removing the metro, and it still prompts this error.

The above problem occurs in this project:
https://github.com/aiqinxuancai/WkyFast

**Screenshots**  
![image](https://user-images.githubusercontent.com/4475018/174270828-b701945f-b7ca-4185-b917-bc1d63fc892e.png)

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10] 19043.1766
 - .NET: [e.g. net6.0-windows]
 - Version: [nuget last]

**Comment by pomianowski** [comment]
Hey @aiqinxuancai. The error is due to an invalid `Color` to `Brush` assignment for the `ComboBox` control. This bug will be corrected in version 2.1.0.

**Comment by gy-ge** [comment]
Release 2.0.1 has fixed this problem.
