### ISSUE TITLE
Error running after upgrading from 1.2.6 to 2.0.1

### ISSUE THREAD

**Issue by luluxiaoyu** [lepoco/wpfui#252]
**Describe the bug**  
Error running after upgrading from 1.2.6 to 2.0.1  

Error message:   
System.Windows.Markup.XamlParseException: ""An exception was thrown while setting property 'System.Windows.ResourceDictionary.Source'. ", the line number is "10", and the line position is "18"."  

FileNotFoundException: Could not load file or assembly 'WPFUI, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**To Reproduce**  
Upgraded from 1.2.6 to 2.0.1, changed the title attribute of the card control to the header attribute, and then compiled, the compilation went smoothly, but the operation went wrong

**Desktop (please complete the following information):**  
 - OS: Windows11
 - .NET: net6.0-windows10.0.18362.0
 - Version: 2.0.1

**Comment by chucker** [comment]
This is probably a Visual Studio problem. Try rebuilding, deleting `obj` folders, etc.

Failing that, post the XAML.

**Comment by MortalKim** [comment]
Got same error too. And tried clear program, delete obj and bin, clear nuget cache, all not work.

**Comment by MortalKim** [comment]
I delete code form app.xaml:
```
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Dark.xaml" />
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
```
replace with code `<ui:Resources Theme="Dark" />`
then I can run it. but theme got wrong, I need set theme in code, just first window:
```
            Wpf.Ui.Appearance.Background.Apply(
                this,
                Wpf.Ui.Appearance.BackgroundType.Mica);

            Wpf.Ui.Appearance.Accent.Apply(
                Wpf.Ui.Appearance.Accent.GetColorizationColor(),
                Wpf.Ui.Appearance.ThemeType.Dark);
```
IDE may have some error, but it work for now. And a little UI problem need fix manually

**Comment by chucker** [comment]
You need to change the URIs from:

```
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Dark.xaml" />
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
```

to:

```
<ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Theme/Dark.xaml" />
<ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Wpf.Ui.xaml" />
```

**Comment by MortalKim** [comment]
> You need to change the URIs from:
> 
> ```
> <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Dark.xaml" />
> <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
> ```
> 
> to:
> 
> ```
> <ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Theme/Dark.xaml" />
> <ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Wpf.Ui.xaml" />
> ```

Thanks for information. it works fine now.

**Comment by luluxiaoyu** [comment]
> You need to change the URIs from:
> 
> ```
> <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Dark.xaml" />
> <ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
> ```
> 
> to:
> 
> ```
> <ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Theme/Dark.xaml" />
> <ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Styles/Wpf.Ui.xaml" />
> ```
Thanks
