### ISSUE TITLE
MessageBox doesn't block the main process when opened

### ISSUE THREAD

**Issue by tomihbk** [lepoco/wpfui#255]
First of all, I'm grateful of your amazing work you've done! <3

**Describe the bug**  
When the `Wpf.Ui.Controls.MessageBox` window is opened, the process behind still continues unlike `System.Windows.MessageBox` where it would block the thread until we select options such as OK, CANCEL, ...

**To Reproduce**  
```c
MessageBox() messageBox = new MessageBox();

messageBox.Show("Something weird", "May happen");

System.Diagnostics.Debug.WriteLine("Just passed after the messagebox smh...");
``` 

**Expected behavior**  
The `Debug.WriteLine` message should not have printed the message. The thread should have been paused until I finish my interaction with the `MessageBox.Show()`

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows / .NET Framework 4.8.04084
 - VS : 2022 v17.1.0

**Comment by namhnz** [comment]
You should use the ShowDialog() method

**Comment by tomihbk** [comment]
> You should use the ShowDialog() method

Thanks for your input. `ShowDialog()` seems to be limited, though. I can set up the title and assign button actions. 

But how can I add the text description ? 

After that, when I call `ShowDialog()` for the second time, I get this error 
```c
System.InvalidOperationException: 'Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed.'
 ```

**Comment by pomianowski** [comment]
I don't know if the custom `MessageBox` in WPF Ui should be treated the same as the original MessageBox. This new one is more of a visual window that I don't think should be used often. Application interruption is neither interactive nor modern.

In my opinion, this functionality should not interrupt the rendering of the window.

**Comment by tomihbk** [comment]
While that might be true. In my case, I want it to be a warning, for example, deleting a file, merging a file,.. as the warning is important, it should block the UI until the user has responded.

**Comment by pomianowski** [comment]
So maybe it is worth considering `Dialog` inside the main app view with a custom Footer.

![image](https://user-images.githubusercontent.com/13592821/177007439-21dac2a6-d111-4187-93b6-003bf5cd346b.png)
