### ISSUE TITLE
Light Theme bugs

### ISSUE THREAD

**Issue by PierreLeGit** [lepoco/wpfui#259]
Hello Lepo,

All these novelties cannot be done at once and the work done is great. The light theme is not finished. Since the new version 2, the title bar and the navigation bar on the left remain black. In the title bar, the minimize, maximize and close buttons are not highlighted when the mouse is over them. We are starting to touch perfection and it would be perfect to achieve a bug-free shell. Other user controls can wait ;)

OS: Win 10 & 11
.Net 6

**Comment by PierreLeGit** [comment]
White/black them switch well in Windows 11 but not in Windows 10

**Comment by niels9001** [comment]
This has been resolved in the latest previews
