### ISSUE TITLE
Getting errors from following tutorial.

### ISSUE THREAD

**Issue by realrandombeans** [lepoco/wpfui#261]
**Describe the bug**  
I'm getting 3 errors after following the tutorial.
1:
![image](https://user-images.githubusercontent.com/97028115/176949438-5c71082d-d41e-4396-a727-6419641e6ab2.png)
2:
![image](https://user-images.githubusercontent.com/97028115/176949472-560a5177-d894-42eb-ac8a-565dc77a8375.png)
![image](https://user-images.githubusercontent.com/97028115/176949483-e1afefdd-af24-49db-aac2-f0927f0d4084.png)
3:
![image](https://user-images.githubusercontent.com/97028115/176949588-ee9f7da9-b9b4-41ec-9095-e2fd089e7eaa.png)
![image](https://user-images.githubusercontent.com/97028115/176949600-f0981d46-f23e-4e10-bdb5-aca0f43ddea1.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - .NET: Net 6.0 Long Term Release
 - Version: Latest stable release 2.01

**Comment by NotARobot6969** [comment]
Documentation is flawed; you need to use the ui:UiWindow class instead of Window.

**Comment by NotARobot6969** [comment]
(As a temporary fix to a bigger problem, you can use the WPFUI extension for VS)

**Comment by mastry** [comment]
I was able to get around these issues by making the following changes:

Change `Style="{StaticResource UiWindow}"` to `Style="{StaticResource DefaultChromeWindowStyle}"`
Create a `Pages` folder and add 2 WPF Pages to it named `Dashboard` and `Settings`.

You's also have to change the import namespace for WPFUI to `ui`:

` xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"`
