### ISSUE TITLE
[Navigation]Any example showing how to pass data to a page?

### ISSUE THREAD

**Issue by 1357310795** [lepoco/wpfui#267]
Neither the document nor the demo involves passing data...

If I use `public bool Navigate(Type pageType, object? dataContext)`, it's hard to pass `INavigationService navigationService` to the dataContext at the same time.

**Comment by pomianowski** [comment]
The `Demo` shows how to use the ViewModel based on Dependency Injection. In ViewModel you can get data from any service.

**Comment by 1357310795** [comment]
Thank! I have to create a service class to pass the data then. If there's something like MAUI's Shell style, that would be awesome.😁
