### ISSUE TITLE
Theme change module dose not work well on windows 10

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#268]
**Describe the bug**  
on windows 11, changing theme between dark and light is normally,but on windows 10, the title bar and navigator's theme remains dark after change the theme from dark to light.

**To Reproduce**  
change application's theme on windows 10.

**Screenshots**  
before change:![image](https://user-images.githubusercontent.com/38943319/177447787-1cadbf42-3876-4e34-be65-e23226a01414.png)

after change:
![image](https://user-images.githubusercontent.com/38943319/177447842-5ab0576c-668d-4597-9181-8e2593134911.png)

**Desktop (please complete the following information):**  
 - OS: [Windows 10]
 - .NET: [net6.0-windows10.0.17763.0]
 - Version: [2.0.1]

**Comment by 1357310795** [comment]
Note: If you delete the explicitly specified background in `Container.xaml`, everything works fine.

![QQ截图20220707122141](https://user-images.githubusercontent.com/35869804/177690669-e45f60eb-c495-45d3-92c8-104f685d28c1.png)

**Comment by pomianowski** [comment]
`ui:ThemeResource` should work after recent changes to **development** branch

**Comment by LHTXQ** [comment]
> Note: Demo app also don't work well on windows 10. But if you delete the explicitly specified background in `Container.xaml`（in Demo app）, everything works fine.
> 
> ![QQ截图20220707122141](https://user-images.githubusercontent.com/35869804/177690669-e45f60eb-c495-45d3-92c8-104f685d28c1.png)

谢谢，我还是等着下一版修复这个问题吧。
