### ISSUE TITLE
Split accent brushes

### ISSUE THREAD

**Issue by MajorXAML** [lepoco/wpfui#27]
If we want to use a [different ](https://github.com/lepoco/wpfui/commit/cc72e9c0d0ce9383b39d90015d5e1b234e2467bf)accent color in the two themes, we need to separate the brushes. 

https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Assets/Brushes.xaml#L18

SystemAccentColorLight2  & SystemAccentColorDark2 
etc..

I made some attempts and I did not like the result, the accent color is not like those used in windows 11 and it looks like some colors are mixed up. The right thing to do is to use an algorithm which will generate the necessary shades (SystemAccentColorLight and Dark 1-3) based on SystemAccentColor, but Microsoft has not yet shared the information on how they get these shades.

**Comment by MajorXAML** [comment]
I was told that we can try to use [modernwpf ](https://github.com/Difegue/Mica-WPF-Sample/issues/2#issuecomment-1004144510) method, but I can't figure out how to use it yet.

**Comment by Pomianowski** [comment]
Hey @MajorXAML, check the
https://github.com/lepoco/wpfui/blob/d6c9d31c1db0f51210e2b61a9c2c9abb9daa8a5c/WPFUI/Theme/Manager.cs#L372

**Comment by MajorXAML** [comment]
Unfortunately, the result is completely different ☹️
![accent_code](https://user-images.githubusercontent.com/93913816/148884807-87921540-9552-4789-8a52-8dbabe439645.PNG)

**Comment by BartoszCichecki** [comment]
Can you make `ChangeAccentColor` public?
