### ISSUE TITLE
Error displaying Chinese characters in controls（2.0.1-win11）

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#273]
In some controls, the Chinese characters display font is abnormal(inconsistent writing style and font thickness), such as the Chinese characters in the TextBlock in the followed screenshot.

![image](https://user-images.githubusercontent.com/38943319/178087825-b2901d35-a46f-4f4a-8d9f-7f3f710e8a8d.png)

**Comment by pomianowski** [comment]
It looks a bit like this font lacks letters for different font weights

**Comment by LHTXQ** [comment]
> It looks a bit like this font lacks letters for different font weights

No, the way those characters are written is not correct, it is not the simplified Chinese writing style.
Maybe you should use a better default font for controls.

**Comment by LHTXQ** [comment]
In addition, the screenshot shows that the application encountered an exception caused by inputing Chinese characters into NumberBox. The data binding is invalidated after the exception occurs. (I mentioned this problem in ([https://github.com/lepoco/wpfui/issues/269]))

**Comment by 1357310795** [comment]
wpfui默认字体是segoe ui，不是微软雅黑
![image](https://user-images.githubusercontent.com/35869804/178406621-165809e4-f45e-4ac9-99fc-08c172c1da67.png)

在app.xaml里覆盖成微软雅黑就行
```
<FontFamily x:Key="ContentControlThemeFontFamily">微软雅黑</FontFamily>
<FontFamily x:Key="DFontFamily">微软雅黑</FontFamily>
```

**Comment by LHTXQ** [comment]
> wpfui默认字体是segoe ui，不是微软雅黑 ![image](https://user-images.githubusercontent.com/35869804/178406621-165809e4-f45e-4ac9-99fc-08c172c1da67.png)
> 
> 在app.xaml里覆盖成微软雅黑就行
> 
> ```
> <FontFamily x:Key="ContentControlThemeFontFamily">微软雅黑</FontFamily>
> <FontFamily x:Key="DFontFamily">微软雅黑</FontFamily>
> ```

知道，所以建议把默认字体改成中文字形质量好一点字体。还是谢谢了，让我学到了怎么改默认字体。 ： ） 我是个业余选手，以后遇到问题可以向你请教一下吗（当然是在网上查找无果的前提下）？可以的话加你这个QQ？

**Comment by 1357310795** [comment]
So for globalization experience, it is better to leave the FontFamily of controls as default. @pomianowski

**Comment by 1357310795** [comment]
> 可以的话加你这个QQ？

可以吧，我也是业余玩玩的罢了（
