### ISSUE TITLE
Button in light mode has a faint color difference when hovering.

### ISSUE THREAD

**Issue by rounk-ctrl** [lepoco/wpfui#28]
**Describe the bug**  
Button in light mode has a faint color difference when hovering.

**To Reproduce**  
1. Create app with WPFUI
2. Add a button and load the light mode xaml
3. See bug.

**Expected behavior**  
Button to have more color difference when hovering.

**Screenshots**  
Normal state:
![image](https://user-images.githubusercontent.com/70931017/148778032-3cfdf46d-b1da-4e43-8f11-c0e304fa4395.png)
Hovering:
![image](https://user-images.githubusercontent.com/70931017/148778100-d99a75ba-d849-4973-bbf8-3f06163451c9.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - .NET: Framework 4.8
 - Version: 1.2.1

**Comment by MajorXAML** [comment]
To fix: 
https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Controls/Button.xaml#L57

change value to {DynamicResource ControlFillColorSecondaryBrush}

**Comment by rounk-ctrl** [comment]
nope that didnt work

**Comment by MajorXAML** [comment]
> ControlFillColorSecondaryBrush

ahh SolidColor, well then the longer version. I'm not sure why it's done that way.

```
<Trigger Property="IsMouseOver" Value="True">
<Setter TargetName="Border" Property="Background" >
<Setter.Value>
<SolidColorBrush Color="{DynamicResource ControlFillColorSecondary}" />
</Setter.Value>
</Setter>
</Trigger>
```

**Comment by rounk-ctrl** [comment]
still no

**Comment by MajorXAML** [comment]
Well, I checked, and it works for me. Depending on the background, the difference may not be very noticeable.

![btns](https://user-images.githubusercontent.com/93913816/148934437-fab596d0-5dc0-4edb-ac0a-3c1788b81196.PNG)
