### ISSUE TITLE
Cannot use snaplayout on windows11.  (.net6  V2.0.2)

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#291]
**Describe the bug**  
Cannot use snaplayout on windows11.

**To Reproduce**  

Creat an application using custom TitleBar.
```
        <ui:TitleBar Name="TitleBar" Grid.Row="0"
            Title=""
            FontSize="{Binding FontSize13, Mode=OneWay}"
            ForceShutdown="False"
            Icon="pack://application:,,,/Logo.png"
            MinimizeToTray="False"
            ShowHelp="False"
            ShowMaximize="True"
            ShowMinimize="True"
            UseSnapLayout="True">
......
......
```

**Expected behavior**  
Pops up snaplayout when move mouse over the maximize button.

**Comment by Xinnony** [comment]
You have two screens ?

**Comment by informagico** [comment]
I was looking at the same thing (I have two screens), even the Demo app has this issue.
`WIN + Z` combo keys is showing the snaplayout correctly, it's just the hover to be broken.

**Comment by danielkornev** [comment]
same issue :(
22H2 Windows 11 (RP)

**Comment by LHTXQ** [comment]
> 

Using only one screen has the same problem

**Comment by LHTXQ** [comment]
> You have two screens ?

Using only one screen has the same problem

**Comment by LHTXQ** [comment]
> I was looking at the same thing (I have two screens), even the Demo app has this issue. `WIN + Z` combo keys is showing the snaplayout correctly, it's just the hover to be broken.

The same.
