### ISSUE TITLE
notifyIcon won't update resource immediately after change resource dictionary

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#292]
**Describe the bug**  
notifyIcon won't update resource immediately after change resource dictionary.

**To Reproduce**  
1. add language resource into resource dictionary :
```
            <ResourceDictionary.MergedDictionaries>
                <ui:ControlsDictionary />
                <ui:ThemesDictionary Theme="Dark" />
                <ResourceDictionary Source="pack://application:,,,/XinQing.VirtualMechanicalLaboratory;component/Languages/English.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/XinQing.VirtualMechanicalLaboratory;component/Languages/Chinese.xaml"/>
            </ResourceDictionary.MergedDictionaries>
```
2. reference language resource in *.xaml: 
```
                <ui:NotifyIcon
                    x:Name="NotifyIcon"
                    FocusOnLeftClick="False"
                    Icon="pack://application:,,,/Logo.png"
                    MenuOnRightClick="True"
                    LeftClick="NotifyIcon_LeftClick"
                    TooltipText="{DynamicResource ProgramName}">
......
```
3. change resource dictionary when you want change language.
4. notifyIcon's menu will change language only after changed the theme but toolTip do not.

**Expected behavior**  
both tooltip and menu will change their language after changed resource without changing theme.

**Screenshots**  
![image](https://user-images.githubusercontent.com/38943319/180004430-afe17b92-7b3f-48e1-8ccd-dfdfbd40cce3.png)

**Comment by LHTXQ** [comment]
I wonder if it's difficult for you to understand my poor English?

**Comment by pomianowski** [comment]
I haven't seen any application, including system ones, to have a black tooltip.
![image](https://user-images.githubusercontent.com/13592821/180028758-8db9f6d7-dbf8-4129-9b7c-eebd450ec9e9.png)
![image](https://user-images.githubusercontent.com/13592821/180028610-13d3b730-093b-4c59-bec8-6e6804f75728.png)

Only the interactive elements of the task bar are black, but it's more of a custom popup.
![image](https://user-images.githubusercontent.com/13592821/180028906-22cb6877-1a52-4116-a3eb-f41ca958431a.png)

**Comment by pomianowski** [comment]
Duplicate #292
