### ISSUE TITLE
Outdated Templates

### ISSUE THREAD

**Issue by M1XT3NZ** [lepoco/wpfui#293]
Current [Templates](https://marketplace.visualstudio.com/items?itemName=lepo.WPF-UI&ssr=false#overview) arent up2date

**Comment by alec-hs** [comment]
Can confirm this - using any of the templates in the extension breaks the project in VS.

**Comment by pomianowski** [comment]
The extension has been updated with the latest changes.

![wpfui-template](https://user-images.githubusercontent.com/13592821/181916634-dd253c24-adcf-4aa5-b8dc-c0fd67fabe66.png)
![image](https://user-images.githubusercontent.com/13592821/181916698-a51c5eb2-fc44-4d60-bd49-3b69f01a199f.png)
