### ISSUE TITLE
ui:Resources doesn't exist in namepsace "http://schemas.lepo.co/wpfui/2022/xaml"

### ISSUE THREAD

**Issue by Reyshyram** [lepoco/wpfui#295]
It says that ui:Resources doesn't exist in namepsace "http://schemas.lepo.co/wpfui/2022/xaml", and that ui:Resources cannot be found.

1) Create new Wpf Project
2) Add Wpf-ui v2.0.2 via nuget package manager
3) Add "xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"" in app.xaml and `<ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:Resources Theme="Dark" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>` as shown in the tutorial
4) Impossible to launch and multiple errors

I don't know why it does that, it's the first time that I use wpf-ui and it doesn't seem to function.

![image](https://user-images.githubusercontent.com/102749075/180249155-d44212bd-75d7-4311-8fcf-7b47e4eeadef.png)

 
 - OS: Windows 11 21h2
 - .NET: 6.0.7
 - Version: 2.0.2

**Comment by Tinekk** [comment]
As a workaround you can use 
```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemesDictionary Theme="Dark" />
                <ui:ControlsDictionary />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
```

**Comment by Reyshyram** [comment]
Thanks You ! It functions !
