### ISSUE TITLE
<ui:TitleBar.Tray> cannot pop up ToolTips when content was bound to DataContext (V2.0.2)

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#298]
**Describe the bug**  
<ui:TitleBar.Tray> cannot pop up ToolTips when ToolTip content was bound to DataContext. While it was bound to DaynamicResource, it works well.

**To Reproduce**  
1. Create a <ui:TitleBar.Tray> contains: 
```
<ui:NotifyIcon
   ...........
   TooltipText="{Binding TitleText}">
```

2. start app.

3. Move the mouse over notification Icon.

4. There should be a tooltips if it works well.

**Expected behavior**  
Pops up ToolTips when content was bound to DataContext as the same as it dose when <ui:TitleBar.Tray> contains: 
```
<ui:NotifyIcon
   ...........
   TooltipText="{DynamicResource ResourceName}">
```

**Comment by pomianowski** [comment]
Duplicate #287
