### ISSUE TITLE
Dialog IsShow property no longer working

### ISSUE THREAD

**Issue by jasmeet21** [lepoco/wpfui#300]
**Describe the bug**  
After updating to v2.0.2 the property IsShown throwing error and can no longer be used. 
Revert back to v2.0.1 and it is working fine.

**Screenshots**  
![image](https://user-images.githubusercontent.com/9377470/180646246-7fc7625a-e03a-4699-8504-5ca97afaea06.png)
![image](https://user-images.githubusercontent.com/9377470/180646286-d572ea40-a0de-478d-82bb-ff6182e03ac1.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 2.0.2

**Comment by informagico** [comment]
I am fairly new to this package but as far as I know in the v2.0.2 they implemented the `IDialogService` to interact with dialogs.
The service is injected in the view and you need to use that to get/set dialog properties.
For example look at this page: [Wpf.Ui.Demo/Views/Pages/Controls.xaml.cs](https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui.Demo/Views/Pages/Controls.xaml.cs)

```csharp
public Controls(ISnackbarService snackbarService, IDialogService dialogService)
{
    InitializeComponent();

    _snackbarService = snackbarService;
    _dialogControl = dialogService.GetDialogControl();
}
```

You can see the IDialogService is injected and the dialog instance is retrieved by `GetDialogControl()`, from there you can access what you are looking for with the `_dialogControl.IsShown` **readonly** property.

```csharp
var _isShown = _dialogControl.IsShown;
```

NB: I totally understand this is a breaking change and **not** a minor update (maybe a v.2.1.0 would have been a better solution 😄 )

**Comment by jasmeet21** [comment]
I'm thinking instead of making massive change to the code, can I just replace IsShown with Visibility instead. 

Any difference in general between using this two ?
