### ISSUE TITLE
Moving the mouse over the taskbar does not pop up the window title at the first start.

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#304]
**Describe the bug**  
When the program first starts, moving the mouse over the taskbar does not show the window title.

**To Reproduce**  

A. 
```
        <
...............................
        WindowCornerPreference="Round"
        Icon="pack://application:,,,/Logo.png"
        Title="{Binding TitleText}" >
```

B.
```
        public string TitleText
        {
            get => _titleText;
            private set
            {
                _titleText = value;
                OnPropertyChanged(nameof(TitleText));
            }
        }
```

**Expected behavior**  
When the program first starts, the title of the window is displayed when the mouse moves over the taskbar.

**Screenshots**  
When the program first starts, the other controls display TitleText correctly：
![image](https://user-images.githubusercontent.com/38943319/181032785-d000e37e-8882-4c2e-bd27-c6318b3585cc.png)

Only after starting the software and updating TitleText once will the content pop up when the mouse moves over the taskbar：
![image](https://user-images.githubusercontent.com/38943319/181032206-99798b31-5670-4c86-864d-7779fd9ad61e.png)

**Desktop (please complete the following information):**  
 - .NET: [net6.0-windows11]
 - Version: [ 2.0.2]

**Comment by informagico** [comment]
I assume that the `TitleText` property is in the ViewModel so your problem is the DataContext, ViewModel is injected (see App.xaml.cs), try putting this in the constructor*:

```cs
DataContext = viewModel;
```

*untested

**Comment by pomianowski** [comment]
The `Title` property of the `TitleBar` is not connected to the `Title` property of `Window`.
https://github.com/lepoco/wpfui/blob/6e8739676867ecce82a7913ed35c2bb63a59672f/src/Wpf.Ui/Controls/TitleBar.cs#L181

**Comment by informagico** [comment]
I think it is talking about the Title on the **TaskBar**

This is the default `Container.xaml` (from demo app):

```xml
<ui:UiWindow
    ...
    Title="WPF UI"
    ...
/>
```

![image](https://user-images.githubusercontent.com/38808827/181083152-a96c1558-4381-4243-9d5d-72a10850a4b1.png)

This is the same view with the Title property bound to a property in the ViewModel

```xml
<ui:UiWindow
    ...
    Title="{Binding TitleText}"
    ...
/>
```

```csharp
private string _titleText = "THIS IS THE TASKBAR!";
public string TitleText
        {
            get => _titleText;
            private set
            {
                _titleText = value;
                OnPropertyChanged(nameof(TitleText));
            }
        }
```

![image](https://user-images.githubusercontent.com/38808827/181083493-58dee6b9-3c83-49bd-8baf-ea1208bf2f13.png)

and this with the ViewModel assigned to the DataContext

```csharp
// Container.xaml.cs -> Container()
DataContext = viewModel;
```

![image](https://user-images.githubusercontent.com/38808827/181082467-5ec7fca3-f7d5-4c9a-a260-310aa523e78e.png)

am I getting this whole thing wrong? 😄

**Comment by LHTXQ** [comment]
> The `Title` property of the `TitleBar` is not connected to the `Title` property of `Window`.
> 
> https://github.com/lepoco/wpfui/blob/6e8739676867ecce82a7913ed35c2bb63a59672f/src/Wpf.Ui/Controls/TitleBar.cs#L181

What I said is about <Title> in <ui:Window> and I left <Title> in <ui:TitleBar>  to be always empty, so there is nothing about <Title> in <ui:TitleBar>  .

In the issue screenshots, both "TitleLabel" I added and <Title> in <ui:Window> were bound to "TitleText" in DataBinding, Only "TitleLabel" display the content right after starts( as the first screenshot ), but <Title> of <ui:Window> seems to be empty. After changed the property of "TitleText" in DataBinding, both of they work well( as the second screenshot).

**Comment by LHTXQ** [comment]
Maybe later I will put a Minimal Reproduce Demo into this issue.

**Comment by LHTXQ** [comment]
> 



> I think it is talking about the Title on the **TaskBar**
> 
> This is the default `Container.xaml` (from demo app):
> 
> ```
> <ui:UiWindow
>     ...
>     Title="WPF UI"
>     ...
> />
> ```
> 
> ![image](https://user-images.githubusercontent.com/38808827/181083152-a96c1558-4381-4243-9d5d-72a10850a4b1.png)
> 
> This is the same view with the Title property bound to a property in the ViewModel
> 
> ```
> <ui:UiWindow
>     ...
>     Title="{Binding TitleText}"
>     ...
> />
> ```
> 
> ```cs
> private string _titleText = "THIS IS THE TASKBAR!";
> public string TitleText
>         {
>             get => _titleText;
>             private set
>             {
>                 _titleText = value;
>                 OnPropertyChanged(nameof(TitleText));
>             }
>         }
> ```
> 
> ![image](https://user-images.githubusercontent.com/38808827/181083493-58dee6b9-3c83-49bd-8baf-ea1208bf2f13.png)
> 
> and this with the ViewModel assigned to the DataContext
> 
> ```cs
> // Container.xaml.cs -> Container()
> DataContext = viewModel;
> ```
> 
> ![image](https://user-images.githubusercontent.com/38808827/181082467-5ec7fca3-f7d5-4c9a-a260-310aa523e78e.png)
> 
> am I getting this whole thing wrong? 😄

I have assigned the ViewModel  to the DataContext.

**Comment by 1357310795** [comment]
I had a discussion with @LHTXQ and came to the funny conclusion.

First, @LHTXQ 's problem is the `ToolTip` on taskbar rather than the title.
Second, the `ToolTip` is not controlled by user or by this UI Library but by system. Only when the `Title` of the window is too long, it has a chance to appear.

**Comment by LHTXQ** [comment]
🤣 How stupid of me!
It will only pop up a caption prompt if the title is too long to display.

![image](https://user-images.githubusercontent.com/38943319/181233251-535c6395-096d-4c23-addd-20044f228dd9.png)
