### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DuckyOnQuackTwitch** [lepoco/wpfui#305]
This is not a issue but what is this design thing called for the panel on the left? If you can let me know that would be great! Thank you 
![EA2CD8E7-228C-43F2-8E97-20CCD8A6943D](https://user-images.githubusercontent.com/81114664/181125782-7f8517a8-15ba-4f31-923c-4c38fc4cffef.jpeg)

**Comment by informagico** [comment]
Navigation Bar / Navbar / Navigation Menu

but Fluent UI design calls it [**NavigationView**](https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview)
