### ISSUE TITLE
Update Tutorial

### ISSUE THREAD

**Issue by MokiyCodes** [lepoco/wpfui#307]
**Describe the bug**  
Currently, [the tutorial](https://wpfui.lepo.co/documentation/tutorial) is still on version 1.x.x - It should be updated to 2.x.x

**To Reproduce**  
Does not apply to this type of issue

**Expected behavior**  
Does not apply to this type of issue

**Screenshots**  
![image](https://user-images.githubusercontent.com/92001109/181233657-f4f3bc1b-ee9d-434b-9be9-65c5d3052d5c.png)

**Desktop (please complete the following information):**  
Does not apply to this type of issue

**Additional context**

**Comment by mslowin** [comment]
Yup, I tried using WPF-UI for the first time today and I just couldn't get it to work. The tutorial really needs an update 😄

**Comment by pomianowski** [comment]
![wpfui-template](https://user-images.githubusercontent.com/13592821/181920257-1e7bca97-e20c-4324-bf55-d3433a6684a8.png)
