### ISSUE TITLE
Rename ToggleButton to ToggleSwitch

### ISSUE THREAD

**Issue by MajorXAML** [lepoco/wpfui#31]
I suggest renaming the ToggleButton to ToggleSwitch since WinUI has both controls.
![toggle](https://user-images.githubusercontent.com/93913816/148960361-f1c5ff1c-2647-42e5-94d6-12edb143a043.PNG)

**Comment by BartoszCichecki** [comment]
Btw, there is something wrong with this new ToggleSwitch in prerelease 133. Colors are not right in off state, but also it disables (?) other controls:

IsChecked = false
![image](https://user-images.githubusercontent.com/7916915/151253199-c2baf95c-e982-4696-99e9-45ccb63dc387.png)


IsChecked = true:
![image](https://user-images.githubusercontent.com/7916915/151253130-143d162c-d0dd-47b7-b21d-0587b2e666bc.png)

**Comment by BartoszCichecki** [comment]
@pomianowski FYI

**Comment by pomianowski** [comment]
Hey @BartoszCichecki, what a funky bug. Looks like the accent binding and then modifying it's opacity on one control affects the others
