### ISSUE TITLE
Adding dictionaries, ui:Resources doesn't exist anymore?

### ISSUE THREAD

**Issue by drummendejef** [lepoco/wpfui#310]
**Describe the bug**  
The explanation on how the "Adding dictionaries" part doesn't seem to be correct. It shows  <**ui:Resources** Theme="Dark" /> but the **Resources** part seems wrong/unexisting.

**To Reproduce**  
1. Open app.xaml in a project
2. Add the piece of code:
`<Application
  xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ui:Resources Theme="Dark" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>`
3. Notice how there is a squiggly line under the Resources of _ui.Resources_.

**Expected behavior**  
The keyword _Resources_ to be changed so it doesn't show an error. Change it into _ThemesDictionary_?

**Screenshots**  
Shows error:
![Shows error](https://user-images.githubusercontent.com/6048347/181717073-30127fd7-4042-49a5-97af-5bccf9faa581.png)
Doesn't show error:
![Doesn't show error](https://user-images.githubusercontent.com/6048347/181717114-e4ccc7d7-7d81-41ca-985f-1d877e44ad2a.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 2.0.2 (WPF-UI)

**Comment by pomianowski** [comment]
After recent update, there is `ui:ThemesDictionary ` and `ui:ControlsDictionary`.

```xaml
<Application
  ...
  xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ui:ThemesDictionary Theme="Dark" />
        <ui:ControlsDictionary />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

**Comment by bloodylucifer** [comment]
https://prnt.sc/1rUzSQ_RN0N4
https://prnt.sc/m2P2tRmVJjBy

**Comment by bloodylucifer** [comment]
OS: Windows 11
.NET: net6.0-windows
Version: 2.0.3

**Comment by TenebrosFR** [comment]
I'm in the same case as @bloodylucifer , Windows 11 .net7 and WPF UI 3.0
