### ISSUE TITLE
Error after installing version 2.0.2

### ISSUE THREAD

**Issue by LazyYangi** [lepoco/wpfui#312]
After installation, according to the documentation, the following problems occur
![image](https://user-images.githubusercontent.com/30524761/181808121-89df0548-2abf-432f-8a67-b8f91775b53d.png)
![image](https://user-images.githubusercontent.com/30524761/181808231-67568351-3435-48fd-9590-b5acbdb04aed.png)

**Comment by LazyYangi** [comment]
OS: Windows 11
.NET: net6.0-windows
Version: 2.0.2 (WPF-UI)

**Comment by LazyYangi** [comment]
Do you have the latest documents 2.0

**Comment by LazyYangi** [comment]
![image](https://user-images.githubusercontent.com/30524761/181866899-e3a19dcb-50e6-436e-b6e1-a504a00643ec.png)

**Comment by LazyYangi** [comment]
![image](https://user-images.githubusercontent.com/30524761/181870294-8aaea182-b412-439f-85cf-e5671026aa61.png)

**Comment by lambor590** [comment]
Well, when applying the main window, I removed all the content of the MainWindow.xaml and literally pasted the example of the tutorial, so the file was exactly like this:

`<ui:UiWindow x:Class="OCM_Installer_V2.MainWindow"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  xmlns:local="clr-namespace:OCM_Installer_V2"
  mc:Ignorable="d"
  Title="Otako Craft Launcher" Height="450" Width="800" ResizeMode="CanMinimize" SizeToContent="WidthAndHeight" WindowStartupLocation="CenterScreen"
  xmlns:pages="clr-namespace:MyNewApp.Pages"
  xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"
  Background="{ui:ThemeResource ApplicationBackgroundBrush}"
  ExtendsContentIntoTitleBar="True"
  WindowBackdropType="Mica"
  WindowCornerPreference="Round"
  WindowStartupLocation="CenterScreen">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <Grid
        x:Name="RootMainGrid"
        Grid.Row="1"
        Margin="0">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>

        
        <ui:NavigationStore
            x:Name="RootNavigation"
            Grid.Column="0"
            Margin="6,0,6,0"
            Frame="{Binding ElementName=RootFrame, Mode=OneWay}"
            Navigated="RootNavigation_OnNavigated"
            SelectedPageIndex="0">
            <ui:NavigationStore.Items>
                <ui:NavigationItem
                    Content="Home"
                    Icon="Home24"
                    PageType="{x:Type pages:Dashboard}"
                    PageTag="dashboard" />
            </ui:NavigationStore.Items>
            <ui:NavigationStore.Footer>
              <ui:NavigationItem
                    Content="Settings"
                    Icon="Diversity24"
                    PageType="{x:Type pages:Settings}" />
                
                <ui:NavigationItem
                    Click="NavigationButtonTheme_OnClick"
                    Content="Theme"
                    Icon="DarkTheme24" />
            </ui:NavigationStore.Footer>
        </ui:NavigationStore>

        
        <Border
            Grid.Column="1"
            Background="{ui:ThemeResource ControlFillColorDefaultBrush}"
            CornerRadius="8,0,0,0">
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                <Frame x:Name="RootFrame" Grid.Row="1" />
                <ui:Breadcrumb
                    Grid.Row="0"
                    Margin="18"
                    HorizontalAlignment="Left"
                    VerticalAlignment="Top"
                    FontSize="24"
                    Navigation="{Binding ElementName=RootNavigation, Mode=OneWay}" />
            </Grid>
        </Border>
    </Grid>

    
    
    
    <ui:TitleBar
      Title="WPF UI - Fluent design system"
      Grid.Row="0">
      <ui:TitleBar.Tray>
        <ui:NotifyIcon
          FocusOnLeftClick="True"
          MenuOnRightClick="True"
          TooltipText="WPF UI">
          <ui:NotifyIcon.Menu>
             <ContextMenu>
               <ui:MenuItem
                 Header="Home"
                 SymbolIcon="Library28"
                 Tag="home" />
            </ContextMenu>
          </ui:NotifyIcon.Menu>
        </ui:NotifyIcon>
      </ui:TitleBar.Tray>
    </ui:TitleBar>
  </Grid>
</Window>`

**Comment by Tinekk** [comment]
@lambor590, please read the errors
1. You are opening `<ui:UiWindow>` and closing `</Window>` (yeah documentation issue)
2. You are setting WindowStartupLocation twice

**Comment by lambor590** [comment]
@Tinekk, that is true.
I managed to get it working, adding Wpf.Ui.dll as reference of the project and fixing the example :)
