### ISSUE TITLE
QUESTION: Radiograph

### ISSUE THREAD

**Issue by BobbyESP** [lepoco/wpfui#32]
Is this a real app (Radiograph, the one in README)? I liked to get it.

https://raw.githubusercontent.com/lepoco/wpfui/main/.github/assets/screen-6.png

**Comment by alkalinin** [comment]
Yes, this is a real app
https://www.microsoft.com/en-us/p/radiograph/9nh1p86h06cg?activetab=pivot:overviewtab

**Comment by BobbyESP** [comment]
Nice, thanks!
