### ISSUE TITLE
Errors building WPF UI VS Extension template 

### ISSUE THREAD

**Issue by 7odaifa-ab** [lepoco/wpfui#332]
**Describe the bug**  
creating a project from the existing template doesn't get built and shows the following errors 

**To Reproduce**  
1. Go to 'Create a new project'
2. Click on 'any of the 3 MVVM template
3. build
4. See error:

![image](https://user-images.githubusercontent.com/86853497/183247227-46023084-c256-475e-a2fa-24ef583d8ad3.png)

**Expected behavior**  
it should build with no modification according to the documentation 

**Screenshots**  
![image](https://user-images.githubusercontent.com/86853497/183247264-1306e16a-7b22-48ba-9a8c-64aab227d152.png)

![image](https://user-images.githubusercontent.com/86853497/183247287-cb83510f-d5c4-4e56-b600-b61356400b0b.png)

![image](https://user-images.githubusercontent.com/86853497/183247566-5156d513-82cf-4187-9ba2-ade678a713a4.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: [6]

**Comment by pomianowski** [comment]
Generators don't work in some versions of Visual Studio and WPF
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608=

With workaround:
* To enable build in Windows Desktop 6.0.7, navigate to the directory containing the `Microsoft.WinFx.targets` file ( `C:\Program Files\dotnet\sdk\6.0.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets` )
* Add the following target in the file:
```xaml
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
        <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
        <Analyzer Remove="@(Analyzer)" />
        <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```
