### ISSUE TITLE
I think the accent color of some disabled controls is inappropriate.

### ISSUE THREAD

**Issue by ghost** [lepoco/wpfui#339]
ToggleSwitch or Radiobutton with "IsCheckd = true" changes color properly when "IsEnable" is changed.
However, in the same situation, CheckBox only changes the color of the text, and the color of the box does not change.
I checked that it works normally in the demo, is it going to be fixed in the next update?
Will the "IsThreeState" issue also be fixed in the next update?

ToggleButton with "IsEnable = flase" does not change color in light mode and changes color slightly in dark mode compared to WinUI3 when "IsChecked" is changed.
I think the distinction should be greater like WinUI3.

And I have a few suggestions that I want "TimePicker" from WinUI3, "DataGrid" looks like WinUI3, and I want to add a control to "TitleBar".
I'd like you to check if it's possible.

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: .NET 6
 - Version: 2.0.2

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/issues/213 related

**Comment by chucker** [comment]
> I want "TimePicker" from WinUI3 

I believe this is coming in 3.0.

>I want to add a control to "TitleBar".

You can set the `Header` property instead of `Title` to do that. For example, instead of:

```xml
        <wpfui:TitleBar Title="Hello world" />
```

You can do:

```xml
            <wpfui:TitleBar>
                <wpfui:TitleBar.Header>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock>
                            <TextBlock.Inlines>
                                <Run FontWeight="DemiBold">Hello</Run>
                                <Run> world</Run>
                            </TextBlock.Inlines>
                        </TextBlock>
                    </StackPanel>
                </wpfui:TitleBar.Header>
```

**Comment by niels9001** [comment]
This has been resolved in the latest previews
