### ISSUE TITLE
ToolTip looks weird

### ISSUE THREAD

**Issue by ghost** [lepoco/wpfui#340]
**Describe the bug**  
The edge of the ToolTip is strange as shown below.
You can't see it well in dark mode, but you can see it well in light mode.

**Screenshots**  
![image](https://user-images.githubusercontent.com/80233243/183670471-57c8690c-872f-41d2-8157-208d94b96dd1.png)
![image](https://user-images.githubusercontent.com/80233243/183670509-f63c6cb4-4870-4a79-8087-0bd13c6372e6.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: .NET6
 - Version: 2.0.2

**Comment by niels9001** [comment]
This has been resolved in the latest previews
