### ISSUE TITLE
Cannot generate wpfui mvvm applications, not even for new projects

### ISSUE THREAD

**Issue by Miaoywww** [lepoco/wpfui#346]
I created a new wpf mvvm project using the wpfui plugin , and when I try to start it, it reports errors, even when creating another project

here is my screenshot, and i'm make sure that this is a new project
![image](https://user-images.githubusercontent.com/52089819/184350912-f46835fb-20fe-4471-9953-8cc274d389d9.png)

i was able to generate it a few days ago

 - OS: [Windows 11]
 - .NET: [net6.0]
 - Version: [2.0.2]

**Comment by Miaoywww** [comment]
All templates are not available

**Comment by pomianowski** [comment]
Generators don't work in some versions of Visual Studio and WPF
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608=

With workaround:
* To enable build in Windows Desktop 6.0.7, navigate to the directory containing the `Microsoft.WinFx.targets` file ( `C:\Program Files\dotnet\sdk\6.0.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets` )
* Add the following target in the file:
```xaml
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
        <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
        <Analyzer Remove="@(Analyzer)" />
        <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```

**Comment by Miaoywww** [comment]
thanks :3
