### ISSUE TITLE
Slider style

### ISSUE THREAD

**Issue by viniciusjarina** [lepoco/wpfui#349]
First of all. Great job! This project is fantastic. Is nice to be able to use WPF and make things look modern.

I noticed the Slider is slightly different from the WinUI Slider theme
![Screenshot 2022-08-17 001802](https://user-images.githubusercontent.com/926868/185059085-3c4716b7-e642-49fb-9d85-80492025fc5f.png)

There is another project similar to this one called [ModernWPF ](https://github.com/Kinnara/ModernWpf) I am not sure how active it is, but maybe each project can help each other.

I guess ModernWPF import styles from https://github.com/microsoft/microsoft-ui-xaml and convert them to WPF. Maybe wpfui could do something similar

**Comment by niels9001** [comment]
This has been resolved in the latest previews
