### ISSUE TITLE
AutoSuggestBox stays showing all suggestions even there is no text in the field

### ISSUE THREAD

**Issue by yukina3230** [lepoco/wpfui#353]
Normally if I type in some text and the SuggestBox still works fine.

![Screenshot 2022-08-23 155234](https://user-images.githubusercontent.com/75545944/186117528-7fd2bb1a-a4e1-4c55-bd20-6df6f95b5a67.png)

But when I clear all the text, the box will shows all suggestions, it cannot be unfocus by clicking on other controls, and sometimes it shows on top of other windows. This bug happened on the Demo App as well.

![Screenshot 2022-08-23 155309](https://user-images.githubusercontent.com/75545944/186118564-2b61ceb5-7502-4876-859c-1359839fcfda.png)

![image](https://user-images.githubusercontent.com/75545944/186126282-0baee13f-d7b4-4176-86b1-28b25192cc8f.png)

**Comment by MulleDK19** [comment]
I've got the same issue. The moment the textbox is empty, the suggestions pop up and won't go away no matter what, including being shown on top of other windows when your app isn't even in focus.

![image](https://user-images.githubusercontent.com/3169809/187315742-c08dfcf3-2d35-4c9b-b965-141ddbdf5271.png)

**Comment by giuseppetrematerra** [comment]
The solution I found was to set this:
`    protected override void OnLostFocus(RoutedEventArgs e)
    {
        IsSuggestionListOpen = false;
        base.OnLostFocus(e);
    }`
 Setting the binding property to false on lost focus since its a textbox.
 In my case I created a subclass as workaround and overrided the method. It could be easily implemented in the actual control.

**Comment by giuseppetrematerra** [comment]
In order to close the popup even if apps are switched, I also made this:
```csharp
    protected override void OnInitialized(EventArgs e)
    {
        base.OnInitialized(e);
        Window parentWindow = Window.GetWindow(this);
        parentWindow.Deactivated += ParentWindow_Deactivated;
    }

    private void ParentWindow_Deactivated(object? sender, EventArgs e)
    {
        IsSuggestionListOpen = false;
    }
```

So on window deactivated, it closes the popup
