### ISSUE TITLE
WPFUI Extension not working with visual studio 2022 Version 17.3.1

### ISSUE THREAD

**Issue by praveencoolchap** [lepoco/wpfui#354]
WPFUI Extension not working with visual studio 2022 Version 17.3.1

![Screenshot 2022-08-24 032004](https://user-images.githubusercontent.com/4453122/186367905-ea3c736c-b261-474d-94e5-38a16ec19bfc.png)

**Comment by EthyMoney** [comment]
It's a .NET issue and currently listed under the known issues. It will be patched in an upcoming .NET update, but for now there's a workaround to get it building [here](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608)

I ran into the same issues and this quick workaround worked right away for me

**Comment by pomianowski** [comment]
Generators don't work in some versions of Visual Studio and WPF
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608=

With workaround:
* To enable build in Windows Desktop 6.0.7, navigate to the directory containing the `Microsoft.WinFx.targets` file ( `C:\Program Files\dotnet\sdk\6.0.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets` )
* Add the following target in the file:
```xaml
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
        <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
        <Analyzer Remove="@(Analyzer)" />
        <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```
