### ISSUE TITLE
The type 'DashboardViewModel' already contains a definition for 'Progress'

### ISSUE THREAD

**Issue by Kaysharp42** [lepoco/wpfui#362]
After adding the workaround outlined here https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402, I added a progress bar and variable called progress but I got this error https://i.imgur.com/CDWghFy.png

 - OS: Windows 11
 - .NET: v6.0.400

**Comment by pomianowski** [comment]
Try creating private variables with pascal case and underscore prefix:
```c#
private int _progressBarValue = 0;
```

**Comment by pomianowski** [comment]
Try creating private variables with camel case and underscore prefix:
```c#
private int _progressBarValue = 0;
```

**Comment by Kaysharp42** [comment]
It worked.
Thank you.
