### ISSUE TITLE
ProgressRing still using GPU when collapsed

### ISSUE THREAD

**Issue by Eternal-ll** [lepoco/wpfui#367]
**Describe the bug**  
I am collapsing root element of progress ring but it still using GPU.

**To Reproduce**  

**Expected behavior**  
i would like to have turn off behavior on element visibility

**Screenshots**  
![image](https://user-images.githubusercontent.com/86099479/187254902-e586e493-59cd-45ae-b6a3-25df7337fcdb.png)
![image](https://user-images.githubusercontent.com/86099479/187255187-e4ffff04-e3ba-44a9-9019-6b83770c105f.png)
![image](https://user-images.githubusercontent.com/86099479/187255034-cd95eecf-ac08-4bbe-b044-b8431269054e.png)
![image](https://user-images.githubusercontent.com/86099479/187254980-af720463-6727-49db-8ceb-265af53d3aeb.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 2.0.2

**Additional context**  
1. When root is collapsed and window is small, it dont use GPU
2. Direct turn off of IsIndeterminate is fixes the problem

**Comment by Eternal-ll** [comment]
Oh i just saw https://github.com/lepoco/wpfui/issues/69#issuecomment-1046289898

**Comment by pomianowski** [comment]
Duplicate #69
