### ISSUE TITLE
The type.. Already contains a definition for...

### ISSUE THREAD

**Issue by Sploopiii** [lepoco/wpfui#371]
Hey, I have replaced $safeprojectname$ with my project name in every document

Now it gives me the errors:![image](https://user-images.githubusercontent.com/61621914/187761641-ed357116-aa09-4b3f-a44c-a83b3241379b.png)

and I dont know what to do...

Does someone have a build I dont need to do very much? Everytime I try it will not work...

**Comment by AGIBuild** [comment]
same problem

**Comment by pomianowski** [comment]
Duplicate #354
