### ISSUE TITLE
app doesnt start

### ISSUE THREAD

**Issue by Sploopiii** [lepoco/wpfui#375]
Hey, I dont have any errors but for some reason if I start the  App no window will open up.. I dont have any clue why

what I see: https://youtu.be/m6mFGUO7_7Q

**Comment by pomianowski** [comment]
Have you used files from the Templates directory? They are for plug [WPF UI Visual Studio 2022 Templates](https://marketplace.visualstudio.com/items?itemName=lepo.wpf-ui).
![image](https://user-images.githubusercontent.com/13592821/188125412-9ad9d768-4adf-4b19-b350-3282e2a7594d.png)
