### ISSUE TITLE
Application with a dark theme on start is flickering from white to black

### ISSUE THREAD

**Issue by alxkalinin** [lepoco/wpfui#388]
**Describe the bug**  

Any WPF UI application with a dark theme is flickering on start from white to black. First, the white screen appears, following screen changes from white to black.

**To Reproduce** 

Run WPF UI Simple Demo

**Expected behavior** 

Application should start with a black screen by default with a dark theme. Flickering from white to black with a dark theme is not very convinient.

**Screenshots**  

https://user-images.githubusercontent.com/97022983/189654083-b99bbf01-2dbd-4543-9de5-e3e4c0873e02.mp4

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 2.0.2

**Comment by FreeTheTech101** [comment]
This seems to be because SimpleDemo uses `Window` instead of `ui:UiWindow`. Can you try using `ui:UiWindow` in your app?

**Comment by alxkalinin** [comment]
I've just modified SimpleDemo to use ui:UiWindow, but the result is the same.

**Comment by FreeTheTech101** [comment]
Alright, I gave the code a lookover instead of going off of memory. The issue should be fixed by pull request #389, so feel free to cherry pick the changes from there for the time being.

**Comment by alxkalinin** [comment]
> Alright, I gave the code a lookover instead of going off of memory. The issue should be fixed by pull request #389, so feel free to cherry pick the changes from there for the time being.

Thanks for the patch. But on my machine, the problem with the initial white background remains. May be it is some WPF specific to initially run the window with white background...

**Comment by FreeTheTech101** [comment]
It is possible that the issue is Windows 10 specific, as I do most of my development work on Windows 11. I know the flash is caused by the `WindowBackdropType` not being set, so it's odd it's occurring even with that patch.

https://user-images.githubusercontent.com/7614507/189692457-b5dd3b66-53a5-409d-86ed-17802211019d.mp4

**Comment by alxkalinin** [comment]
@FreeTheTech101 thanks for the help! I will try find how to fix it on my Windows 10 platform.

**Comment by alxkalinin** [comment]
Finally, it is a clear WPF issue (not WPF UI). And I found a workaround on my Windows 10. We need to use the following Window attributes

````
<ui:UiWindow
    ...
    WindowStyle="None"
    AllowsTransparency="True"
>
````
