### ISSUE TITLE
Docs doesn't work

### ISSUE THREAD

**Issue by Pietro228** [lepoco/wpfui#400]
**Describe the bug**  
Documantation throws 404 error.

**To Reproduce**  
1. Go to https://wpfui.lepo.co/documentation/

**Expected behavior**  
Open docs.

**Screenshots**  
![obrazek](https://user-images.githubusercontent.com/53868994/191518030-1ffc22a2-0a5a-404c-8da8-6e058fbe4f68.png)

**Comment by pomianowski** [comment]
Hey @Pietro228, it looks like service-worker saved an old version of the site and doesn't want to update it. To clear the application storage, use the **Clear site data** option in the **Application** tab.

![image](https://user-images.githubusercontent.com/13592821/191838177-ee0649e8-8340-4e55-9ce1-d68cbf246fc3.png)

**Comment by bry-decelles** [comment]
Please re-open this issue. The documentation is still not displaying as referenced in issue #407
