### ISSUE TITLE
Can't compile project containing a ui:Button with a Click event handler

### ISSUE THREAD

**Issue by rrickgauer** [lepoco/wpfui#404]
**Describe the bug**  

Can't compile my project when adding a Click event handler to a `<ui:Button>` control.

**To Reproduce**  

Create a new page and compile:

```xml
<Page x:Class="Tasks.Wpf.Pages.LabelsPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"
      mc:Ignorable="d" 
      d:DesignHeight="450" d:DesignWidth="800">

    <Grid>
        <ui:Button Content="Click me" Click="Button_Click"/>
    </Grid>
</Page>
```

If I change the button xaml code to this it compiles fine:

```xml
<ui:Button Content="Click me" />
```

**Expected behavior**  

I expect to be able to add a click event handler to a button.

**Screenshots**  

This is the error I get when I compile with the Click handler in the xaml file:

![image](https://user-images.githubusercontent.com/22210580/192047405-db05c3b9-28f1-44aa-9b10-598591441d1d.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10, 21H2
 - .NET: net6.0-windows 6.0.301
 - Version: 2.0.2

**Comment by rrickgauer** [comment]
What additional info would you like me to provide?

**Comment by JeremyWu917** [comment]
@rrickgauer 
After check it works to me.
You may need to have a look [tutorial](https://wpfui.lepo.co/tutorial/tutorial.html#wpf-ui-namespace)

![image](https://user-images.githubusercontent.com/54832272/192280170-1c9d7600-7a9e-49e6-b7f5-434ee5c0f120.png)
