### ISSUE TITLE
NavigationStore Orientation not working

### ISSUE THREAD

**Issue by ghost** [lepoco/wpfui#419]
### Describe the bug

NavigationStore Orientation not working

### To Reproduce

<ui:NavigationStore Orientation="Horizontal">

### Expected behavior

only vertical

### OS version

Windows 10

### .NET version

.NET Framework 4.8

### WPF-UI NuGet version

2.0.3

**Comment by Paliverse** [comment]
@pomianowski Any eta for this to be implemented in the main branch?

**Comment by m0lDaViA** [comment]
@Paliverse still an issue?

**Comment by m0lDaViA** [comment]
@pomianowski Can this issue be closed?
