### ISSUE TITLE
Documentation is broken | 404: Not Found

### ISSUE THREAD

**Issue by Ozakinn** [lepoco/wpfui#422]
### Describe the bug

I'm trying to see the documentation, but as soon as I go there the pages aren't working. Everything is has 404 not found.

### To Reproduce

Go to the Documentation: https://wpfui.lepo.co/documentation/
then 404 will appear on every pages.

### Expected behavior

View introduction and how to use controls with samples and tutorials.

### Screenshots

![image](https://user-images.githubusercontent.com/21289418/194472279-7a3c3584-85fe-4348-9f85-693cb1f6215b.png)
![image](https://user-images.githubusercontent.com/21289418/194472311-61b30901-fc07-462a-a280-abf85f959261.png)

### OS version

Windows 10
Opera GX

### .NET version

.NET isn't related here. I think. But I use .NET 6 and .Net framework 4.7/4.8

### WPF-UI NuGet version

2.0.2

**Comment by alkalinin** [comment]
To solve the issue please clean the application storage as described in the https://github.com/lepoco/wpfui/issues/400.

**Comment by pomianowski** [comment]
Duplicate #400
