### ISSUE TITLE
Can it use this project with Visual studio 2019?

### ISSUE THREAD

**Issue by pomianowski** [lepoco/wpfui#426]
### Discussed in https://github.com/lepoco/wpfui/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **HojinPark-Kor** October  6, 2022</sup>
Hello I'm Hojin, SW Developer in Korea

I tried to use this project at my new windows project on .net4.8 / Visual Studio2019 / Windows10

but occur "can't find 'AccentFillColorDisabled' resource" error at 'Application' Tag after input "xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml" in "App.xaml"

this project seems to be optimized at Visual studio 2022. a demo project as well. so i don't know it can be use in Visual studio 2019

please let me know How to use,  if it can be used in Visual studio2019 or if you know "can't find 'AccentFillColorDisabled' resource" Problem

Thank you.

</div>

**Comment by chucker** [comment]
Just tried in 2019 16.11.19, and it worked fine.

**Comment by fhnb16** [comment]
Same issue, how do you solve them?

**Comment by tegaidev** [comment]
I also have same issue, same exception. No idea how to proceed. Using VS 2019 also, but version 16.4.5 & .NET 4.7.2.
