### ISSUE TITLE
Not accurate background on Windows 10

### ISSUE THREAD

**Issue by Pietro228** [lepoco/wpfui#429]
### Describe the bug

Window background has a weird color and sometimes it's just white.

### To Reproduce

Open WPF UI app on Windows 10.

### Expected behavior

Show dark colors when Mica is not available.

### Screenshots

**Screenshots from friends computer - 3 more friends had the same issue on Windows 10.**

![unknown](https://user-images.githubusercontent.com/53868994/195165057-22886ecc-f650-41f6-81a7-eed82cbd1fc2.png)
![unknown1](https://user-images.githubusercontent.com/53868994/195165059-52362b00-70d6-48e4-a7e2-376453a94cc7.png)

### OS version

Windows 10

### .NET version

6.0

### WPF-UI NuGet version

2.0.3

**Comment by Pietro228** [comment]
When I try this I can't click on the window title bar unless the whole window has a color with the lowest transparency possible :/
![obrazek](https://user-images.githubusercontent.com/53868994/195363554-66cfaff4-4859-4bdb-8bc2-dcaff8aa74cf.png)

**Comment by Pietro228** [comment]
![obrazek](https://user-images.githubusercontent.com/53868994/195435574-b1580d13-eacb-4376-8cd9-f593384dc6a2.png)
My friend tried the new version and it looks like this

**Comment by alkalinin** [comment]
Could you check my demo application: https://github.com/alkalinin/WPF-Samples/tree/main/HelloWorld ? On my Windows 10 it works without problems.

**Comment by Pietro228** [comment]
I didn't apply that background brush, that's probably the problem. Thank you so much for helping me with my problem! :)

Btw. Where can I find a list of all resources? I know that WinUI 3 shows it in editor but I don't know how to find it in WPF.

**Comment by alkalinin** [comment]
> Btw. Where can I find a list of all resources? I know that WinUI 3 shows it in editor but I don't know how to find it in WPF.

In my Visual Studio 2022 I can start typing the property and editor shows me variants, see image below. And also in WPFUI in the development branch (not yet released) there is a great application Wpf.Ui.Gallery, where we can find list of all controls.

![image](https://user-images.githubusercontent.com/1408589/195688963-056059cc-451b-4881-a1dc-acf9eb12f56a.png)

**Comment by Pietro228** [comment]
It shows me that property. I mean how did you know which resource to use in that ThemeResource?

**Comment by alkalinin** [comment]
First, I looked at the demo application https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui.Demo/Views/Container.xaml. And second I looked at the https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui/Styles/Theme/Dark.xaml , it is a definition of the theme color.

**Comment by Pietro228** [comment]
Thank you! Btw. Your solution work for me but I didn't have to set transparent window without style

**Comment by 23W** [comment]
> First, I looked at the demo application https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui.Demo/Views/Container.xaml. And second I looked at the https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui/Styles/Theme/Dark.xaml , it is a definition of the theme color.

Links are 404

**Comment by niels9001** [comment]
This has been resolved in the latest previews
