### ISSUE TITLE
Can't add custom pages Bug

### ISSUE THREAD

**Issue by berkespace** [lepoco/wpfui#437]
### Describe the bug

Hi there, i was trying to modify the Wpfui extension templates. Tried to add my own Navigation item and page but i got this error.

System.InvalidOperationException: 'The UiDesktopApp1.Views.Pages.Test has not been registered in the Wpf.Ui.Mvvm.Contracts.IPageService service.'

### To Reproduce

When i click to the navigation button.

### Expected behavior

--

### OS version

Windows 10

### .NET version

.NET 6.0

### WPF-UI NuGet version

2.0.2

**Comment by pomianowski** [comment]
Hey @berkespace, demo applications and extension templates use the **dependency injection** mechanism to manage page instances. As the error indicates, `IPageService` does not know that the `UiDesktopApp1.Views.Pages.Test` page has been registered.

Each **Page** or **ViewModel** is treated as a service. In the case of WPF UI templates, sites are registered in X.
`App.xaml.cs`.
```c#
public partial class App
{
    private static readonly IHost _host = Host
        .CreateDefaultBuilder()
        .ConfigureServices((context, services) =>
        {
            services.AddSingleton<UiDesktopApp1.Views.Pages.Test>();
        }).Build();
}
```

This allows the `GetPage` method  of the `IPageService` to get an instance of the **Test** page with the help of the service provider.
https://github.com/lepoco/wpfui/blob/78f7c7fb84db71365d6694f9b9819b3b46023a75/src/Wpf.Ui.Extension/Templates/Wpf.Ui.Mvvm.FluentNavigation/Services/PageService.cs#L26
