### ISSUE TITLE
Style.Trigger removes wpfui specific design of textbox

### ISSUE THREAD

**Issue by c3rebro** [lepoco/wpfui#455]
### Describe the bug

Adding a Style like (for example)

```
<ui:TextBox.Resources>
    <Style TargetType="ui:TextBox">
        <Style.Triggers>
            <DataTrigger Binding="{Binding IsValidDesfireMasterKeyTarget}" Value="True">
                <Setter Property="Foreground" Value="Green" />
                <Setter Property="Background" Value="White" />
                <Setter Property="FontWeight" Value="Normal" />
            </DataTrigger>
            <DataTrigger Binding="{Binding IsValidDesfireMasterKeyTarget}" Value="False">
                <Setter Property="Foreground" Value="Black" />
                <Setter Property="Background" Value="Red" />
                <Setter Property="FontWeight" Value="Normal" />
            </DataTrigger>
        </Style.Triggers>
    </Style>
</ui:TextBox.Resources>
```

To an existing TextBox in WPF.UI Design

```
<ui:TextBox
    Grid.Row="0"
    Grid.Column="1"
    Margin="8,7,8,0"
    Height="auto"
    HorizontalContentAlignment="Left"
    VerticalContentAlignment="Center"
    Text="{Binding DesfireMasterKeyTarget, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}">
</ui:TextBox>
```

Will break the Design (back to default WPF TextBox with not rounded corners). It does not matter if the ui:TextBox is a Part of a ui:UiWindow or (like in this Case) a Part of UserControl.

### To Reproduce

See Description

### Expected behavior

Adding a Style.Trigger does ot change the design

### OS version

Windows 10

### .NET version

.NET Framework 4.8

### WPF-UI NuGet version

2.0.3

**Comment by focustense** [comment]
WPF `<style>` elements always override the component defaults, you have to inherit from the one you want.

i.e. `<Style TargetType="ui:TextBox" BasedOn="{StaticResource DefaultTextBoxStyle}">`
