### ISSUE TITLE
NavigationBase能否提供GetContext方法?

### ISSUE THREAD

**Issue by RocChing** [lepoco/wpfui#458]
### Is your feature request related to a problem? Please describe

NavigationBase已经提供SetContext方法，为什么不提供 GetContext方法?

希望_navigationService提供对应的GetContext方法 ，拿到 DataContext后，可以初始化一些赋值操作；

或者是希望跳转到某个页面时可以添加一些参数，比如如下的重载；

bool Navigate(string pageTag , Dictionary<string,object> parameter);
bool Navigate(Type pageType , Dictionary<string,object> parameter);

### Describe the solution you'd like

NavigationBase已经提供SetContext方法，为什么不提供 GetContext方法?

希望_navigationService提供对应的GetContext方法 ，拿到 DataContext后，可以初始化一些赋值操作；

或者是希望跳转到某个页面时可以添加一些参数，比如如下的重载；

bool Navigate(string pageTag , Dictionary<string,object> parameter);
bool Navigate(Type pageType , Dictionary<string,object> parameter);

**Comment by pomianowski** [comment]
Please keep the communication in English.

**Comment by RocChing** [comment]
学习一下中文可能对你会有帮助。
