### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by LHTXQ** [lepoco/wpfui#466]
### Is your feature request related to a problem? Please describe

Is the project still under development?
The content of the tutorial page is no longer available.

### Describe the solution you'd like

I love this project and hope the contributors will continue to maintain and improve it. Thanks!

**Comment by LHTXQ** [comment]
> Is the project still under development? The content of the tutorial page is no longer available.
> 
The content of the tutorial page is there again, but some of the controls (such as the decimal number box) have obvious issues that affect usage and I hope contributors can fix them.

**Comment by LHTXQ** [comment]
> > Is the project still under development? The content of the tutorial page is no longer available.
> 
> The content of the tutorial page is there again, but some of the controls (such as the decimal number box) have obvious issues that affect usage and I hope contributors can fix them.

## again...
### Is this to save electricity?

![image](https://user-images.githubusercontent.com/38943319/206852955-7b326629-737e-4fd0-905d-3a49d424b9fa.png)

**Comment by pomianowski** [comment]
Duplicate #400
