### ISSUE TITLE
Horizontal navigation

### ISSUE THREAD

**Issue by MajorXAML** [lepoco/wpfui#49]
I tried to make a horizontal navigation style, but I hit a wall, no matter what I do the list is always vertical 🤔. 
Here is an example of what I am trying to achieve
![image](https://user-images.githubusercontent.com/93913816/151697203-f57f6351-6c1a-48ed-b7b8-8ec9eef032c7.png)

Any ideas?

**Comment by pomianowski** [comment]
Hey @MajorXAML, looking at your example, I would be more interested in modifying the `<TabControl/>` style.

**Comment by MajorXAML** [comment]
Yes it can be a TabControl, but in my case I will use pages. Anyway, I already found a solution, it's incredibly simple. 😁
```
<ItemsControl.ItemsPanel>
   <ItemsPanelTemplate>
      <StackPanel Orientation="Horizontal" />
   </ItemsPanelTemplate>
</ItemsControl.ItemsPanel>
```
