### ISSUE TITLE
Document website cannot access

### ISSUE THREAD

**Issue by JingeOnline** [lepoco/wpfui#490]
### Describe the bug

The documentation website as
https://wpfui.lepo.co/
has some problem that most of the resources cannot be accessed.
(I am in Melbourne, Australia)

### To Reproduce

Go to have a look.

### Expected behavior

Can access

### Screenshots

![image](https://user-images.githubusercontent.com/42198086/210895818-8dfd6a9f-c106-4d7d-8ff0-f1bd3f3503b7.png)

### OS version

XXX

### .NET version

XXX

### WPF-UI NuGet version

XXX

**Comment by pomianowski** [comment]
Duplicate #400
