### ISSUE TITLE
Editable combobox text highlighting overflows when text surpasses combobox width

### ISSUE THREAD

**Issue by CejSmets** [lepoco/wpfui#497]
### Describe the bug

As the title suggests; When selecting text in an editable combobox, if the text does not fit inside the combobox the highlighting will overflow into the surrounding window.

### To Reproduce

1. Add a combobox width a set width (Or make the window smaller so the combobox can't grow)
2. Type an amount of text that cannot fit inside the combobox
3. Highlight all text

### Expected behavior

Text highlights, but the highlighting is not visible outside the combobox

### Screenshots

Correct behaviour when the combobox is large enough
![image](https://user-images.githubusercontent.com/74273372/212336657-eaffa96b-3187-467f-a2bd-2ee7bd0b308a.png)

As soon as the combobox does not have enough width to display all the text,, the highlighting overflows.
![image](https://user-images.githubusercontent.com/74273372/212336713-d974fcac-2fa0-4dee-bfa1-e1d74b1b09fd.png)

### OS version

Windows 11

### .NET version

.NET 6.0, .NET 7.0

### WPF-UI NuGet version

2.0.3,  as well as in the example projects (Wpf.Ui.Gallery) from the latest main branch as of january 13th, 2023.

**Comment by blueblur22** [comment]
Still present. The text field will also not scroll horizontally to show the overflow text if you move the text cursor to the right, so the user cannot see the text. The cursor just leaves the textbox instead.

![image](https://github.com/lepoco/wpfui/assets/26550726/fb3a877f-f72f-4152-a74a-bd00a03d90b7)
