### ISSUE TITLE
Mica don't work anymore on the last Insider Build

### ISSUE THREAD

**Issue by Brouilles** [lepoco/wpfui#5]
Microsoft has disabled the trick to apply Mica with dwmapi. In the last Insider Build.

**Comment by Pomianowski** [comment]
Thank you @jonasnordlund for tip, and @Brouilles for info.

I rewritten the classes responsible for the backdrop effect and checked on the Insider Preview VM.
I also added a new test window - Backdrop where you can test different effects, it looks like it works.

**Mica in Dark theme**
![wpfui-mica](https://user-images.githubusercontent.com/13592821/146686521-28827c8a-d791-4b15-b54d-a52c11e13274.png)

**Tabbed in Dark theme**
![wpfui-tabbed](https://user-images.githubusercontent.com/13592821/146686526-ae18812c-277f-4697-b59e-72364faec751.png)

**Acrylic in Dark theme**
![wpfui-acrylic](https://user-images.githubusercontent.com/13592821/146686528-35aeff74-a810-4428-99ec-a357546ca877.png)

**Acrylic in Light theme**
![wpfui-acrylic-light](https://user-images.githubusercontent.com/13592821/146686531-1a7d14e0-a2b9-44f3-9ea7-5779aa4b1ac9.png)

**Comment by dongle-the-gadget** [comment]
@jonasnordlund That opaque title bar only appears if you use the native DWM titlebar, custom titlebars shouldn't have this problem.

**Comment by jonasnordlund** [comment]
> @jonasnordlund That opaque title bar only appears if you use the native DWM titlebar, custom titlebars shouldn't have this problem.

OK, yeah that's right, I didn't consider they are already being drawn custom here.

I think this looks great and I'm happy this didn't become a sticky issue for this project moving forward!
