### ISSUE TITLE
How to implement wizard + side navigation

### ISSUE THREAD

**Issue by Diddlik** [lepoco/wpfui#526]
### Is your feature request related to a problem? Please describe

I've only used WPF UI for simple tools so far and it's all worked fine. 

Now I am faced with the problem of implementing the following, see picture:

On the left side I have a menu. Some of the items are simply buttons, the others should be opened as a page.

At the top I have the wizard with 3 steps, pages from this are displayed at the bottom. 

My question is, how can I combine these two approaches?

![grafik](https://user-images.githubusercontent.com/6010713/216842321-a8ea7497-b9e8-4d3e-a797-c5548bb5d13a.png)

### Describe the solution you'd like

Can I include navigation at the top as well as at the bottom?

**Comment by pomianowski** [comment]
Kinda NavigationView with multi-level navigation. Checkout out the gallery app in development branch.

![image](https://user-images.githubusercontent.com/13592821/217625657-e70470de-8baa-4b75-a823-8bde187beb40.png)
