### ISSUE TITLE
Can the icon property of a control such as cardcontrol support the use of fonticon?

### ISSUE THREAD

**Issue by luluxiaoyu** [lepoco/wpfui#53]
**Is your feature request related to a problem? Please describe.**
I want to customize the icon of the card  
Can the icon property of a control such as cardcontrol support the use of fonticon?  

**Describe the solution you'd like**
use the fonticon

**Comment by pomianowski** [comment]
You can use `Icon="Empty"` and manually add a `FontIcon` to the CardAction.Header or CardControl.Header
