### ISSUE TITLE
Custom FluentWindow has no titlebar

### ISSUE THREAD

**Issue by Iulian-Liviu** [lepoco/wpfui#537]
### Describe the bug

The window has no controls.

I don't know how to solve.
I NEED HELP.

### To Reproduce

Install Package.
Modify App.xaml.

Modify Window to FluentWindow in xaml and cs.

Start and view bug.

### Expected behavior

Window should have controls buttons, like maximize, minimize and close.

### Screenshots

![image](https://user-images.githubusercontent.com/98668344/219469898-2db86552-b8f9-4095-9d04-530d34c92e0b.png)

### OS version

Windows 11 22H2 22621.1105.

### .NET version

.NET 7

### WPF-UI NuGet version

Preview 2.0.0 5

**Comment by pomianowski** [comment]
Hey @Iulian-Liviu, `FluentWindow` removes the default titlebar so you can apply your own with custom styles.
If you take a look at **Wpf.Ui.Demo.Simple** you can see that **MainWindow.xaml** contains a custom `<ui:TitleBar />`.
https://github.com/lepoco/wpfui/blob/4d1c726513912d58c29326c2206ba0abec3eca8c/src/Wpf.Ui.Demo.Simple/MainWindow.xaml#L64

If you want to keep the appearance of the original window with it's navigation buttons, don't use the FluentWindow style. If you use it, you need to add your own custom styles.

**Comment by Iulian-Liviu** [comment]
Thank, this is such a beautiful framework, it help a lot with Wpf theming without worrying how it works, but I find a bit difficult to get started, maybe is because I am still learning WPF. Thanks for taking your time to respond.
