### ISSUE TITLE
InfoBar has no click event

### ISSUE THREAD

**Issue by mingyaodagege** [lepoco/wpfui#539]
### Describe the bug

InfoBar has no click event

### To Reproduce

InfoBar has no click event

### Expected behavior

InfoBar has no click event

### Screenshots

InfoBar has no click event

### OS version

InfoBar has no click event

### .NET version

InfoBar has no click event

### WPF-UI NuGet version

InfoBar has no click event

### Additional context

InfoBar has no click event

**Comment by pomianowski** [comment]
Not enough information
