### ISSUE TITLE
Consistent light theme controls

### ISSUE THREAD

**Issue by Lixkote** [lepoco/wpfui#542]
The WpfUI light controls look inconsistent with the microsoft official winui3 fluent styles. 
Here is what i mean:
![image](https://user-images.githubusercontent.com/95425619/220624052-50b3e4e5-56e4-42ad-b061-8ec180cbe7e7.png)
![image](https://user-images.githubusercontent.com/95425619/220624815-26b7f59b-37b5-4fa1-a6bf-e746744c8ee8.png)

I would like these controls to be reworked, to be more official and fluent. Plus i think the demo app should be replaced with an controls gallery like the official WinUI3 controls gallery.

**Comment by niels9001** [comment]
This has been resolved in the latest previews
