### ISSUE TITLE
Theme.Watcher.cs - System theme does not update reliably

### ISSUE THREAD

**Issue by Ch0pstix** [lepoco/wpfui#55]
**Describe the issue**  

**Theme.Watcher.cs**: subscribing to the `SystemParameters.StaticPropertyChanged` is an unreliable way to keep the styling up to date with the system theme as the event will only fire once after the first time the system color theme is changed, but no longer after that (adding to this, the properties `SystemParameters.UxThemeColor` and `SystemParameters.UxThemeName` never change).  

**Suggested implementation**  

It feels a bit hacky, as WPF is generally supposed to abstract away from Win32, but I've created a working implementation in my **SystemThemeWatcher.cs** ([view on PasteBin](https://pastebin.com/iSSx24b5)). Basically, you'd initialize it in your application's `MainWindow.SourceInitialized` event like `SystemThemeWatcher.Start(this)`. It'll create a hook, monitoring messages sent to the window from the system, looking for `WM_SETTINGCHANGE`, then calling `Manager.SetSystemTheme()` to update the theme accordingly.  

For some context I've added using aliases to **Theme.Manager** -> **ThemeManager** and **Background.Manager** -> **BackgroundManager** so I can reference either without namespace conflicts.  

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: 1.2.2-prerelease136

**Comment by IDBickel** [comment]
Also: for those interested, windows message codes can be found [here](https://www.autoitscript.com/autoit3/docs/appendix/WinMsgCodes.htm).
