### ISSUE TITLE
Backdrop Type crash the app

### ISSUE THREAD

**Issue by HugoMskn** [lepoco/wpfui#555]
### Describe the bug

When applying the Mica, Tabbed, acrylic backdrop, the app just crash
But you can still run it if you click twice on the continue execution button

### To Reproduce

Create a c# WPF project with WPF UI

Add theses line into the main windows
 ExtendsContentIntoTitleBar="True"
 WindowBackdropType="Mica" (Or any backdrop type, none work anyway)

### Expected behavior

The backdrop choosen should be added

### Screenshots

N/A

### OS version

Windows 11 22H2

### .NET version

.NET 4.7.2

### WPF-UI NuGet version

2.0.3/3.0.0 preview

**Comment by HugoMskn** [comment]
Semi fixed ? Untick this
![image](https://user-images.githubusercontent.com/81116453/224504375-553cf962-c71b-4ae5-a33f-c0105116e5fb.png)

**Comment by niels9001** [comment]
This has been resolved in the latest previews
