### ISSUE TITLE
Move fonts to separate package?

### ISSUE THREAD

**Issue by vegardlarsen** [lepoco/wpfui#56]
**Is your feature request related to a problem? Please describe.**
I noticed the file size of `WPFUI.dll` is over 3MB. It seems 2.64MB of that is from the included TTF fonts.

**Describe the solution you'd like**
Move the fonts into a separate Nuget package, that you can include only if you need to use them.

**Describe alternatives you've considered**
Removing the fonts completely?

Thank you for an otherwise great library. :)

**Comment by MajorXAML** [comment]
I think it will be a bit difficult, because font icons are quite strongly integrated into this library

**Comment by MajorXAML** [comment]
Sorry to reopen the thread. 
But I think you can reduce the font size by removing all unused icons from it, (manually, using font editor) and then generate a new enum of the remaining [icons](https://github.com/lepoco/wpfui/blob/main/WPFUI/Common/Icon.cs#L18). If @pomianowski can tell us how he generated it :)

**Comment by pomianowski** [comment]
To generate, filter and format enum with icons, I modified Character-Map-UWP, so I wouldn't recommend it as a convenient solution.
https://github.com/character-map-uwp/Character-Map-UWP

**Comment by MajorXAML** [comment]
@pomianowski Oh, then I see the problem, since we can't just update them ourselves or automate the process 😅 Since the font is frequently updated...

Maybe we can use the official list? Here are two Json files which contain the names and code of the icon https://github.com/microsoft/fluentui-system-icons/tree/master/fonts

**Comment by pomianowski** [comment]
@MajorXAML, Using that JSON we could do this:
```c#
using System.Text;
using System.Text.Json;

var filePath = @".\regular.json";
var outPath = @".\Icon.cs";

if (!File.Exists(filePath)) return 1;

FileStream fileStream = new FileStream(filePath, FileMode.Open);
using StreamReader reader = new StreamReader(fileStream);

var jsonData = JsonSerializer.Deserialize<Dictionary<string, string>>(reader.ReadToEnd());
var enumName = jsonData != null && jsonData.Any() && jsonData.First().Key.Contains("_regular") ? "Icon" : "IconFilled";

var enumMap = new StringBuilder();

enumMap.AppendLine("    public enum " + enumName);
enumMap.AppendLine("    {");
enumMap.AppendLine("        // Actually, this icon is not empty, but makes it easier to navigate.");
enumMap.AppendLine("        Empty = 0x0,");
enumMap.AppendLine("");

foreach (var singleIcon in jsonData)
{
    var name = singleIcon.Key.Replace("ic_fluent_", String.Empty).Replace("_regular", String.Empty).Replace("_filled", String.Empty);
    var iconId = (int)new System.ComponentModel.Int32Converter().ConvertFromString(singleIcon.Value);
    var iconName = "";

    foreach (var newPart in name.Split('_'))
    {
        var charactersArray = newPart.ToCharArray();
        charactersArray[0] = Char.ToUpper(charactersArray[0]);

        iconName += new string(charactersArray);
    }

    enumMap.AppendLine($"        {iconName} = 0x{iconId:X},");
}

enumMap.AppendLine("    }");

File.WriteAllText(outPath, enumMap.ToString());

Console.WriteLine("Done.");

return 0;
```
