### ISSUE TITLE
Windows using Mica backdrop show the highlight/hyperlink color on high contrast

### ISSUE THREAD

**Issue by Difegue** [lepoco/wpfui#561]
### Describe the bug

When using a High Contrast theme, Windows uses the hyperlink high contrast color for the window chrome instead of the Mica brush when requested.  
This results on difficult to read window contents on WPFUI windows that use the Mica backdrop.

WinUI apps remedy this by applying an additional border on the window background when high contrast is enabled (see Settings screenshot)  

![image](https://user-images.githubusercontent.com/8237712/225603592-2033e066-6659-4779-aa3d-1801958df5b1.png)

### To Reproduce

Turn High Contrast on in Windows and open the Sample app.  

(I don't think the Sample app has any option to use the `HighContrast` theme dictionary, but this issue happens regardless of the selected theme dictionary.)

### Expected behavior

I'd expect the background to remain white/readable, with the hyperlink color only being used for the focus border of the window.  

### Screenshots

![image](https://user-images.githubusercontent.com/8237712/225603407-7af6d0af-3558-4300-8df1-988630d8d5f4.png)  

### OS version

Windows 11

### .NET version

Any .NET version

### WPF-UI NuGet version

Both v2 and v3.

### Additional context

High Contrast colors are easily customizable starting with Win11, but the selected colors seem to be available through the [SystemColors](https://learn.microsoft.com/en-us/dotnet/api/system.windows.systemcolors?view=windowsdesktop-7.0&viewFallbackFrom=netcore-3.1) enum.  

It might be a good idea to modify the `HighContrast` theme dictionary to use those? Not sure how WinUI does it.

**Comment by niels9001** [comment]
This has been resolved in the latest previews
