### ISSUE TITLE
MessageBox & Dialog have different event handlers

### ISSUE THREAD

**Issue by Wlad57** [lepoco/wpfui#57]
Hello,

I found that two rather identical controls take a different approach to event handling

[MessageBox ](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/MessageBox.cs#L186) uses one command and two parameters
while [Dialog ](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/Dialog.cs#L169) uses only two commands (one of them doesn't work)

Could you please tell me which one of these two is correct?

**Comment by pomianowski** [comment]
Hi, I don't really understand "rather identical controls". Dialog and MessageBox are two completely different controls.
The Dialog simply creates a centered Grid in our style, while MessageBox creates a window completely separate from the main application window.
