### ISSUE TITLE
The name "NavigationStore" doesn't exist in the namespace "http://schemas.lepo.co/wpfui/2022/xaml"

### ISSUE THREAD

**Issue by lomychx** [lepoco/wpfui#587]
### Describe the bug

I try to migrate the demo.simple to a whole new project for learning purpose.

### To Reproduce

Create a new project
install nuget package.
Change the app.xaml as tutorial.
Change the mainWindow.xaml as the demo mainWindows.xaml

### Expected behavior

NavigationStore should be contained? I saw it in wpf.ui.simpledemo

### Screenshots

![image](https://user-images.githubusercontent.com/87072272/231266760-3ca14024-b475-4a27-9e61-057dbfccb3fc.png)

### OS version

windows 11

### .NET version

6.0

### WPF-UI NuGet version

3.0.0 preview 1
![image](https://user-images.githubusercontent.com/87072272/231266984-b358b2d8-f75a-44bc-ac81-86ca8413aed5.png)

### Additional context

Ошибка	XDG0008	Имя "NavigationStore" не существует в пространстве имен "http://schemas.lepo.co/wpfui/2022/xaml".

**Comment by zh3305** [comment]
This feature has not been released yet, you can try to introduce the project
