### ISSUE TITLE
Does this add a custom tooltip and if yes, how do I disable it?

### ISSUE THREAD

**Issue by Zopenzop** [lepoco/wpfui#59]
I actually made a custom tooltip style for myself, but I think this package adds its own tooltip style too. How do I disable it?

**Comment by MajorXAML** [comment]
Yes. https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Controls/ToolTip.xaml

**Comment by Zopenzop** [comment]
Apparently merging the package's dictionary in the app.xaml does change the tooltip style. How do I disable it? I have my own tooltip style.

**Comment by pomianowski** [comment]
Hey @Zopenzop, the question is rather about how to style the controls, which you can find in the WPF documentation. Tooltip in *WPF UI* overrides the default style. You can either create your own style and modify the imports to make your custom `/Styles/WPFUI.xaml` alternative. Or you can add a Key to your custom Tooltip style that you will use later.

https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-create-apply-style?view=netdesktop-6.0#relationship-of-the-targettype-property-and-the-xkey-attribute

https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/tooltip-styles-and-templates?view=netframeworkdesktop-4.8
