### ISSUE TITLE
Dialog has no EventHandler for Left button.

### ISSUE THREAD

**Issue by Wlad57** [lepoco/wpfui#60]
**Describe the bug**  
Dialog has EventHandler for ButtonRightClick but not for ButtonLeftClick 

**Additional context**  
As I mentioned [here](https://github.com/lepoco/wpfui/issues/57), their event handler code for the buttons is different, yes they are different controls, but the purpose of the buttons is the same in both controls - one for action the other for cancel.

**Comment by MajorXAML** [comment]
As far as I can see, the left button is just `Click`. Not very obvious I agree :D

To answer your previous question, this can happen when the code is written at different times. I use the MessageBox method (i.e. switch/case)
