### ISSUE TITLE
Dark theme not working in Windows 10

### ISSUE THREAD

**Issue by moonway-dev** [lepoco/wpfui#600]
### Describe the bug

Windows 10:
![image 1](https://user-images.githubusercontent.com/59399356/233215558-6a4009ae-a6f1-483a-a0a1-c476406f18ad.png)

Windows 11:
![image](https://user-images.githubusercontent.com/59399356/233215768-a22ad999-7b27-4ff7-8942-5ac9a8187812.png)

my test code:
`
if (winver() >= 22000)
            {
                Wpf.Ui.Appearance.Theme.Apply(Wpf.Ui.Appearance.ThemeType.Dark, Wpf.Ui.Controls.Window.WindowBackdropType.Mica, true);
            }
            else if (winver() >= 17763)
            {
                Wpf.Ui.Appearance.Theme.Apply(Wpf.Ui.Appearance.ThemeType.Dark, Wpf.Ui.Controls.Window.WindowBackdropType.Auto, true);
            }
`

### To Reproduce

Wpf.Ui.Appearance.Theme.Apply(Wpf.Ui.Appearance.ThemeType.Dark, Wpf.Ui.Controls.Window.WindowBackdropType.Auto, true);

### Expected behavior

The display should be the same as on Windows 11

### OS version

Windows 11 22H2

### .NET version

.NET Framework 4.7.1

### WPF-UI NuGet version

3.0.0-preview1

**Comment by pomianowski** [comment]
Hey @moonway-dev, I cannot reproduce the bug, Please provide an example repository where you successfully reproduce the bug.

**Comment by IrisV3rm** [comment]
> Hey @moonway-dev, I cannot reproduce the bug, Please provide an example repository where you successfully reproduce the bug.
> 
> Also make sure that your App.xml contains WPF UI dictionaries
> 
> ```
> <Application
>   ...
>   xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml">
>   <Application.Resources>
>     <ResourceDictionary>
>       <ResourceDictionary.MergedDictionaries>
>         <ui:ThemesDictionary Theme="Dark" />
>         <ui:ControlsDictionary />
>       </ResourceDictionary.MergedDictionaries>
>     </ResourceDictionary>
>   </Application.Resources>
> </Application>
> ```

I have it set up correctly above, and I'm also receiving the issue he is facing

**Comment by IrisV3rm** [comment]
Update: Its according to the mica backround is the issue iirc

**Comment by niels9001** [comment]
@IrisV3rm could you verify if this issue is still present on the latest preview? (`preview-10`)

**Comment by IrisV3rm** [comment]
> @IrisV3rm could you verify if this issue is still present on the latest preview? (`preview-10`)

Hello, just checked my software on a win10 vm with latest updates to both, I can confirm that the issue is no longer present, it's not mica (which I understand mica is windows 11 required), but it does retain dark mode and can run functionally.

**Comment by niels9001** [comment]
Great to hear! Thanks for testing!
