### ISSUE TITLE
Following "How to use" results into build error "'Ui' does not exist"

### ISSUE THREAD

**Issue by tomasfil** [lepoco/wpfui#607]
### Describe the bug

Following:
https://github.com/lepoco/wpfui#-how-to-use

Results into:
The type or namespace name 'Ui' does not exist in the namespace 'Client.Wpf' (are you missing an assembly reference?)

### To Reproduce

1. Create new WPF App.
2. Install WPF-UI package
3. Follow: https://github.com/lepoco/wpfui#-how-to-use

### Expected behavior

Should work as intended.

### OS version

Windows 10

### .NET version

NET 7

### WPF-UI NuGet version

2.0.3

**Comment by tomasfil** [comment]
The same happens even if I create completely new project from Extension template:
![image](https://user-images.githubusercontent.com/34779382/234050592-0ca50880-25b5-46f1-ae87-bf70d60aaf3f.png)


![image](https://user-images.githubusercontent.com/34779382/234050638-e4155ce9-dc9c-43f9-b8ac-8971835553b0.png)

**Comment by pomianowski** [comment]
Hey @tomasfil, I cannot reproduce the bug, Please provide an example repository where you successfully reproduce the bug.

**Comment by tomasfil** [comment]
Seems like the original repository now just simply works. 
Propably some Visual studio shenanigans, Sorry to bother.
