### ISSUE TITLE
ListView doesn't look as it should

### ISSUE THREAD

**Issue by yagudron** [lepoco/wpfui#610]
### Describe the bug

ListView doesn't look like it does in the gallery application.

### To Reproduce

Create a project using the VS Extension, and add a ListView to any page.

### Expected behavior

The ListView should be styled like in the demos.

### Screenshots

![image](https://user-images.githubusercontent.com/7910223/234226080-cf93e539-44bc-4211-b013-8f56320d847b.png)
 
vs.

![image](https://user-images.githubusercontent.com/7910223/234227800-29769348-a1f4-4834-bf83-bc3b7bb2daad.png)

### OS version

Edition	Windows 11 Home
Version	22H2
Installed on	‎22/‎10/‎13
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

### .NET version

.NET 6.0

### WPF-UI NuGet version

2.0.3

### Additional context

I have looked at the demo Gallery application and can't seem to find the reason why it works differently there. I have tried copying styles over, but then I lose the proper switch of Dark/Light themes for the control. Am I missing something very crucial, or this is a bug?

**Comment by pomianowski** [comment]
Hey @yagudron, Gallery user preview release of the library. Checkout the 3.0.0-preview.2 version on NuGet.org.
https://www.nuget.org/packages/WPF-UI/3.0.0-preview.2

**Comment by yagudron** [comment]
@pomianowski, thanks! That helped, albeit I needed to adapt my code a bit for the new version.
