### ISSUE TITLE
if MainWindow set WindowState='Maximized' then window lacks the top margin and right margin

### ISSUE THREAD

**Issue by yuyihu** [lepoco/wpfui#615]
### Describe the bug

![1682578433796](https://user-images.githubusercontent.com/64644171/234783766-13c718e6-62db-4a9f-aac6-2ec925bd6484.jpg)

### To Reproduce

.

### Expected behavior

![image](https://user-images.githubusercontent.com/64644171/234784320-13aba955-031e-44dd-994e-702c6a9c8a26.png)

### Screenshots

.

### OS version

.

### .NET version

net6

### WPF-UI NuGet version

all version 

### Additional context

.

**Comment by blakepell** [comment]
@yuyihu I just had the same issue.  I had set the WindowState to maximized in the window constructor.  Moving the code later in the life cycle fixes the issue (I used the window loaded event and the margins are then correct).
