### ISSUE TITLE
WPF UI Gallery Problem

### ISSUE THREAD

**Issue by laipuran** [lepoco/wpfui#624]
### Describe the bug

C# source code not shown correctly.

### To Reproduce

Enter Navigation then NavigationView
You can see it right away

### Expected behavior

<RichTextBox />

### Screenshots

![image](https://user-images.githubusercontent.com/55612059/236372032-813e7e53-7ab7-4c16-b050-80e4df7a21c7.png)

### OS version

Win10 2202

### .NET version

7.0.2

### WPF-UI NuGet version

Default

### Additional context

None

**Comment by zh3305** [comment]
fix on #592  #603
