### ISSUE TITLE
How to use Dialog

### ISSUE THREAD

**Issue by gaowanliang** [lepoco/wpfui#632]
### Is your feature request related to a problem? Please describe

I found that `Dialog` seem to have undergone multiple modifications, with many different implementation methods. I am a bit confused, and the examples provided by `Gallery` seem very complex. 

### Describe the solution you'd like

Can you provide a more concise example to implement `Dialog`.

**Comment by FunJoo** [comment]
官方给的示例是Wpf.Ui.Gallary里面有。通过依赖注入，调用IDialogService使用。

**Comment by gaowanliang** [comment]
I noticed that the `Gallery` in the main branch version is not the same as the operation provided in the `NuGet package`, and when I downloaded the code provided in Release, the `demo` included in it was an example that could be used for the version of the code provided in the `NuGet package`.
