### ISSUE TITLE
The FontSize Stlye

### ISSUE THREAD

**Issue by MakesYT** [lepoco/wpfui#635]
### Describe the bug

The FontSize property of TextBox has no effect on the size of the Icon
And the ClearButton display is abnormal. It should be centered, but in fact it is up (on 2.0.3)/ not displayed (on 3.0.0pre2).
`
<ui:TextBox ClearButtonEnabled="True" FontSize="32">
            <ui:TextBox.Icon>
                <ui:SymbolIcon   Symbol="Search48"  FontSize="32"/>
            </ui:TextBox.Icon>
        </ui:TextBox>
`

### To Reproduce

1.  No special steps, only install from Nuget
2. `
<ui:TextBox ClearButtonEnabled="True" FontSize="32">
            <ui:TextBox.Icon>
                <ui:SymbolIcon   Symbol="Search48"  FontSize="32"/>
            </ui:TextBox.Icon>
        </ui:TextBox>
`

### Expected behavior

The size of the Icon should be controlled by FontSize or some other property,
And the ClearButton display at the center.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/42534870/5d4693a8-1199-49fe-bb54-99e1715cc65e)

### OS version

版本	Windows 11 专业工作站版
版本	22H2
安装日期	‎2022/‎7/‎27
操作系统版本	22624.1690
体验	Windows Feature Experience Pack 1000.22641.1000.0

### .NET version

net7.0-windows

### WPF-UI NuGet version

3.0.0pre2

**Comment by bbsuuo** [comment]
我猜你布局有问题

**Comment by MakesYT** [comment]
> 我猜你布局有问题

也许反正改不了大小

**Comment by MakesYT** [comment]
> 我猜你布局有问题

也许反正改不了大小

**Comment by niels9001** [comment]
Fixed in #638
