### ISSUE TITLE
Feature request: Modal Window

### ISSUE THREAD

**Issue by Wlad57** [lepoco/wpfui#64]
I propose to create a control that is called a Modal Window, the content of which will be in the form of a page.

![image_2022-02-17_172438](https://user-images.githubusercontent.com/97350944/154501564-17913402-68db-4c0e-98ea-99bf0de9cac6.png)

After pressing the button, we show the modal window which is located in MainWindow (`IsOpen = true;`) and define its content, for example as it is done with navigation` Type="{x:Type pages:Page1}"`

What do you think about this? I can create the xaml part but the navigation part is a bit complicated for me 😅

**Comment by MajorXAML** [comment]
Good idea, not sure about "as it is done with navigation" but you could try putting the page in the Сontent of the modal window before it opens. The xaml part is easy, you could take [Dialog](https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Controls/Dialog.xaml) as a basis. Remove everything unnecessary and add a close button.

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/blob/b6e846262573336b265fdf033b682339beb43570/src/Wpf.Ui/Controls/MessageBox.cs#L16

https://github.com/lepoco/wpfui/blob/b6e846262573336b265fdf033b682339beb43570/src/Wpf.Ui/Controls/Dialog.cs#L15

The above controls allow you to achieve this effect
