### ISSUE TITLE
When the mouse is removed from the item, its icon is displayed incorrectly

### ISSUE THREAD

**Issue by buaaCCJ** [lepoco/wpfui#65]
![Dingtalk_20220218015029](https://user-images.githubusercontent.com/20292463/154541139-9956eebb-1561-4f2f-b001-df56e520ee74.jpg)

**Comment by MajorXAML** [comment]
I don't quite understand where to look and what's going on here..

**Comment by pomianowski** [comment]
Closed due to lack of further information.
