### ISSUE TITLE
3.0 preview3 ui:TitleBar's control can not get focus

### ISSUE THREAD

**Issue by yuyihu** [lepoco/wpfui#660]
### Describe the bug

![image](https://github.com/lepoco/wpfui/assets/64644171/bf8f1e56-cb72-4807-b84b-7bfb4de1afec)

use ui:FluentWindow  then the controls in ui:TitleBar like Button can't click.

Another problem may be the same reason : use ui:FluentWindow and set WindowStyle="None"， can't not drag and move the MainWindow。

### To Reproduce

xaml code like  this.
![image](https://github.com/lepoco/wpfui/assets/64644171/6a13a159-19c6-4b81-b1f6-a26c21991e73)

### Expected behavior

.

### Screenshots

.

### OS version

win10

### .NET version

net6.0

### WPF-UI NuGet version

3.0.0 Preview3

### Additional context

.

**Comment by zznty** [comment]
can we get this fix for regular control that are being drawn on titlebar area to be focusable too. like i have search box on the titlebar but even with the fix only controls inside TitleBar.Header are being hit tested which is not the case for searchbox.
