### ISSUE TITLE
Double clicking the icon will crash the app

### ISSUE THREAD

**Issue by giiyms** [lepoco/wpfui#667]
### Describe the bug

In the WPF UI Gallery example, when I double click the icon next to the title in the title bar, it will silently crash the app.

Any ideas what is happening?

### To Reproduce

Double click the icon in the title bar

### Expected behavior

Do nothing

### OS version

Build 19045

### .NET version

7.0

### WPF-UI NuGet version

3.0.0-prev2

**Comment by IvanDmitriev1** [comment]
If you don't want this behavior, set `CloseWindowByDoubleClickOnIcon="False"` in `ui:TitleBar`.
