### ISSUE TITLE
PasswordBox text cleared when value is shown / hidden

### ISSUE THREAD

**Issue by Revan1985** [lepoco/wpfui#669]
### Describe the bug

When the password box raw value is shown/hidden with the button, text is cleared away

### To Reproduce

Just use the Gallery project in github code

### Expected behavior

Password should not be cleaned when hiding/showing characters

### Screenshots

Before clicking show button
![image](https://github.com/lepoco/wpfui/assets/547547/2423ec92-858d-4124-805f-cffc491cee96)
After clicked
![image](https://github.com/lepoco/wpfui/assets/547547/ec0d16f8-8f6d-4517-b835-ae2b56e21922)
Enter again showing the value
![image](https://github.com/lepoco/wpfui/assets/547547/e2a2db21-2590-4b2c-9aa1-8868fb361f56)
After Hiding again
![image](https://github.com/lepoco/wpfui/assets/547547/1ec69805-ecf6-4dfc-8ea4-86c1f4f62f6b)

### OS version

Windows 11 10.0.22621

### .NET version

net7.0

### WPF-UI NuGet version

3.0.0-preview.3

**Comment by MrCosmo** [comment]
I can't seem to reproduce this issue.
![20230801 Password](https://github.com/lepoco/wpfui/assets/3482460/357854ba-54b9-4d8f-a34f-02ecd17e2a80)

**Comment by Revan1985** [comment]
uhm, maybe I was using another version, the ui in my screens are different from the master ones...
My mistake, i cannot either reproduce it...
Will just close, sorry for the inconvenience...
