### ISSUE TITLE
Toggle switch control change the color of the Button

### ISSUE THREAD

**Issue by alxkalinin** [lepoco/wpfui#67]
**Describe the bug**  

In my demo application I have ToggleSwitch control and a Button. When I change the ToggleSwitch state, the color of the Button also changed.

**Screenshots**  

https://user-images.githubusercontent.com/97022983/154750116-3670a432-7bc6-4640-bcb1-1c51ffdfa6d9.mp4

**Desktop**  
 - OS: Windows 10
 - .NET: net6.0-windows
 - Version: latest version from 18.02.2022, https://github.com/lepoco/wpfui/commit/353aae4d8821430d80c43f2cc7aa9e6d7c89ec30

**Comment by pomianowski** [comment]
That's funky bug. Probably the color binding is breaking something, I'll try to fix it soon

**Comment by alxkalinin** [comment]
Thank you very much for the quick response and quick fix! Probably we also need duplicate the brush for the textbox also.

```xml
            <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
                <wpfui:ToggleSwitch Margin="5" HorizontalAlignment="Center" />
                <TextBox />
                <Button
                    Margin="5"
                    HorizontalAlignment="Center"
                    Content="OK" />
            </StackPanel>
```

https://user-images.githubusercontent.com/97022983/154802935-253e8c66-9e89-4782-8d15-b7011d2a6909.mp4
