### ISSUE TITLE
[TitleBar] Dragging no longer works when  SizeToContent is set on Window

### ISSUE THREAD

**Issue by niels9001** [lepoco/wpfui#674]
### Describe the bug

Dragging the window no longer works when using a `TitleBar` and setting the `SizeToContent` to `WidthAndHeight` on the Window.

### To Reproduce

- Set ` SizeToContent="WidthAndHeight"` on the `MainWindow`
- Use a `TitleBar`

### Expected behavior

Dragging to work

### OS version

Windows 11

### .NET version

NET 7

### WPF-UI NuGet version

Preview-3

**Comment by Nice3point** [comment]
@niels9001 fixed, try it

**Comment by niels9001** [comment]
> @niels9001 fixed, try it

Amazing! Will give this a try!

@pomianowski will this be included in preview-14? This fix might just unblock us on 2 PowerToys modules!

Cc @jay-o-way

**Comment by pomianowski** [comment]
Hey @niels9001, the change is already included in the latest version marked as release **3.0.0**
