### ISSUE TITLE
[Flyout] Missing Opened and Closed event

### ISSUE THREAD

**Issue by niels9001** [lepoco/wpfui#675]
### Describe the bug

The `Flyout` control does not have an `Opened` and `Closed` event. Would be great to have those to update specific logic in an app.

### To Reproduce

..

### Expected behavior

Simple `Opened` and `Closed` event

### OS version

Windows 11

### .NET version

NET 7

### WPF-UI NuGet version

Preview-3

**Comment by MrCosmo** [comment]
Seems to be implemented already:
https://github.com/lepoco/wpfui/blob/development/src/Wpf.Ui/Controls/Flyout.cs#L114

**Comment by MrCosmo** [comment]
This issue should be closed @pomianowski since the PR has been merged.
