### ISSUE TITLE
Visual styles are different in DEMO application, WPF control and WPFUI controls

### ISSUE THREAD

**Issue by alxkalinin** [lepoco/wpfui#68]
**Describe the bug**  

We have a difference in controls visual styles across DEMO application, WPF controls and WPFUI controls.

In DEMO application we have the "Dark" theme, "Gray Button" and the "Light Gray Accent":

https://user-images.githubusercontent.com/97022983/154794580-42add893-d01a-4bf2-912e-049e69f64a3f.mp4

In simplest application with "WPF Button"
```xml
        <Grid Grid.Row="1">
            <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
                <wpfui:ToggleSwitch Margin="5" HorizontalAlignment="Center" />
                <Button
                    Margin="5"
                    HorizontalAlignment="Center"
                    Content="OK" />
            </StackPanel>
        </Grid>
```
we have "Dark" theme, "Blue Button" and the "Dark Gray Accent"

https://user-images.githubusercontent.com/97022983/154794677-3d57650f-b3f0-4043-8e4c-ff56546bc0b2.mp4

In simplest application with "WPFUI Button"
```xml
        <Grid Grid.Row="1">
            <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
                <wpfui:ToggleSwitch Margin="5" HorizontalAlignment="Center" />
                <wpfui:Button
                    Margin="5"
                    HorizontalAlignment="Center"
                    Content="OK" />
            </StackPanel>
        </Grid>
    </Grid>
```
we have we have "Dark" theme, "Blue Button" and the "Dark Blue Accent"

https://user-images.githubusercontent.com/97022983/154794747-5d96246d-e21b-4e5a-9b28-206114665022.mp4

**Could we have the same style across all controls, something like this**

```xml
<ui:ThemeResources RequestedTheme="Dark" AccentColor="Red" />
```

**Desktop**  

 - OS: Windows 10.0.19044
 - .NET: 6.0.200
 - Version: latest build from 19.02.2022

**Comment by pomianowski** [comment]
Demo app fires up experimental https://github.com/lepoco/wpfui/blob/70f8ecfd99e757bd7c4ff6d8d185df675d2914e3/WPFUI/Theme/Watcher.cs#L45

with `useMica` and `useAccent`

**Comment by alxkalinin** [comment]
Thanks for explanation!
