### ISSUE TITLE
Button doesn't have Appearance property

### ISSUE THREAD

**Issue by rounk-ctrl** [lepoco/wpfui#7]
**Describe the bug**  
I wanted to apply the secondary button style but then there was no Appearance property in WPFUI button.

**Expected behavior**  
Appearance property to be there.

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: Framework 4.8
 - Version: 1.1.0

**Additional context**  
```
Error
The property 'Appearance' does not exist in XML namespace 'clr-namespace:WPFUI.Controls;assembly=WPFUI'. 
```

**Comment by Pomianowski** [comment]
Hey @rounk-ctrl. Can you check if the bug still occurs in the latest prerelease?

**Comment by rounk-ctrl** [comment]
Nope, its fixed.
