### ISSUE TITLE
ContextMenu Styling in Windows 10 20H2 not working

### ISSUE THREAD

**Issue by Inzaniity** [lepoco/wpfui#71]
**Describe the bug**  
Context Menu styling on Windows 10 20H2 is broken. (Running this build in a corporate environment)

**Expected behavior**  
Styling to be the same as in the systray context menu.

**Screenshots**  
ContextMenu in the Demo-App
![image](https://user-images.githubusercontent.com/17164019/155115629-85146fb1-c7bc-407d-91c0-556766532c0a.png)

ContextMenu in the Demo-App's systray icon
![image](https://user-images.githubusercontent.com/17164019/155115825-d0325daa-b6d9-41a8-b94c-92e0a60d8a5e.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 20H2
 - .NET: net6.0-windows
 - Version: Latest stable 1.2.1

**Additional context**  
The issue happens in my own app as well as in the demo-app. I added the 
Added the ResourceDictionary

```XAML <ResourceDictionary.MergedDictionaries>
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/Theme/Light.xaml" />
<ResourceDictionary Source="pack://application:,,,/WPFUI;component/Styles/WPFUI.xaml" />
</ResourceDictionary.MergedDictionaries>
```

Applied the style to my Mainwindow
`Style="{DynamicResource UiWindow}"`

**Comment by MajorXAML** [comment]
As far as I can see, styling doesn't work because it doesn't exist in this lib

**Comment by Inzaniity** [comment]
> As far as I can see, styling doesn't work because it doesn't exist in this lib

Then the question is, why is the styling broken if the lib doesn't override / use context menu styling. As you can see in the first screenshot there's this weird vertical line. I'll see what the context menu looks like on a windows 11 machine.

**Comment by jz5** [comment]
The reason for this is that MenuItem style is overridden in Menu.xaml.

**Comment by pomianowski** [comment]
Should be better 
![image](https://user-images.githubusercontent.com/13592821/158039836-60de1e90-3a6f-4c74-8020-c989ac7e8af8.png)
