### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by bloodylucifer** [lepoco/wpfui#711]
### Describe the bug

https://prnt.sc/1rUzSQ_RN0N4
https://prnt.sc/m2P2tRmVJjBy
OS: Windows 10
.NET: net6.0-windows
Version: 2.0.2 (WPF-

### To Reproduce

Perspiciat

### Expected behavior

Doloremque

### Screenshots

Sapiente i

### OS version

Consectetu

### .NET version

Sed est su

### WPF-UI NuGet version

Qui et ven

### Additional context

Voluptas i

**Comment by Thazzr** [comment]
Are u sure, your namespace is Wpf.Ui?

**Comment by pomianowski** [comment]
Please keep communication in English
