### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by Steff093** [lepoco/wpfui#720]
I would like to be able to switch to a new page with a button (Multiple Windows in WinUI 3).  

I would like to implement a function in my application to switch to a new page via button click. So far this already works in WinUi 3 but unfortunately not here yet. Would be nice if you can still implement th

### Describe the solution you'd like

I would like to implement a function in my application to switch to a new page via button click. So far this already works in WinUi 3 but unfortunately not here yet. Would be nice if you can still implement th

![image](https://github.com/lepoco/wpfui/assets/137640230/73af8098-d907-4406-9340-b519c3d68acb)

**Comment by pomianowski** [comment]
I don't quite understand your issue, once you talk about `Window`, once about `Page`.

If you want to navigate with the help of a button, and you use a dependency model, you can use a navigation service
```c#
public partial class DashboardViewModel : ObservableObject
{
    private readonly INavigationService _navigationService;

    public DashboardViewModel(INavigationService navigationService)
    {
        _navigationService = navigationService;
    }

    [RelayCommand]
    private void OnCardClick(string parameter)
    {
        _navigationService.Navigate(typeof(SettingsPageOrWhatever));
    }
}
```

If you want to create a new window, you simply create a new window
```c#
var windowInstance = new MyWindowClass();
windowInstance.Owner = Application.Current.MainWindow;
windowInstance.Show();
```
or
```c#
var windowInstance = _serviceProvider.GetRequiredService<MyWindowClass>();
windowInstance.Owner = Application.Current.MainWindow;
windowInstance.Show();
```

If your newly created window also has navigation, you can do so:
```xaml
<ui:NavigationView x:Name="RootNavigation" />
```
```c#
var windowInstance = _serviceProvider.GetRequiredService<MyWindowClass>();
windowInstance.Owner = Application.Current.MainWindow;
windowInstance.Loaded += (sender, args) =>
{
    if (sender is MyWindowClass window)
    {
        window.RootNavigation.Navigate(typeof(DashboardPageOrSomething));
    }
}
windowInstance.Show();
```
