### ISSUE TITLE
[NavigationView] Support for Pages of the same TargetPageType

### ISSUE THREAD

**Issue by Ayley** [lepoco/wpfui#736]
### Is your feature request related to a problem? Please describe

I want add pages dynamic to the navigation. These pages have the same TargetPageType and share the ViewModel so that i have the same data in every page.  

### Describe the solution you'd like

Support for using multiple pages of the same TargetPageType with there own data context.

**Comment by pomianowski** [comment]
There are no plans to support such a scenario.
