### ISSUE TITLE
Pane is not closed by default when using `IsPaneOpen="False"`

### ISSUE THREAD

**Issue by vikofun** [lepoco/wpfui#741]
### Describe the bug

Setting IsPaneOpen to False for the NavigationView of MainWindow.xaml in project Wpf.Ui.Demo.Mvvm does not work.

### To Reproduce

`<ui:NavigationView
            x:Name="RootNavigation"
            Grid.Row="1" 
            IsPaneOpen="False"
            FooterMenuItemsSource="{Binding ViewModel.NavigationFooter, Mode=OneWay}"
            MenuItemsSource="{Binding ViewModel.NavigationItems, Mode=OneWay}">`

### Expected behavior

After setting FALSE to start, it should be in a closed state

### Screenshots

![微信截图_20230827121740](https://github.com/lepoco/wpfui/assets/50802038/57148a41-7509-4220-9f07-0f5004a0e1f4)
![微信截图_20230827121812](https://github.com/lepoco/wpfui/assets/50802038/c2567aba-d3f6-4a69-8d4a-2577601ab58e)

### OS version

last

### .NET version

last

### WPF-UI NuGet version

last

**Comment by lzl32947** [comment]
Similar issue, I bind one bool property to `IsPaneOpen` to try to control the drawer open or not in program, it works correct when I   did not toggle the drawer manually, but when I manually open and close the drawer one or more time, the `IsPaneOpen` property has one fault value and can not open and close with programly control.

**Comment by tmijail** [comment]
> Similar issue, I bind one bool property to `IsPaneOpen` to try to control the drawer open or not in program, it works correct when I did not toggle the drawer manually, but when I manually open and close the drawer one or more time, the `IsPaneOpen` property has one fault value and can not open and close with programly control.

Does this happen even with `Mode=TwoWay`?
