### ISSUE TITLE
WPF UI Gallery Problem

### ISSUE THREAD

**Issue by wzy2505353012** [lepoco/wpfui#745]
### Describe the bug

component overlapping with title

### To Reproduce

In the component of within demo of "Wpf.Ui.Gallery-->MainWindow.xaml-->ui:NavigationView",
if I set 
IsBackButtonVisible="Visible"
IsPaneToggleVisible="True"
to
IsBackButtonVisible="Collapsed"
IsPaneToggleVisible="False"

### Expected behavior

component display below the title Bar

### OS version

win11 22H2

### .NET version

.NET6

### WPF-UI NuGet version

wpfui main Branch
https://github.com/lepoco/wpfui/commit/c8cd75f6f82414a52a94d2a55fe2a21dd5db83d7

**Comment by pomianowski** [comment]
This is the expected and intentional arrangement of the elements in the `Grid` so that the `TitleBar` overlaps the `NavigationView`.
