### ISSUE TITLE
FilePicker and FolderPicker

### ISSUE THREAD

**Issue by jaredlhamilton** [lepoco/wpfui#748]
### Is your feature request related to a problem? Please describe

I am working on an application that requires a FilePicker and a FolderPicker. It would be nice if it looked similar to the rest of the WPF UI application.

### Describe the solution you'd like

Is there a plan to implement a FilePicker and a FolderPicker? The WPF UI Gallery has a FilePicker menu item, but it does not appear to be implemented.

<img width="1088" alt="WPF UI Gallery FilePicker" src="https://github.com/lepoco/wpfui/assets/5350247/7d55ab41-a8fd-430a-8183-fec5e6212007">

### Describe alternatives you've considered

I have considered using a FilePicker and FolderPicker using the Ookii.Dialogs.Wpf library.

**Comment by pomianowski** [comment]
Updated in https://github.com/lepoco/wpfui/commit/b5fe3f30eae8129ab73e99883bc59d44cc984766

https://github.com/lepoco/wpfui/blob/b5fe3f30eae8129ab73e99883bc59d44cc984766/src/Wpf.Ui.Gallery/ViewModels/Pages/OpSystem/FilePickerViewModel.cs#L91

https://github.com/lepoco/wpfui/blob/b5fe3f30eae8129ab73e99883bc59d44cc984766/src/Wpf.Ui.Gallery/ViewModels/Pages/OpSystem/FilePickerViewModel.cs#L120
