### ISSUE TITLE
How to enumerate colors

### ISSUE THREAD

**Issue by melinyi** [lepoco/wpfui#755]
### Is your feature request related to a problem? Please describe

I am unable to obtain relevant color information from ui:ThemeResource or  StaticResource or DynamicResource

![Uploading image.png…]()

### Describe the solution you'd like

How to add static resources and use them in xaml attributes

**Comment by melinyi** [comment]
Im try Change
<ui:ThemesDictionary Theme="Dark"  
to 
<ResourceDictionary Source="pack://application:,,,/Wpf.Ui;component/Resources/Theme/Dark.xaml"/>
will work properly，Will this affect the normal operation of other components

**Comment by syntax-tm** [comment]
No. If you look at the source for [ThemesDictionary](https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui/Markup/ThemesDictionary.cs) you can see that all it does is build that `Uri` for whichever `Theme` is selected.

```cs
Source = new Uri(
    $"{ApplicationThemeManager.ThemesDictionaryPath}{themeName}.xaml",
    UriKind.Absolute
);
```

The `ApplicationThemeManager` defines the `ThemesDictionaryPath`.

```cs
internal const string ThemesDictionaryPath =
        "pack://application:,,,/Wpf.Ui;component/Resources/Theme/";
```

So, no, it won't affect the normal operation of other components. It will let you use `StaticResource` to reference them.

The main problem with doing that is that those will always reference to the `Dark` theme. If you wanted to reference the currently selected `Theme`, you would just use the `DynamicResource` markup instead. You can view the resource names [here](https://github.com/lepoco/wpfui/blob/main/src/Wpf.Ui/Resources/Theme/Dark.xaml).

**Comment by melinyi** [comment]
I understand. Thank you

**Comment by melinyi** [comment]
closed
