### ISSUE TITLE
Cannot use it in .NET Framework 4.8.1 - ThemesDictionary does not exist in namespace

### ISSUE THREAD

**Issue by Symbai** [lepoco/wpfui#786]
### Describe the bug

Same issue as #584 but this was closed without providing an answer (@RaphMar2021)

![image](https://github.com/lepoco/wpfui/assets/14368203/c6b1f7b7-80f1-4e70-942c-fb6c863a5370)

### To Reproduce

Create WPF project based on .NET Framework 4.8.1 and add WPFUI v3.3.2.5 from Nuget and following install instruction from Github

### Expected behavior

Works on .NET framework

### OS version

W11

### .NET version

.NET framework 4.8.1

### WPF-UI NuGet version

3.3.2.5

**Comment by MrCosmo** [comment]
I don't think you should start a new project on such an old framework.
Why not use Net7 (or Net6 if you prefer LTS)?

**Comment by Symbai** [comment]
Because I have to make a small program that doesn't require me to ship 200mb large runtime with it or forces people to install it. Anyway the problem was the Nuget package. There is a version with a dot that produces the error, I had to use the nuget package with a minus instead.
