### ISSUE TITLE
No component is showing up.

### ISSUE THREAD

**Issue by 9-SK** [lepoco/wpfui#791]
### Describe the bug

Hi there, I am trying to use WPF UI in my project with .NET 7.0 normal WPF, whatever I do, nothing shows up, there are no errors too. I followed the tutorial, nothing happens

### To Reproduce

1. Download
2. Setup the XAML
3. Setup up CS
4. Run

### Expected behavior

The controls to appear

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/89019214/2f14226e-ee8f-41f4-a1e3-abfffc8da0da)
![image](https://github.com/lepoco/wpfui/assets/89019214/aedef12f-815c-4406-9ebf-f61c45f8fc20)

### OS version

Windows 11

### .NET version

.NET 7.0

### WPF-UI NuGet version

2.1

**Comment by 9-SK** [comment]
**UPDATE** I think the error is because of this: 
![image](https://github.com/lepoco/wpfui/assets/89019214/55c37dc9-2590-46a2-83d8-678a68f08c33)

**Comment by GalaxyGaming2OOO** [comment]
weird i get the error but i can still add the controls and stuff in my vs 2022 project so i don't think its that did you remember to add the references to the app.xmal and the xmal file you are trying to get the controls in? also are controls appearing in the toolbox?

**Comment by 9-SK** [comment]
> weird i get the error but i can still add the controls and stuff in my vs 2022 project so i don't think its that did you remember to add the references to the app.xmal and the xmal file you are trying to get the controls in? also are controls appearing in the toolbox?
> 
> (oh yeah for infobars make sure isopen is true)

Yes, all of that is finished, I used the extension now it works!
