### ISSUE TITLE
Disabled Item Error in ComboBox

### ISSUE THREAD

**Issue by Taiizor** [lepoco/wpfui#794]
### Describe the bug

An error occurs if the IsEnabled property of any item in the ComboBox component is set to false.

### To Reproduce

`ComboBox Test = new()

Test.Items.Add(new ComboBoxItem()
{
    IsEnabled = true,
    Content = "True"
});

Test.Items.Add(new ComboBoxItem()
{
    IsEnabled = false,
    Content = "False"
});`

### Expected behavior

No error occurs.

### Screenshots

3.0.0-preview.7
![Sucrose](https://github.com/lepoco/wpfui/assets/41683699/453c4e3d-a341-4cf1-bc74-5cae28d423c1)

3.0.0-preview.8
![Sucrose](https://github.com/lepoco/wpfui/assets/41683699/30224a3f-538d-4066-a8e9-548d857f826a)

### OS version

Windows 11 22621.2428

### .NET version

.NET 8

### WPF-UI NuGet version

3.0.0-preview.8 - 3.0.0-preview.9 - 3.0.0-preview.10

**Comment by wfjsw** [comment]
[aff99851](https://github.com/lepoco/wpfui/pull/788)

https://github.com/lepoco/wpfui/blob/64a4c83dcf6576bbc2bad1285cfb705bde7ec81c/src/Wpf.Ui/Controls/ComboBox/ComboBox.xaml#L143

**Comment by Taiizor** [comment]
Solved in 3.0.0-preview.10

**Comment by pomianowski** [comment]
CC @niels9001

**Comment by niels9001** [comment]
PR to fix this issue: https://github.com/lepoco/wpfui/pull/839
