### ISSUE TITLE
WPF UI Dialog with one button, not with two

### ISSUE THREAD

**Issue by alxkalinin** [lepoco/wpfui#80]
I want to create a "Progress Bar Dialog" with only one button "Close" if we need to stop the process. The "wpfui:Dialog" is perfectly works for that purposes, but "wpfui:Dialog" has two buttons by default. 

What is the best way to get the same "wpfui:Dialog", but with one button?

**Comment by MajorXAML** [comment]
This can easily be done by adding dependency property in [wpfui](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/Dialog.cs). Something like `IsLeftButtonVisible` and then bind in the xaml.

**Comment by alxkalinin** [comment]
> This can easily be done by adding dependency property in [wpfui](https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/Dialog.cs). Something like `IsLeftButtonVisible` and then bind in the xaml.

Thanks, it seems to be a good solution. I can try to make a pull request if this solution is aligned with wpf ui architecture.
