### ISSUE TITLE
Using the Closing event of the ContentDialog causes a crash

### ISSUE THREAD

**Issue by IOL0ol1** [lepoco/wpfui#805]
### Describe the bug

There's a bug here:    
https://github.com/lepoco/wpfui/blob/a58feed8d00f230a95f647cb14054818a8ca4a6d/src/Wpf.Ui/Controls/ContentDialog/ContentDialog.cs#L607

### To Reproduce

```csharp
var dialog = new ContentDialog(contentPresenter);   
dialog.Closing += AnyMethod;
var result = await dialog.ShowAsync();
```

it's will throw a exception when close dialog.

### Expected behavior

No exception

### OS version

any version

### .NET version

any version

### WPF-UI NuGet version

3.0.0-preview.7

**Comment by niels9001** [comment]
Fixed in #806
