### ISSUE TITLE
Button IsDefault setting

### ISSUE THREAD

**Issue by PiousVenom** [lepoco/wpfui#81]
**Is your feature request related to a problem? Please describe.**
Currently, the Button control has no option for "IsDefault".

**Describe the solution you'd like**
I'd like to set a button on my page to "IsDefault=true" so that when I hit the enter button, it performs the action for that button.

**Describe alternatives you've considered**
Not using the WPFUI Button control.

**Comment by MajorXAML** [comment]
Can be fixed by replacing `System.Windows.Controls.Primitives.ButtonBase` with `System.Windows.Controls.Button`
https://github.com/lepoco/wpfui/blob/main/WPFUI/Controls/Button.cs#L17
