### ISSUE TITLE
Pull the latest project and replace the theme exception after running

### ISSUE THREAD

**Issue by wch66** [lepoco/wpfui#823]
### Describe the bug

Pull the latest project and replace the theme exception after running，I Dont Konw WHy?
![image](https://github.com/lepoco/wpfui/assets/36251958/30b9eec4-1f7e-4719-b112-69d5013aac82)

### To Reproduce

The original project has not changed

### Expected behavior

The original project has not changed

### OS version

Windwos 10

### .NET version

Net 6.0

### WPF-UI NuGet version

Preview3.0.0，The latest version

**Comment by niels9001** [comment]
@wch66 Could you try preview.10 to see if this issue is resolved?

**Comment by niels9001** [comment]
@wch66 `Preview.12` is available now - mind checking if that resolves the issue?

**Comment by wch66** [comment]
After testing, the issue has been resolved。
