### ISSUE TITLE
Password Box

### ISSUE THREAD

**Issue by GiuseppeIII** [lepoco/wpfui#84]
Amazing library! Thanks for creating this!
Are there any plans on creating an updated password box like this: https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/controls/password-box.md
I am especially interested in the placeholder text alongside the password reveal button!

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/blob/2fd11ff1b0ac7cf7ba7d1adce3ee4a1080181d1b/WPFUI/Controls/PasswordBox.cs#L18
