### ISSUE TITLE
cf8468a breaks apps that don't use `Application.Current`

### ISSUE THREAD

**Issue by chucker** [lepoco/wpfui#841]
### Describe the bug

Starting with commit cf8468a3f86ce7fa56f75405c707b595706f9d77 and therefore `3.0-preview8`, you can no longer use theming on buttons if your app doesn't use the `Application.Current` app lifetime. (In my case, because the main portion of the app is WinForms.)

### To Reproduce

In an empty WPF app, add a button to `MainWindow.xaml`:

```xaml
<wpfui:Button
	Width="100"
	Height="40"
	Appearance="Primary">
	Hello
</wpfui:Button>
```

Then, replace the constructor with:

```csharp
public MainWindow()
{
    foreach (var uri in new[]
    {
        "pack://application:,,,/Wpf.Ui;component/Resources/Theme/Light.xaml",
        "pack://application:,,,/Wpf.Ui;component/Resources/Wpf.Ui.xaml"
    })
    {
        resources.MergedDictionaries.Add(new ResourceDictionary { Source = new Uri(uri) });
    }
    InitializeComponent();
}
```

This will throw:

>System.Windows.Markup.XamlParseException: ''Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.' Line number '308' and line position '6'.'
>
>Exception: Cannot find resource named 'SystemAccentColorPrimary'. Resource names are case sensitive.

Unfortunately, that's still the case if I explicitly add the resource to my window:

```csharp
Resources["SystemAccentColorPrimary"] = Colors.Red; // still throws!
```

Only if I explicitly add it to the _application_'s resources does the exception go away:

```csharp
Application.Current.Resources["SystemAccentColorPrimary"] = Colors.Red; // works, but I'd rather avoid it
```

### Expected behavior

WpfUi should IMHO avoid tight coupling with `Application.Current`. While fine for apps that newly or entirely WpfUi styling, this approach isn't ideal for apps that want to _transition_ to use it in places. There are previous discussions on this in #837, #662, #668, etc.

### OS version

Windows 11 22H2 23590.1000

### .NET version

.NET Framework 4.7.2; .NET 7

### WPF-UI NuGet version

3.0 previews 8 through 10, but not preview 7, nor 2.1.

**Comment by pomianowski** [comment]
https://github.com/lepoco/wpfui/pull/840 related
