### ISSUE TITLE
no found SystemAccentColorPrimary

### ISSUE THREAD

**Issue by melinyi** [lepoco/wpfui#842]
### Describe the bug

System Windows Markup XamlParseException: "An exception was thrown while providing a value on 'System. Windows. Markup. StaticResourceHolder'

Exception: Unable to find a resource named 'SystemAccentColorPrimary'. Resource names are case sensitive.

### To Reproduce

SystemAccentColorPrimary

### Expected behavior

SystemAccentColorPrimary

### OS version

WIN11

### .NET version

6.0

### WPF-UI NuGet version

PR6.0 UP PR10.0

**Comment by mmadej20** [comment]
One of the workaround is to add 
`Wpf.Ui.Appearance.ApplicationThemeManager.Apply(Wpf.Ui.Appearance.ApplicationTheme.Light);` or `Wpf.Ui.Appearance.SystemThemeWatcher.Watch(this);` 
in MainWindow.xaml.cs before `InitializeComponent()`
