### ISSUE TITLE
NumberBox isn't rendered until clicked on

### ISSUE THREAD

**Issue by jhert0** [lepoco/wpfui#849]
### Describe the bug

NumberBox is not being rendered on screen until after being clicked.

### To Reproduce

1. Add a NumberBox to a Window.
2. Open window.
3. NumberBox doesn't render until clicked.

### Expected behavior

NumberBox renders properly without being interacted with.

### OS version

Windows 11

### .NET version

.NET 6

### WPF-UI NuGet version

3.0.0-preview.11

**Comment by syntax-tm** [comment]
Worth noting that this only occurs when you're using the default `Window` control instead of a `FluentWindow`.

**Comment by jhert0** [comment]
This doesn't seem to be happening anymore.
