### ISSUE TITLE
FluentWindow dose not have a title bar

### ISSUE THREAD

**Issue by Yuval-pa** [lepoco/wpfui#862]
### Describe the bug

Fluent window dose not have window controls (close, minimize, full screen) 

### To Reproduce

In Windows 10:
* open a new Wpf .Net Framework 4.8 project
* follow the instructions in the getting started section of the repo
* convert `MainWindow` into a FluentWindow
* Debug the app

### Expected behavior

I want to be able to exit or minimize the program.
or in other words: I want to see this buttons: 
![image](https://github.com/lepoco/wpfui/assets/117012304/66ed6703-3ce7-40b0-8693-ff46f4836126)

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/117012304/6aae96fc-52f7-46ad-b728-1dc88f659f07)
how the window looks when debugging.

### OS version

Windows 10 Pro 22H2

### .NET version

.Net Framework 4.8

### WPF-UI NuGet version

3.0.0-preview.12

**Comment by syntax-tm** [comment]
You should just add the TitleBar control manually. You can just use a `Grid` with the top row height set to `Auto` or a `DockPanel` with the `TitleBar` docked to the top with `DockPanel.Dock="Top"`. I tested .NET Framework 4.8 as well as .NET 7 and both worked fine.

```xaml
<ui:FluentWindow x:Class="TestWpfApp.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"
                 mc:Ignorable="d"
                 Width="1280" Height="720">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <ui:TitleBar Title="Test Wpf App" />
        <Grid Grid.Row="1">
            <!-- place whatever content here -->
        </Grid>
    </Grid>
</ui:FluentWindow>
```

Result:

![image](https://github.com/lepoco/wpfui/assets/13120514/b1794c84-c1ba-4667-a32c-e6a4e0f55cf6)

**Comment by Yuval-pa** [comment]
thank you!
