### ISSUE TITLE
WPF UI Gallery Problem

### ISSUE THREAD

**Issue by Chettra7** [lepoco/wpfui#865]
### Describe the bug

ui:NavigationView not work
![Screenshot 2023-12-08 090024](https://github.com/lepoco/wpfui/assets/40337337/cbb88be1-cc09-4acc-85dd-9813a767d8c2)

### To Reproduce

ui:NavigationView PaneDisplayMode="Top" not work

### Expected behavior

![Screenshot 2023-12-08 090024](https://github.com/lepoco/wpfui/assets/40337337/adf577b3-3100-44c4-9139-e0081a59d20d)

### Screenshots

![Screenshot 2023-12-08 085850](https://github.com/lepoco/wpfui/assets/40337337/3253acac-73fb-4be6-9e07-0ddafb6ea27c)

### OS version

2.1.0

### .NET version

4.7.2

### WPF-UI NuGet version

2.1.0

### Additional context

        <ui:NavigationView PaneDisplayMode="Top" >
            <ui:NavigationView.MenuItems>
                <ui:NavigationViewItem Content="Home" Icon="Home24" />
            <ui:NavigationView.MenuItems/>
        <ui:NavigationView />

**Comment by niels9001** [comment]
@Chettra7 Can you try `Preview.12` to see if that resolves the issue?

**Comment by Chettra7** [comment]
I have try preview version it’s work. Thank you☺️

**Comment by niels9001** [comment]
@Chettra7 Great to hear! Glad it's fixed!

**Comment by Chettra7** [comment]
Hello sir! I have try binding Password value (MVVM) but I can get only value '****'. Please help me the right binding 
Here is my xaml:  <ui:PasswordBox PlaceholderText="Password" Text="{Binding PASSWORD,Mode=TwoWay}" ></ui:PasswordBox>
