### ISSUE TITLE
Bug : 'Could not load file or assembly 'WPFUI, PublicKeyToken=null'

### ISSUE THREAD

**Issue by turswiming** [lepoco/wpfui#870]
### Describe the bug

I try to use wpfUI in .NET framework 4.8. When opening a window, it throws an error called
 " System.Windows.Markup.XamlParseException: 'Could not load file or assembly 'Wpf.Ui, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'"

Thanks! This is my first error reported at github!

### To Reproduce

```xaml
<Application
    x:Class=" FrontEndRevit.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"
    DispatcherUnhandledException="OnDispatcherUnhandledException"
    Exit="OnExit"
    Startup="OnStartup">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemesDictionary Theme="Dark" />
                <ui:ControlsDictionary />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

my code is:
```cs
namespace FrontEndRevit.Source.UI
{
    /// <summary>
    /// Interaction logic for Window1.xaml
    /// </summary>
    public partial class MainPage : Window
    {
        public MainPage()
        {
            InitializeComponent();//throw error here
        }
    }
}
```
this is the Page.xaml corresponding the cs file:
```xaml
<Window x:Class="FrontEndRevit.Source.UI.MainPage"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:FrontEndRevit.Source.UI"
        xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml"
        mc:Ignorable="d"
        Title="Window1" Height="450" Width="800">
    <Grid>
        <ui:SymbolIcon Symbol="Fluent24"/> <--! if I remove this line, it won`t throw error-->


    </Grid>
</Window>

```

### Expected behavior

it should show window.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/71206440/758eb357-1f49-49e4-86a2-1f4f2533c85a)

### OS version

win 11

### .NET version

.net framework 4.8

### WPF-UI NuGet version

2.1.0. This bug can be also reproduced at 1.27.

### Additional context

I copied some file from visual studio WPFUI template.

**Comment by turswiming** [comment]
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Could not load file or assembly 'Wpf.Ui, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at FrontEndRevit.Source.UI.MainPage.InitializeComponent() in C:\GitLib\FrontEndRevit\FrontEndRevit\Source\UI\MainPage\MainPage.xaml:line 1

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Wpf.Ui, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by turswiming** [comment]
I solve it. The compiler assumes I didn't use wpfui, and removes dll automatically. I just need to call wpfui in .cs

**Comment by EphraimElgrabli** [comment]
Hi can you be more detailed about how did you solve it? cuz even tho ive im using it in the .cs, it stills give me this error.

**Comment by turswiming** [comment]
if you just call some directly e.g. read some value but not use it, it may still be pruned. For me, I add these: 
```cs
        /// <summary>
        /// don't have any meaning.  
        /// this function aims to invoke the lib, and make sure the Wpf.Ui.dll not be deleted automatically
        /// </summary>
        public static void InvokeWPFUILib()
        {
            //call a type in the lib
            Wpf.Ui.Appearance.ApplicationTheme theme = Wpf.Ui.Appearance.ApplicationTheme.Dark;
            //edit the return value, make sure the call before is not optimized
            int a = (int)theme++;
        }
```

**Comment by EphraimElgrabli** [comment]
well, I still got the same error. thanks anyway.

**Comment by turswiming** [comment]
can you provide more details? like .net version, your env and others?
