### ISSUE TITLE
Horizontal Scroll bars

### ISSUE THREAD

**Issue by U-C-S** [lepoco/wpfui#89]
Currently, Vertical Scroll bars works good
![image](https://user-images.githubusercontent.com/50218121/157241037-1c1aa515-f1e4-48d7-beb4-35b9be8dc2e6.png)

But Horizontal scroll bars seems to look like this..... Just up and down arrows and 0 scroll length (despite being horizontally scrollable with normal wpf controls
![image](https://user-images.githubusercontent.com/50218121/157241076-5e7340dd-f7ff-4381-89e0-8f7256d4760a.png)

**Comment by U-C-S** [comment]
yeh, Exact issue

I just searched for "scroll" and it didn't appear 😅
Closing

**Comment by djklesk** [comment]
how to  fix the horizonal scrollbar? it tryed everything... i fixed the style but the horizonal scrollbar isnt working at all...
it appears for a second on on ui init but then its always invisible and impossible to interact with it... no mouseover, no click nothing is working
