### ISSUE TITLE
Arc not resizing correctly

### ISSUE THREAD

**Issue by ElectroAttacks** [lepoco/wpfui#903]
### Describe the bug

When you try resizing the Arc Control by changing its height/ widht properties or refreshing a data binding between them, the control will not behave as expected. The control will only resize based on one of these two properties and you cannot force a redraw.

This behavior leeds to weird graphs that are more like an ellipse than a circle/ proper arc.

### To Reproduce

Use the Arc Control within a panel/ grid, so that it's hight is defined by it's container. 
Bind it's Width property like so: 
`Width="{Binding RelativeSource={RelativeSource Self}, Path=ActualHeight}"`

Resize the Window/ Page multiple times by maximizing it for example.

### Expected behavior

The Arc should resize, due to the fact that it's actually receiving the correct values.

### OS version

Windows 11 Pro (22H2)

### .NET version

.Net 7.0 

### WPF-UI NuGet version

2.1.0

**Comment by m0lDaViA** [comment]
Hello @ElectroAttacks !
This issue got fixed here #1067 so you can close this issue.
