### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by realcnk** [lepoco/wpfui#91]
Hi.

The demo does not work for me, I try to run it but it gives me an error indicating that I have to add an executable to the project. How can I do it?

Thanks.

**Comment by pomianowski** [comment]
Have you selected WPFUI.Demo as your startup project?
![image](https://user-images.githubusercontent.com/13592821/157953385-aac11b08-2438-4d76-8ea9-a45b539121cc.png)

**Comment by realcnk** [comment]
Thank you man, it¡s works. I'm noob with this.
