### ISSUE TITLE
Template without forced copyright

### ISSUE THREAD

**Issue by KillyMXI** [lepoco/wpfui#914]
### Is your feature request related to a problem? Please describe

I can't use provided templates.
Even so called "blank" template is plastered with license text in every *.cs file.

MIT license doesn't allow to remove it. But the forced copyright has nothing to do with the actual purpose of the application that will contain it.

### Describe the solution you'd like

C'mon!
Be humble, don't claim the copyright on templates you provide so people can use your project!

What you put into templates should be considered trivial and not legally binding.
Alternatively, it is equivalent to the documentation. Following public documentation is also not legally binding.

All I have to do is to respect the license of the package itself, which is an external dependency to my code.

### Describe alternatives you've considered

Ignore templates, follow the documentation from the ground up - that's what I have to do.
This costs me some time, increases the risk of mistakes, removes the opportunity to suggest recommended project structure.

**Comment by GalaxyGaming2OOO** [comment]
yeah i had to end up looking at the code to figure out what to do
even then i dont fully know what i am doing

**Comment by KillyMXI** [comment]
There seems to be a larger issue for those starting with WPF UI around now - the library is in transition between major versions, a lot of breaking changes.
Documentation, templates, repository structure, code - all out of sync.
All repo links are broken. Templates break when updating the package to a newer "prerelease".
So yeah, can only rely on the code for now.

Wish it was handled better, with clearer separation between versions in documentation and repository. (Probably too much to ask when a project gets as much attention as it can justify.)

This issue is still a valid point of concern, assuming WPF UI is not abandoned and will eventually reach a synced state across all documentation and code.

**Comment by m0lDaViA** [comment]
You wanna write the documentation? 😁

**Comment by KillyMXI** [comment]
This issue is about removing license text from templates, to prevent license poisoning.
Doesn't matter that MIT is the most liberal license.

If you read carefully, I wasn't expecting documentation improvements. It was mostly a response to another comment. While it felt relatable, I kept it out of my issue text. Being new to the project, I wasn't familiar with its cadence to know whether these transition issues are under control to point them out intently.

If you need help with something - start from guiding people into helping you - show the things you recognize as incomplete and are ready to delegate.

My involvement with WPF-UI is likely to end up very limited - just a prototype of a tool for internal use, likely to change down the line. I don't have other projects with comparable documentation experience to transfer good documentation experience without significant time investment. I'm torn apart between other projects already. So, volunteering for this project is far down the list of things I could do myself.
