### ISSUE TITLE
'NotifyIcon' missing from XML namespace 'http://schemas.lepo.co/wpfui/2022/xaml/tray'

### ISSUE THREAD

**Issue by po-trottier** [lepoco/wpfui#922]
### Describe the bug

Attempting to add a Tray Icon as described in the documentation results in a compilation error:
```
Error MC3074 : The tag 'NotifyIcon' does not exist in XML namespace 'http://schemas.lepo.co/wpfui/2022/xaml/tray'
```

### To Reproduce

- Add a NotifyIcon control to your MainWindow.xaml:
    ```
    <tray:NotifyIcon
        Grid.Row="0"
        FocusOnLeftClick="True"
        Icon="pack://application:,,,/Assets/wpfui.png"
        MenuOnRightClick="True"
        TooltipText="WPF UI">
            <tray:NotifyIcon.Menu>
               <ContextMenu ItemsSource = "{Binding ViewModel.TrayMenuItems, Mode=OneWay}" />
            </tray:NotifyIcon.Menu>
    </tray:NotifyIcon>
    ```
- Add the tray namespace to your MainWindow.xaml:
    ```
    xmlns:tray="http://schemas.lepo.co/wpfui/2022/xaml/tray"
    ```

### Expected behavior

The control should resolve correctly.

### Screenshots

![image](https://github.com/lepoco/wpfui/assets/41876093/6745bab7-b4fc-4793-accb-988332f82402)

### OS version

Windows 11 Pro - 23H2

### .NET version

net8.0-windows

### WPF-UI NuGet version

3.0.0-preview.13

**Comment by po-trottier** [comment]
Seemd like `ui:Hyperlink` is also missing from  `http://schemas.lepo.co/wpfui/2022/xaml`

**Comment by jackBonadies** [comment]
Not sure if this is your issue, but NotifyIcon is in a separate Nuget package (WPF-UI.Tray)

**Comment by po-trottier** [comment]
Yeah that solved the missing reference for the Tray, thanks! 
Also ui:Hyperlink should be ui:HyperlinkButton.

Is there any reason why Tray is not part of the base package or a dependency of the base package? Also this should probably be described somewhere in the documentation

**Comment by pomianowski** [comment]
Hey @po-trottier, tray has been taken into a separate package so that WPF-UI does not have any external dependencies.
