### ISSUE TITLE
The content of the ContextMenu is not displayed when right-clicking on the tray icon.

### ISSUE THREAD

**Issue by acinside** [lepoco/wpfui#933]
### Describe the bug

The content of the ContextMenu is not displayed when right-clicking on the tray icon.

### To Reproduce

xmlns:tray="http://schemas.lepo.co/wpfui/2022/xaml/tray"

<tray:NotifyIcon
    Grid.Row="0"
    FocusOnLeftClick="True"
    Icon="pack://application:,,,/Assets/wpfui-icon-256.png"
    MenuOnRightClick="True"
    TooltipText="WPF UI - MVVM Demo">
    <tray:NotifyIcon.Menu>
        <ContextMenu ItemsSource="{Binding ViewModel.TrayMenuItems, Mode=OneWay}">
        </ContextMenu>
    </tray:NotifyIcon.Menu>
</tray:NotifyIcon>

-MainWindowViewModel
        [ObservableProperty]
        private ObservableCollection<Wpf.Ui.Controls.MenuItem> _trayMenuItems =
            new()
            {
                new Wpf.Ui.Controls.MenuItem { Header = "Home", Tag = "tray_home" },
                new Wpf.Ui.Controls.MenuItem { Header = "Close", Tag = "tray_close" },
            };

### Expected behavior

The same issue is observed in the Wpf.Ui.Gallery project as well.

### OS version

windows-10

### .NET version

.Net 8.0

### WPF-UI NuGet version

WPF-UI 3.0.0

**Comment by SalehBagheri** [comment]
I have faced this error:

> NotifyIcon does not exist in the "http://schemas.lepo.co/wpfui/2022/xaml/tray" namespace

It seems there is a problem with NotifyIcon

**Comment by acinside** [comment]
I have installed the WPF-UI.Tray 3.0.0-preview.11 package.
