### ISSUE TITLE
DarkTheme does not work as default

### ISSUE THREAD

**Issue by Sub-Zero-1** [lepoco/wpfui#949]
### Describe the bug

Changing default theme from "Light" to "Dark" in App.xaml does not work. It does not even work in the example Code of the app "Wpf.Ui.Gallery". According to this documentation it should: https://wpfui.lepo.co/documentation/themes.html

### To Reproduce

<Application
  ...
  xmlns:ui="http://schemas.lepo.co/wpfui/2022/xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ui:ThemesDictionary Theme="Dark" />
        <ui:ControlsDictionary />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
-> Still "Light"

### Expected behavior

The app should start in Dark-Mode.

### OS version

Windows 10

### .NET version

8.0

### WPF-UI NuGet version

3.0.0

**Comment by ericbyrd** [comment]
@Sub-Zero-1 see here: https://github.com/lepoco/wpfui/issues/935#issue-2122061833.  That fix worked for me.  Unfortunate that there isn't any documentation regarding.

**Comment by Sub-Zero-1** [comment]
@ericbyrd Thank you. That works!
