### ISSUE TITLE
No icon in CardExpander

### ISSUE THREAD

**Issue by ToxicSkill** [lepoco/wpfui#953]
### Describe the bug

Each card has icon property, CardExpander has it as well but it is not visible after all

### To Reproduce

Just create one

### Expected behavior

To be visible

### OS version

Win 11 Pro

### .NET version

8.0

### WPF-UI NuGet version

3.0.0

**Comment by kevfrench** [comment]
I created one, and it's displaying the icon fine, What kind of icon are you trying to assign?

```<ui:CardExpander Icon="{ui:SymbolIcon AlertBadge24}" />```
