### ISSUE TITLE
MenuItem Icon not properly rendering

### ISSUE THREAD

**Issue by mwpowellhtx** [lepoco/wpfui#958]
### Describe the bug

In my view model:

```csharp
public class ToolsControllerViewModel : ObservableObject
{
    // Property declaration
    public virtual BitmapImage LocalSecurityPolicyImage { get; private set; }

    // in the ctor...
    public ToolsControllerViewModel()
    {
        // ...
        LocalSecurityPolicyImage = new BitmapImage(new Uri(@"..\Resources\secpol_16x.png", UriKind.Relative));
    }
}
```

And in the corresponding XAML view:
```xml
<ui:MenuItem Header="_Local Security Policy" Command="{Binding LocalSecurityPolicyCommand}">
    <MenuItem.Icon>
        <Image Source="{Binding LocalSecurityPolicyImage}" />
    </MenuItem.Icon>
</ui:MenuItem>
```

### To Reproduce

As far as I can tell the XAML is good, this is broadly accepted as "the WPF way" of doing things, if I read the SO various blogs, so I cannot understand why it would not work in this case. Except perhaps aluded to via [this report](https://github.com/lepoco/wpfui/issues/168), in which it might be suggested that somehow the icon is treated as a glyph, and not a first class bitmap (`.png`) resource.

### Expected behavior

The bitmap is loading in correctly, the path is resolved and I have an image instance correctly.

Yet there is no rendering in the menu.

I would expect that a bitmap icon should be able to render properly.

Unless you've overridden `Icon` for a `SymbolIcon` which it seems like maybe you have. I definitely do not want a `FontIcon`, that;s not appropriate for this use case, I want the actual bitmap image.

### OS version

W10 Pro x64, 19041.685

### .NET version

Targeting `net8` in this case (as far as I know)

### WPF-UI NuGet version

`3.0` the latest from nuget.

### Additional context

So... all things considered, `Wpf.Ui.Controls.MenuItem` does not seem like the right for for these sort of use cases.

Question, am I losing that much by defaulting to the WPF `System.Windows.Controls.MenuItem`?

Or framed in the other direction, what else am I gaining by sticking with the `Wpf.Ui.Controls.MenuItem`, and what would it take to extend support for a proper bitmap image?

**Comment by mwpowellhtx** [comment]
Also possibly worth mentioning, the parent `_Tools` menu is also `Wpf.Ui.Controls.MenuItem`, some maybe something in the way its children are treated is also interfering, I do not know. Tried also in the `PresentationFramework` `System.Windows.Controls.MenuItem` base case, also not working, which is strange. Verified that the images are correctly embedded as resources, and the `Uri` is correct, as I stated.

**Comment by mwpowellhtx** [comment]
After some tinkering, this is about as close as I can get to properly mapping the XAML with the underlying view model bindings. Still no joy, not showing the icon images properly.

```xml
<ui:MenuItem Header="_Local Security Policy" Command="{Binding LocalSecurityPolicyCommand}">
    <ui:MenuItem.Icon>
        <ui:ImageIcon Source="{Binding LocalSecurityPolicyImage}" />
    </ui:MenuItem.Icon>
</ui:MenuItem>
```

After some digging, seems like `ImageIcon.Source` is the correct path for making this work, but it is not working.

`ui` mapped to the `Wpf.Ui.Controls` namespace in the XAML.

**Comment by mwpowellhtx** [comment]
Anyone at all, am I doing something incorrectly, is there a workaround for this?

**Comment by SalehBagheri** [comment]
Just note that some objects such as "BitmapImage", "Color" etc. are freezable, and you have to freeze them before assigning them to the ViewModel. I'm not sure this is your real problem, but you can try!

```csharp
var image = new BitmapImage(new Uri(@"..\Resources\secpol_16x.png", UriKind.Relative));
image.Freeze();
LocalSecurityPolicyImage = image;
```

**Comment by mwpowellhtx** [comment]
Issue sorted.

Change file _Build Action_ to _Resource_, which is apparently to WPF _"this is the way"_. the asset is still embedded but is there instead for WPF visibility.

And in the view model this adjustment:

```csharp
```csharp
const UriKind absolute = UriKind.Absolute;
LocalSecurityPolicyImage = new BitmapImage(new Uri("pack://application:,,,/Resources/secpol_16x.png", absolute));
```

Explained in the [_Microsoft_ docs](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/app-development/wpf-application-resource-content-and-data-files).

**Comment by mwpowellhtx** [comment]
Draft intermediate result.

![image](https://github.com/lepoco/wpfui/assets/1824187/17caac16-376d-46ee-b3e0-8442bef00514)
