### ISSUE TITLE
PasswordBox input overflows component

### ISSUE THREAD

**Issue by timokoessler** [lepoco/wpfui#973]
### Describe the bug

If I enter more characters in a password field than it is wide, the additional characters are no longer visible and the cursor moves outside the PasswordBox.

### To Reproduce

Check out PasswordBox Page in WPF UI Gallery.

### Expected behavior

The behavior should be the same as a normal TextBox.

### Screenshots

![Screenshot 2024-02-26 083539](https://github.com/lepoco/wpfui/assets/33259218/8abdacda-be65-4af8-8543-21a8f13c7264)

### OS version

Windows 11 23H2 (Build 22631.3155)

### .NET version

.NET 8.0

### WPF-UI NuGet version

3.0.0

**Comment by tmijail** [comment]
Related: #497
