### ISSUE TITLE
无法发布应用程序

### ISSUE THREAD

**Issue by input111** [lepoco/wpfui#976]
### Describe the bug

发布应用程序发生错误

### To Reproduce

发布应用程序发生错误

### Expected behavior

可以发布应用程序

### Screenshots

![0ab219b7bf1fe845e6d1c94a59d5804](https://github.com/lepoco/wpfui/assets/101310122/447b6554-3fb9-47de-956e-e81501a5d452)

### OS version

Win11
设备名称	DESKTOP-OOLG8PE
处理器	11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz   2.61 GHz
机带 RAM	32.0 GB (31.7 GB 可用)
设备 ID	D9888029-580B-49BA-A68A-5556B42250D2
产品 ID	00328-90000-00000-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

### .NET version

无

### WPF-UI NuGet version

无

**Comment by lingme** [comment]
shouldn't you check the error log first? Instead of raising an issue directly, or if you insist on raising a issues, you should also attach an error log.
