### ISSUE TITLE
Bug: Tooltips showing only for a fraction of a second

### ISSUE THREAD

**Issue by Ch0pstix** [lepoco/wpfui#98]
**Describe the bug**  
When the mouse hovers over a control that is assigned tooltip text, the tooltip only appears for a fraction of a second then disappears.

**To Reproduce**  
1. Create a new project, and add WPFUI.
2. Add style refs, etc...
3. Create a control (eg. Button) and assign tooltip text.
4. Run the app and hover over the button with the tooltip text.

**Expected behavior**  
The tooltip should stay open for about 4 seconds (seems to be the native behavior) after hovering over the control.

**Screenshots**  

![wpfui-bugreport-tooltip](https://user-images.githubusercontent.com/96277815/158629688-e9dc8339-5423-40fe-b686-d6e763bd1c85.gif)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - .NET: net6.0-windows10.0.19041.0
 - Version: 1.2.2-prerelease157

**Comment by Ch0pstix** [comment]
@pomianowski Upon further inspection, it seems to be an issue on .NET 6 with WPF ([#5716](https://github.com/dotnet/wpf/issues/5716)), not a problem caused by your library. Closing.

**Comment by pomianowski** [comment]
It looks like the bug for .NET 6 has now been fixed.
